### PR TITLE
[Buildpacks] Files should belong to the default, non-root, user

### LINKED ISSUE #3187: Rails buildpack permissions fail
### Expected behavior

Skaffold succeeds in building the image

### Actual behavior

Skaffold fails in building the image

### Information

- Skaffold version: v0.41.0-170-ga29ee9ae
- Operating system: Darwin 19.0.0 Darwin Kernel Version 19.0.0
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1
kind: Config
build:
  local:
    push: false
  artifacts:
  - image: something
    buildpack:
      builder: "heroku/buildpacks"
      dependencies:
        paths:
          - .
```

### Steps to reproduce the behavior

When using the new option to build using buildpacks, a permission error occurs:
```
chmod: changing permissions of 'bin/dev': Operation not permitted
chmod: changing permissions of 'bin/bundle': Operation not permitted
chmod: changing permissions of 'bin/spring': Operation not permitted
chmod: changing permissions of 'bin/rails': Operation not permitted
chmod: changing permissions of 'bin/yarn': Operation not permitted
chmod: changing permissions of 'bin/update': Operation not permitted
chmod: changing permissions of 'bin/setup': Operation not permitted
chmod: changing permissions of 'bin/rake': Operation not permitted


-----> Installing node-v10.15.3-linux-x64

 !
 !     Permission denied @ rb_sysopen - ./node
 !
/tmp/tmp.a3FYFIyAqj/lib/ruby/2.5.0/fileutils.rb:1292:in `initialize': Permission denied @ rb_sysopen - ./node (Errno::EACCES)
        from /tmp/tmp.a3FYFIyAqj/lib/ruby/2.5.0/fileutils.rb:1292:in `open'
        from /tmp/tmp.a3FYFIyAqj/lib/ruby/2.5.0/fileutils.rb:1292:in `block in copy_file'
        from /tmp/tmp.a3FYFIyAqj/lib/ruby/2.5.0/fileutils.rb:1291:in `open'
        from /tmp/tmp.a3FYFIyAqj/lib/ruby/2.5.0/fileutils.rb:1291:in `copy_file'
        from /tmp/tmp.a3FYFIyAqj/lib/ruby/2.5.0/fileutils.rb:1259:in `copy'
        from /tmp/tmp.a3FYFIyAqj/lib/ruby/2.5.0/fileutils.rb:418:in `block in copy_entry'
        from /tmp/tmp.a3FYFIyAqj/lib/ruby/2.5.0/fileutils.rb:1390:in `wrap_traverse'
        from /tmp/tmp.a3FYFIyAqj/lib/ruby/2.5.0/fileutils.rb:415:in `copy_entry'
        from /tmp/tmp.a3FYFIyAqj/lib/ruby/2.5.0/fileutils.rb:473:in `rescue in block in mv'
        from /tmp/tmp.a3FYFIyAqj/lib/ruby/2.5.0/fileutils.rb:470:in `block in mv'
        from /tmp/tmp.a3FYFIyAqj/lib/ruby/2.5.0/fileutils.rb:1463:in `block in fu_each_src_dest'
        from /tmp/tmp.a3FYFIyAqj/lib/ruby/2.5.0/fileutils.rb:1477:in `fu_each_src_dest0'
        from /tmp/tmp.a3FYFIyAqj/lib/ruby/2.5.0/fileutils.rb:1461:in `fu_each_src_dest'
        from /tmp/tmp.a3FYFIyAqj/lib/ruby/2.5.0/fileutils.rb:460:in `mv'
        from /cnb/buildpacks/heroku_ruby/0.0.1/lib/language_pack/helpers/node_installer.rb:27:in `block in install'
        from /tmp/tmp.a3FYFIyAqj/lib/ruby/2.5.0/tmpdir.rb:93:in `mktmpdir'
        from /cnb/buildpacks/heroku_ruby/0.0.1/lib/language_pack/helpers/node_installer.rb:20:in `install'
        from /cnb/buildpacks/heroku_ruby/0.0.1/lib/language_pack/ruby.rb:587:in `block in install_binary'
        from /cnb/buildpacks/heroku_ruby/0.0.1/lib/language_pack/ruby.rb:585:in `chdir'
        from /cnb/buildpacks/heroku_ruby/0.0.1/lib/language_pack/ruby.rb:585:in `install_binary'
        from /cnb/buildpacks/heroku_ruby/0.0.1/lib/language_pack/ruby.rb:573:in `block (2 levels) in install_binaries'
        from /cnb/buildpacks/heroku_ruby/0.0.1/lib/language_pack/ruby.rb:573:in `each'
        from /cnb/buildpacks/heroku_ruby/0.0.1/lib/language_pack/ruby.rb:573:in `block in install_binaries'
        from /cnb/buildpacks/heroku_ruby/0.0.1/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
        from /cnb/buildpacks/heroku_ruby/0.0.1/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
        from /cnb/buildpacks/heroku_ruby/0.0.1/lib/language_pack/instrument.rb:17:in `block in instrument'
        from /tmp/tmp.a3FYFIyAqj/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
        from /cnb/buildpacks/heroku_ruby/0.0.1/lib/language_pack/instrument.rb:16:in `instrument'
        from /cnb/buildpacks/heroku_ruby/0.0.1/lib/language_pack/base.rb:50:in `instrument'
        from /cnb/buildpacks/heroku_ruby/0.0.1/lib/language_pack/base.rb:46:in `instrument'
        from /cnb/buildpacks/heroku_ruby/0.0.1/lib/language_pack/ruby.rb:572:in `install_binaries'
        from /cnb/buildpacks/heroku_ruby/0.0.1/lib/language_pack/ruby.rb:155:in `block in build'
        from /cnb/buildpacks/heroku_ruby/0.0.1/lib/language_pack/ruby.rb:948:in `allow_git'
        from /cnb/buildpacks/heroku_ruby/0.0.1/lib/language_pack/ruby.rb:136:in `build'
        from /cnb/buildpacks/heroku_ruby/0.0.1/lib/language_pack/rails2.rb:69:in `build'
        from /cnb/buildpacks/heroku_ruby/0.0.1/bin/support/ruby_build:26:in `block (2 levels) in <main>'
        from /cnb/buildpacks/heroku_ruby/0.0.1/lib/language_pack/base.rb:189:in `log'
        from /cnb/buildpacks/heroku_ruby/0.0.1/bin/support/ruby_build:25:in `block in <main>'
        from /cnb/buildpacks/heroku_ruby/0.0.1/lib/language_pack/instrument.rb:35:in `block in trace'
        from /cnb/buildpacks/heroku_ruby/0.0.1/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
        from /cnb/buildpacks/heroku_ruby/0.0.1/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
        from /cnb/buildpacks/heroku_ruby/0.0.1/lib/language_pack/instrument.rb:17:in `block in instrument'
        from /tmp/tmp.a3FYFIyAqj/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
        from /cnb/buildpacks/heroku_ruby/0.0.1/lib/language_pack/instrument.rb:16:in `instrument'
        from /cnb/buildpacks/heroku_ruby/0.0.1/lib/language_pack/instrument.rb:35:in `trace'
        from /cnb/buildpacks/heroku_ruby/0.0.1/bin/support/ruby_build:21:in `<main>'
ERROR: failed to build: exit status 1
```

Using the custom option by triggering the external `pack` succeeds though

Contents of skaffold.yaml:
```yaml
apiVersion: skaffold/v1
kind: Config
build:
  local:
    push: false
  artifacts:
  - image: something
    custom:
      buildCommand: ./build.sh
      dependencies:
        paths:
          - .
```

Contents of build.sh
```sh
#!/bin/bash
set -e
images=$(echo $IMAGES | tr " " "\n")

for image in $images
do
    pack build $image --builder heroku/buildpacks:18
    if $PUSH_IMAGE
    then
        docker push $image
    fi
done
```

Result
```
Successfully built image something:sometag
```

### PR DESCRIPTION
**Pull request by dgageot**
Fixes #3187

### CODE REVIEW

File: pkg/skaffold/build/buildpacks/dependencies.go [hunk 1]
```diff
@@ -33,8 +34,27 @@ func GetDependencies(ctx context.Context, workspace string, a *latest.BuildpackA
 		return nil, errors.Wrapf(err, "walking workspace %s", workspace)
 	}
 
-	var dependencies []string
+	// Make sure folders are also listed
+	added := map[string]bool{}
 	for file := range files {
+		for path := file; path != "."; path = filepath.Dir(path) {
```
Comment (briandealwis) [inline pkg/skaffold/build/buildpacks/dependencies.go]: We could speed this up by stopping when a path is already in `added`:
```suggestion
		for path := file; path != "." && !added[path]; path = filepath.Dir(path) {
```

But doesn't this mean that we're now exposing all the contents of those directories too, even if the user specified specific files?  (E.g., `pkg/lib/file.go` will result in dependencies on `pkg/`, `pkg/lib/` too?)

File: pkg/skaffold/build/buildpacks/dependencies.go [hunk 2]
```diff
@@ -33,8 +34,27 @@ func GetDependencies(ctx context.Context, workspace string, a *latest.BuildpackA
...
+	for path := range files {
+		for path != "." {
+			if added[path] {
+				break
+			}
+
+			added[path] = true
+			path = filepath.Dir(path)
+		}
+	}
```
Comment (briandealwis) [inline pkg/skaffold/build/buildpacks/dependencies.go]: Isn't this effectively the same as the code above?

File: pkg/skaffold/util/tar.go [hunk 3]
```diff
@@ -62,109 +86,81 @@ func CreateTarGz(w io.Writer, root string, paths []string) error {
...
-	fi, err := os.Lstat(absPath)
-	if err != nil {
-		return err
-	}
-	switch mode := fi.Mode(); {
-	case mode.IsDir():
-		tarHeader, err := tar.FileInfoHeader(fi, tarPath)
-		if err != nil {
-			return err
+		if filepath.IsAbs(target) {
```
Comment (briandealwis) [inline pkg/skaffold/util/tar.go]: Should we further prevent references that resolve outside of the `context` directory?

File: pkg/skaffold/util/tar.go [hunk 4]
```diff
@@ -62,109 +86,81 @@ func CreateTarGz(w io.Writer, root string, paths []string) error {
...
+	} else {
+		header, err = tar.FileInfoHeader(fi, "")
 		if err != nil {
 			return err
 		}
-		tarHeader.Name = tarPath
+	}
 
-		if err := writeHeader(tw, tarHeader); err != nil {
+	if dst == "" {
```
Comment (briandealwis) [inline pkg/skaffold/util/tar.go]: I haven't looked at this code in detail, but I think *this* is where we should be adding directory entries when necessary rather than returning them in `GetDependencies()`.  (We had the same problem in Jib: GoogleContainerTools/jib#891.) Would you agree?

File: pkg/skaffold/build/buildpacks/dependencies.go (hunk 2 above)
Comment (dgageot) [reply pkg/skaffold/build/buildpacks/dependencies.go]: lol. there are the old and the new optimized version...

File: pkg/skaffold/util/tar.go (hunk 4 above)
Comment (dgageot) [reply pkg/skaffold/util/tar.go]: That's a good idea. I'll do that!

File: pkg/skaffold/build/buildpacks/dependencies.go (hunk 1 above)
Comment (dgageot) [reply pkg/skaffold/build/buildpacks/dependencies.go]: I'll move the code to tar.go where it really belongs

File: pkg/skaffold/docker/containers.go [hunk 5]
```diff
@@ -82,10 +83,10 @@ func (l *localDaemon) runAndLog(ctx context.Context, out io.Writer, containerID
 }
 
 // CopyToContainer copies files to a running container.
-func (l *localDaemon) CopyToContainer(ctx context.Context, container string, dest string, root string, paths []string) error {
+func (l *localDaemon) CopyToContainer(ctx context.Context, container string, dest string, root string, paths []string, uid, gid int, modTime time.Time) error {
 	r, w := io.Pipe()
 	go func() {
-		if err := util.CreateTar(w, root, paths); err != nil {
+		if err := util.CreateTarForBuildpacks(w, root, paths, uid, gid, modTime); err != nil {
```
[the remark this answers is not in the document]
Comment (dgageot) [reply pkg/skaffold/docker/containers.go]: I'll do that

File: pkg/skaffold/util/tar_test.go [hunk 6]
```diff
@@ -61,6 +62,44 @@ func TestCreateTar(t *testing.T) {
...
+		tarFiles := make(map[string]string)
+		tr := tar.NewReader(&b)
+		for {
+			hdr, err := tr.Next()
+			if err == io.EOF {
+				break
+			}
+			t.CheckNoError(err)
+
+			content, err := ioutil.ReadAll(tr)
```
Comment (briandealwis) [inline pkg/skaffold/util/tar_test.go]: Check the uid and gid?

Comment (dgageot) [reply pkg/skaffold/util/tar_test.go]: will do that

Comment (dgageot) [reply pkg/skaffold/util/tar_test.go]: @briandealwis done!

File: pkg/skaffold/util/tar.go [hunk 7]
```diff
@@ -48,21 +51,55 @@ func CreateTar(w io.Writer, root string, paths []string) error {
...
+		header.Gname = ""
+	}
+
+	tw := tar.NewWriter(w)
+	defer tw.Close()
+
+	// Make sure parent folders are added before files
+	// TODO(dgageot): this should probably also be done in CreateTar
+	// but I'd rather not break things that people didn't complain about!
+	added := map[string]bool{}
```
Comment (balopat) [inline pkg/skaffold/util/tar.go]: this is interesting - it might be that (unless like here, you need the parents to have a certain uid/guid/modtime) TAR doesn't need parent folders to be created. Just "filespec, filecontent" serially. If this is the case then we can remove the TODO.
