### PR TITLE
Expand values file paths prefixed with ~

### LINKED ISSUE #2123: skaffold helm valuesFiles does not handle tilde sign
### Expected behavior
skaffold run should be able to use and supply values from file in the home directory
### Actual behavior
skaffold run fails with an error of "no such file or directory"
### Information

- Skaffold version: version...v0.29.0
- Operating system: ...Ubuntu
- Contents of skaffold.yaml:

```yaml
<---
apiVersion: skaffold/v1beta10
kind: Config
build:
  artifacts:
    - image: niftyhoot
      context: src
deploy:
  helm:
    releases:
    - name: dev
      chartPath: minis
      valuesFiles:
        - ~/.helm/curr-profile.yaml
      values:
        myImage: niftyhoot
      setValues:
        tenentGroup: dev
>
```

### PR DESCRIPTION
**Pull request by cedrickring**
Fixes #2123

### CODE REVIEW

File: pkg/skaffold/deploy/helm_test.go [hunk 1]
```diff
@@ -645,6 +647,53 @@ func TestHelmDependencies(t *testing.T) {
 	}
 }
 
+func TestExpandPaths(t *testing.T) {
+	home := os.Getenv("HOME")
```
Comment (dgageot) [inline pkg/skaffold/deploy/helm_test.go]: There's a `SetEnvs` function on testutil.T that you should use to cleanup automatically.
