### PR TITLE
SyncMap is a matter of artifact type, not builder

### LINKED ISSUE #3448: SyncMap is not supported by this builder - Using Kaniko and Kustomize
### Expected behavior

I'm trying out the new [FileSync](https://skaffold.dev/docs/pipeline-stages/filesync/) behavior. 

My [skaffold config](https://github.com/jlewi/code-intelligence/blob/c878abc356f9596c962e457f94ceee62bd04a329/Label_Microservice/skaffold.yaml#L14) is using Kaniko and kustomize.

My expectation is that when my python files are changed they are copied to the appropriate location
in the container.

### Actual behavior

I get the following warning

```
WARN[1154] error adding dirty artifact to changeset: inferring syncmap for image gcr.io/issue-label-bot-dev/bot-worker: SyncMap is not supported by this builder 
```

### Information

- Skaffold version:  v1.1.0
- Operating system: ...
- Contents of skaffold.yaml:

```yaml
# Reference: https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v2alpha1
kind: Config
metadata:
  name: label-microservice
build:
  artifacts:
  - image: gcr.io/issue-label-bot-dev/bot-worker
    # Set the context to the root directory. 
    # All paths in the Dockerfile should be relative to this one.
    context: ..
    # Automatically sync python files to the container. This should avoid
    # the need to rebuild and redeploy when the files change.
    sync:
        infer:        
        - '**/*.py'
    kaniko:
      dockerfile: Label_Microservice/deployment/Dockerfile.worker
      buildContext:
        gcsBucket: issue-label-bot-dev_skaffold-kaniko
      env: 
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secret/user-gcp-sa.json
      cache: {}
  cluster:
    # pullSecret can be set to a local file from which the pull secret should be created.
    pullSecretName: user-gcp-sa
    # TODO(jlewi): This should be changed for each developer; or maybe we should create a reusable one?
    namespace: jlewi-dev
    resources:
      requests:
        cpu: 8
        memory: 16Gi

deploy:
  kustomize:
    path: deployment/overlays/dev
```

### Steps to reproduce the behavior

1. Here's the link to my skaffold.yaml
    * https://github.com/jlewi/code-intelligence/blob/ebd8bde80cc331c29fbc2186d4d1901b84414cd2/Label_Microservice/skaffold.yaml 
2. I run the following command
    ```
    skaffold dev -v info --cleanup=false --trigger=polling 
    ```

### PR DESCRIPTION
**Pull request by dgageot**
Fixes #3448

### CODE REVIEW

File: pkg/skaffold/sync/sync.go [hunk 1]
```diff
@@ -138,6 +139,19 @@ func inferredSyncItem(a *latest.Artifact, e filemon.Events, builds []build.Artif
 	return &Item{Image: tag, Copy: toCopy}, nil
 }
 
+func inferredSyncMap(a *latest.Artifact, insecureRegistries map[string]bool) (map[string][]string, error) {
```
Comment (briandealwis) [inline pkg/skaffold/sync/sync.go]: This name, `InferredSyncMap()`, seems off as `docker.SyncMap()` returns the tracked add+copies derived from the `Dockerfile`, and it isn't limited to the files in the `inferred:` block.

**Comment by briandealwis** [comment]
I had been hoping to use this `SyncMap()` function for #2211 to help the IDEs to identify the application source roots in both the local workspace and remote images.  Looking through this PR, I don't think this would have worked 😭. I wish there was a way to avoid these big switches though.

**Comment by nkubala** [comment]
@briandealwis ok with the new function name?
