### PR TITLE
Fix parsing invalid Dockerfile

### LINKED ISSUE #4935: `skaffold build` panics when Dockerfile has empty `FROM` instruction
### Expected behavior
Skaffold surfaces a helpful error that tells me what is broken in my Dockerfile

### Actual behavior
Skaffold panics:

```
➜  microservices git:(master) skaffold build
Generating tags...
 - leeroy-web -> gcr.io/nkubala-demo/leeroy-web:v1.15.0-22-ga549c7a1d
 - leeroy-app -> gcr.io/nkubala-demo/leeroy-app:v1.15.0-22-ga549c7a1d-dirty
Checking cache...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x4bbea4a]

goroutine 39 [running]:
github.com/GoogleContainerTools/skaffold/pkg/skaffold/docker.fromInstruction(0xc000926850, 0xc0009e7660, 0x5a57961, 0x7, 0xc0009e7718)
        /Users/nkubala/Development/skaffold/pkg/skaffold/docker/parse.go:361 +0x2a
github.com/GoogleContainerTools/skaffold/pkg/skaffold/docker.expandOnbuildInstructions(0xc00093c940, 0x8, 0x8, 0x5d99020, 0xc000540840, 0x0, 0x0, 0xc0009e7878, 0x40b069b, 0xc0009300d0)
        /Users/nkubala/Development/skaffold/pkg/skaffold/docker/parse.go:309 +0x14b
github.com/GoogleContainerTools/skaffold/pkg/skaffold/docker.readCopyCmdsFromDockerfile(0x0, 0xc00016e0c0, 0x5c, 0xc0002a9230, 0xa, 0x0, 0x5d99020, 0xc000540840, 0x0, 0x0, ...)
        /Users/nkubala/Development/skaffold/pkg/skaffold/docker/parse.go:84 +0x345
github.com/GoogleContainerTools/skaffold/pkg/skaffold/docker.GetDependencies(0x5d98b60, 0xc00093c840, 0xc0002a9230, 0xa, 0x5a5b15a, 0xa, 0x0, 0x5d99020, 0xc000540840, 0x400f830, ...)
        /Users/nkubala/Development/skaffold/pkg/skaffold/docker/dependencies.go:61 +0x26b
github.com/GoogleContainerTools/skaffold/pkg/skaffold/build.DependenciesForArtifact(0x5d98b60, 0xc00093c840, 0xc0009265b0, 0x5d99020, 0xc000540840, 0x5448239, 0xc0009e7bf0, 0x404eb85, 0xc00014a7b0, 0x0)
        /Users/nkubala/Development/skaffold/pkg/skaffold/build/dependencies.go:42 +0x4af
github.com/GoogleContainerTools/skaffold/pkg/skaffold/runner.NewForConfig.func1(0x5d98b60, 0xc00093c840, 0xc0009265b0, 0x0, 0x1, 0xc00014a7b0, 0x0, 0x1)
        /Users/nkubala/Development/skaffold/pkg/skaffold/runner/new.go:78 +0x7b
github.com/GoogleContainerTools/skaffold/pkg/skaffold/build/cache.getHashForArtifact(0x5d98b60, 0xc00093c840, 0xc000b39ce0, 0xc0009265b0, 0x5a53fcf, 0x5, 0x0, 0x0, 0x0, 0x0)
        /Users/nkubala/Development/skaffold/pkg/skaffold/build/cache/hash.go:56 +0x20f
github.com/GoogleContainerTools/skaffold/pkg/skaffold/build/cache.NewCache.func1(0x5d98b60, 0xc00093c840, 0xc0009265b0, 0x0, 0x0, 0x0, 0x0)
        /Users/nkubala/Development/skaffold/pkg/skaffold/build/cache/cache.go:100 +0x7c
github.com/GoogleContainerTools/skaffold/pkg/skaffold/build/cache.(*cache).lookup(0xc000950ea0, 0x5d98b60, 0xc00093c840, 0xc0009265b0, 0xc0002da8c0, 0x3a, 0x0, 0x0)
        /Users/nkubala/Development/skaffold/pkg/skaffold/build/cache/lookup.go:51 +0x66
github.com/GoogleContainerTools/skaffold/pkg/skaffold/build/cache.(*cache).lookupArtifacts.func1(0xc000950ea0, 0x5d98b60, 0xc00093c840, 0xc0003a7520, 0x2, 0x2, 0x1, 0xc0009fe4b0, 0xc000798440, 0x2, ...)
        /Users/nkubala/Development/skaffold/pkg/skaffold/build/cache/lookup.go:41 +0xb5
created by github.com/GoogleContainerTools/skaffold/pkg/skaffold/build/cache.(*cache).lookupArtifacts
        /Users/nkubala/Development/skaffold/pkg/skaffold/build/cache/lookup.go:40 +0x134
```

### Information

- Skaffold version: v1.15.0
- Operating system: OS X
- Contents of skaffold.yaml: Any of our examples

### Steps to reproduce the behavior

1. pick an example with a dockerfile. remove the `FROM` line and replace it with just `FROM` (this is broken I know)
2. `skaffold build`

### PR DESCRIPTION
**Pull request by gsquared94**
Fixes #4935 
Skaffold shouldn't panic on trying to parse an invalid Dockerfile.

### CODE REVIEW

**Comment by briandealwis** [comment]
Erm, I could see using `recover()` if it was a panic in third-party code.  But we should be able to avoid this panic in our own code shouldn't we?
```
goroutine 39 [running]:
github.com/GoogleContainerTools/skaffold/pkg/skaffold/docker.fromInstruction(0xc000926850, 0xc0009e7660, 0x5a57961, 0x7, 0xc0009e7718)
        /Users/nkubala/Development/skaffold/pkg/skaffold/docker/parse.go:361 +0x2a
github.com/GoogleContainerTools/skaffold/pkg/skaffold/docker.expandOnbuildInstructions(0xc00093c940, 0x8, 0x8, 0x5d99020, 0xc000540840, 0x0, 0x0, 0xc0009e7878, 0x40b069b, 0xc0009300d0)
        /Users/nkubala/Development/skaffold/pkg/skaffold/docker/parse.go:309 +0x14b
```

**Comment by gsquared94** [comment]
> Erm, I could see using `recover()` if it was a panic in third-party code. But we should be able to avoid this panic in our own code shouldn't we?
> 
> ```
> goroutine 39 [running]:
> github.com/GoogleContainerTools/skaffold/pkg/skaffold/docker.fromInstruction(0xc000926850, 0xc0009e7660, 0x5a57961, 0x7, 0xc0009e7718)
>         /Users/nkubala/Development/skaffold/pkg/skaffold/docker/parse.go:361 +0x2a
> github.com/GoogleContainerTools/skaffold/pkg/skaffold/docker.expandOnbuildInstructions(0xc00093c940, 0x8, 0x8, 0x5d99020, 0xc000540840, 0x0, 0x0, 0xc0009e7878, 0x40b069b, 0xc0009300d0)
>         /Users/nkubala/Development/skaffold/pkg/skaffold/docker/parse.go:309 +0x14b
> ```

In `parse.go` there's a dozen references that can throw nil pointer exception. It's assuming a valid Dockerfile and I think that's a good assumption for much cleaner code. Handling the panic in this class doesn't hide any insidious issues nor can it if we only limit this file to Dockerfile parsing. WDYT? @nkubala

File: pkg/skaffold/docker/parse.go [hunk 1]
```diff
@@ -63,7 +63,13 @@ var (
 	RetrieveImage = retrieveImage
 )
 
-func readCopyCmdsFromDockerfile(onlyLastImage bool, absDockerfilePath, workspace string, buildArgs map[string]*string, cfg Config) ([]fromTo, error) {
+func readCopyCmdsFromDockerfile(onlyLastImage bool, absDockerfilePath, workspace string, buildArgs map[string]*string, cfg Config) (sl []fromTo, err error) {
+	defer func() {
```
Comment (tejal29) [inline pkg/skaffold/docker/parse.go:67]: I think the error is coming from https://github.com/GoogleContainerTools/skaffold/blob/d9cf47da6aa179cc9b47e433b386491120f49578/pkg/skaffold/docker/parse.go#L361 where skaffold dockerfile parser assumes the node next to `FORM` is not nil. 
It could be nil if from is empty. 

I feel the right fix is to check if the node.next is not nil?

**Review by tejal29 — CHANGES_REQUESTED** [review]

**Comment by tejal29** [comment]
> > Erm, I could see using `recover()` if it was a panic in third-party code. But we should be able to avoid this panic in our own code shouldn't we?
> > ```
> > goroutine 39 [running]:
> > github.com/GoogleContainerTools/skaffold/pkg/skaffold/docker.fromInstruction(0xc000926850, 0xc0009e7660, 0x5a57961, 0x7, 0xc0009e7718)
> >         /Users/nkubala/Development/skaffold/pkg/skaffold/docker/parse.go:361 +0x2a
> > github.com/GoogleContainerTools/skaffold/pkg/skaffold/docker.expandOnbuildInstructions(0xc00093c940, 0x8, 0x8, 0x5d99020, 0xc000540840, 0x0, 0x0, 0xc0009e7878, 0x40b069b, 0xc0009300d0)
> >         /Users/nkubala/Development/skaffold/pkg/skaffold/docker/parse.go:309 +0x14b
> > ```
> 
> In `parse.go` there's a dozen references that can throw nil pointer exception. It's assuming a valid Dockerfile and I think that's a good assumption for much cleaner code. Handling the panic in this class doesn't hide any insidious issues nor can it if we only limit this file to Dockerfile parsing. WDYT? @nkubala

Missed reading this comment before reviewing. 
Skaffold should first make a sanity check on `Dockerfile` and make sure its a valid dockerfile.

In kaniko, we use this functionality to parse a dockerfile first https://github.com/GoogleContainerTools/kaniko/blob/2303e47aadb8b1dd58237b9cbe4ef9dd485417d8/pkg/dockerfile/dockerfile.go#L88

**Comment by nkubala** [comment]
> Missed reading this comment before reviewing.
Skaffold should first make a sanity check on Dockerfile and make sure its a valid dockerfile.
> In kaniko, we use this functionality to parse a dockerfile first https://github.com/GoogleContainerTools/kaniko/blob/2303e47aadb8b1dd58237b9cbe4ef9dd485417d8/pkg/dockerfile/dockerfile.go#L88

we're doing the same thing in skaffold: https://github.com/GoogleContainerTools/skaffold/blob/84f8f3d312de7165d3106d2b1a70d59ed78913e1/pkg/skaffold/docker/parse.go#L73

the problem is that the parser itself doesn't validate all the nodes, so some of them could be invalid. @tejal29 this bug might also exist in kaniko :) 

normally i would say using `recover()` is no bueno, but we do actually use these nodes all over the place in the parsing code (14 times by my count), which means we need to check for them being `nil` that many times. otherwise if we try to validate beforehand, that could also be a pain, so i could see an argument for using `recover()`. the main drawback i see is if something else panics the actual error is going to get shadowed....but i'm not sure that's such a huge deal.

**Comment by gsquared94** [comment]
> the problem is that the parser itself doesn't validate all the nodes, so some of them could be invalid. @tejal29 this bug might also exist in kaniko :)

Kaniko does do [this](https://github.com/GoogleContainerTools/kaniko/blob/2303e47aadb8b1dd58237b9cbe4ef9dd485417d8/pkg/dockerfile/dockerfile.go#L92):
```go
stages, metaArgs, err := instructions.Parse(p.AST)
```
`instructions.Parse` validates the Dockerfile I think. Maybe we can do that upfront. WDYT @briandealwis @tejal29 ?

**Comment by tejal29** [comment]
> > the problem is that the parser itself doesn't validate all the nodes, so some of them could be invalid. @tejal29 this bug might also exist in kaniko :)
> 
> Kaniko does do [this](https://github.com/GoogleContainerTools/kaniko/blob/2303e47aadb8b1dd58237b9cbe4ef9dd485417d8/pkg/dockerfile/dockerfile.go#L92):
> 
> ```go
> stages, metaArgs, err := instructions.Parse(p.AST)
> ```
> 
> `instructions.Parse` validates the Dockerfile I think. Maybe we can do that upfront. WDYT @briandealwis @tejal29 ?

if it validates all the instructions, we should definitely add this fix.

**Comment by tejal29** [comment]
> the problem is that the parser itself doesn't validate all the nodes, so some of them could be invalid. @tejal29 this bug might also exist in kaniko :)



> we're doing the same thing in skaffold:
> 
> https://github.com/GoogleContainerTools/skaffold/blob/84f8f3d312de7165d3106d2b1a70d59ed78913e1/pkg/skaffold/docker/parse.go#L73
> 
> the problem is that the parser itself doesn't validate all the nodes, so some of them could be invalid. @tejal29 this bug might also exist in kaniko :)

Interesting, we have never had an issue with kaniko so far, so maybe the `instruction` parser ends up catching it for us.

**Comment by gsquared94** [comment]
used the `instructions.Parse` that returns errors on a malformed Dockerfile.

File: pkg/skaffold/docker/parse.go [hunk 2]
```diff
@@ -75,6 +76,11 @@ func readCopyCmdsFromDockerfile(onlyLastImage bool, absDockerfilePath, workspace
 		return nil, fmt.Errorf("parsing dockerfile %q: %w", absDockerfilePath, err)
 	}
 
+	// instructions.Parse will check for malformed Dockerfile
+	if _, _, err := instructions.Parse(res.AST); err != nil {
+		return nil, fmt.Errorf("parsing dockerfile %q: %w", absDockerfilePath, err)
+	}
```
Comment (MarlonGamez) [inline pkg/skaffold/docker/parse.go:82]: Should this happen before we call `parser.Parse()`? Since we basically want to validate the dockerfile with `instructions.Parse()` before then putting the data from the Dockerfile into `res`

Also should the error message be different to give a little more context? Maybe "validating dockerfile" or something similar?

Comment (gsquared94) [reply pkg/skaffold/docker/parse.go:82]: > Should this happen before we call `parser.Parse()`? Since we basically want to validate the dockerfile with `instructions.Parse()` before then putting the data from the Dockerfile into `res`

Not sure what you mean, `parser.Parse()` output is a required input to `instructions.Parse()`.

> Also should the error message be different to give a little more context? Maybe "validating dockerfile" or something similar?

`instructions.Parse` itself returns a very detailed error message so it's safe to not add any more text here.

Comment (MarlonGamez) [reply pkg/skaffold/docker/parse.go:82]: Sorry, I misread, my bad. 

Sweet, thanks for clarifying the error message :)
I think this looks good then

**Review by MarlonGamez — APPROVED** [review]
