### PR TITLE
`debug` nodejs results can result in duplicated environment variables

### LINKED ISSUE #4351: skaffold debug with nodejs duplicates ENV values
### Expected behavior
When running skaffold debug with NodeJS application deployed by kustomize, I expect the env variables from overlays will not be duplicated or overwritten

### Actual behavior
The resulting deployed pod template had duplicate ENV variables.

For `valueFrom: secretKeyRef` the additional blank ENV variable actually overwrites the previous value.

Screen Shot 2020-06-19 at 10 32 21 AM

### Information

- Skaffold version: v1.11.0
- Kustomize version {Version:3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T23:38:55+01:00 GoOs:darwin GoArch:amd64}
- OS: MacOS 10.14.6
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta5
kind: Config
build:
  artifacts:
  - image: skaffold-debug-nodejs
    context: nodejs
deploy:
  kustomize: {}
```

### Steps to reproduce the behavior
Based on the integration test data in repo: https://github.com/GoogleContainerTools/skaffold/tree/master/integration/testdata/debug

1. a clonable repository: https://github.com/legopin/skaffold-debug-nodejs-env-reproduction.git
2. `skaffold debug`
3. kubectl get deployment nodejs -o yaml

### PR DESCRIPTION
**Pull request by briandealwis**
Fixes #4351 

The NodeJS debug transformer was unnecessarily copying all of the image's environment variables into the transformed k8s container definition.  It only needs to add new or changed environment
variables to the transformed container.

I changed the order of the environment variables so as to be consistent with the tests, and avoid the need to sort the variable list.

### CODE REVIEW

File: pkg/skaffold/debug/transform.go [hunk 1]
```diff
@@ -311,7 +311,8 @@ func isPortAvailable(podSpec *v1.PodSpec, port int32) bool {
 // Returns a debugging configuration description with associated language runtime support
 // container image, or an error if the rewrite was unsuccessful.
 func transformContainer(container *v1.Container, config imageConfiguration, portAlloc portAllocator) (ContainerDebugConfiguration, string, error) {
-	// update image configuration values with those set in the k8s manifest
+	// Update the image configuration's environment with those set in the k8s manifest.
+	// (Environment variables in the k8s container's `env` add to the image configuration's `env` settings rather than replace.)
```
Comment (tejal29) [inline pkg/skaffold/debug/transform.go:315]: I am not sure i understand this comment. 
The only two env variables replaced or added  are `NODE_OPTIONS` and `PATH` right?

Comment (briandealwis) [reply pkg/skaffold/debug/transform.go:315]: This was a general comment: the k8s `command`, `arguments`, and `workingDir` attributes replace the image's `entrypoint`, `cmd`, and `workdir` values (respectively).  I clearly mistakenly thought the environment variables replaced the image's values too (the [API docs](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#container-v1-core) are not clear).
