### PR TITLE
Substitute build args from config into parsed Dockerfile before processing deps

### LINKED ISSUE #777: Dockerfile: COPY/ADD with build arg variables are not expanded
Using build arg variables in COPY/ADD instructions are not expanding the variables. Resulting in the following error:
```
creating docker context: getting relative tar paths: file pattern [.txt] must match at least one file
```
It however seems to be working with environment variables

### Expected behavior
Build arg variables are expanded the same way as environment variables.

### Information

- Skaffold version: 0.9.0
- Operating system: Arch Linux
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: foo/bar
    workspace: .
    docker:
      buildArgs:
        FOO: "bar"
deploy:
  kubectl:
    manifests:
      - k8s-*
```

### Steps to reproduce the behavior

1. Create `Dockerfile`:
```Dockerfile
FROM scratch
ARG FOO
COPY $FOO.txt /tmp/foo.txt
```
2. Create `bar.txt`:
```sh
touch bar.txt
```
3. Create `skaffold.yaml` accordingly above
4. Running `skaffold dev` will produce the following error:
```
> skaffold dev
Starting build...
Found [minikube] context, using local docker daemon.
Building [foo/bar]...
Sending build context to Docker daemon 

Watching for changes...
ERRO[0000] dev: dev step: first run: exiting dev mode because the first build failed: building [foo/bar]: running build: docker build: error during connect: Post https://192.168.99.100:2376/v1.23/build?buildargs=%7B%22FOO%22%3A%22bar%22%7D&cachefrom=null&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=null&memory=0&memswap=0&networkmode=&rm=0&shmsize=0&t=10c929cec34592154c09433eb3662e67&target=&ulimits=null: creating docker context: getting relative tar paths: file pattern [.txt] must match at least one file 
Cleaning up...
error: error when stopping "STDIN": no kind "GetOptions" is registered for version "apps/v1"
WARN[0000] cleanup: deleting manifests: exit status 1   
```

### PR DESCRIPTION
**Pull request by nkubala**
This PR passes the buildArgs from Docker artifacts in skaffold.yaml to the Docker dependency parser, which substitutes the args into the parsed Dockerfile AST before processing any other commands. This allows args to be substituted correctly when provided as a build arg and implicitly referenced in a Dockerfile, e.g.

skaffold.yaml
```yaml
build:
  artifacts:
  - imageName: foo/bar
    workspace: .
    docker:
      buildArgs:
        FOO: "bar"
```
Dockerfile
```
...
ARG FOO
COPY $FOO.txt /tmp/bar.txt
...
```
will now copy `bar.txt` to `/tmp/bar.txt`.

Fixes #777

### CODE REVIEW

File: cmd/skaffold/app/cmd/docker/deps.go [hunk 1]
```diff
@@ -46,8 +50,12 @@ type DepsOutput struct {
 	Deps []string
 }
 
-func runDeps(out io.Writer, filename, context string) error {
-	deps, err := docker.GetDependencies(context, filename)
+func runDeps(out io.Writer, filename, dockerfile, context string) error {
+	config, err := cmdutil.ParseConfig(filename)
+	if err != nil {
+		return err
```
Comment (dgageot) [inline cmd/skaffold/app/cmd/docker/deps.go]: nit: wrap the error?

File: cmd/skaffold/app/cmd/docker/context.go [hunk 2]
```diff
@@ -38,13 +39,18 @@ func NewCmdContext(out io.Writer) *cobra.Command {
...
+	cmd.Flags().StringVarP(&dockerfile, "dockerfile", "d", "Dockerfile", "Dockerfile path")
 	cmd.Flags().StringVarP(&context, "context", "c", ".", "Dockerfile context path")
 	cmd.Flags().StringVarP(&output, "output", "o", "context.tar.gz", "Output filename.")
 	return cmd
 }
 
 func runContext(out io.Writer, filename, context string) error {
+	config, err := cmdutil.ParseConfig(filename)
+	if err != nil {
+		return err
```
Comment (dgageot) [inline cmd/skaffold/app/cmd/docker/context.go]: nit: wrap the error?

File: cmd/skaffold/app/cmd/docker/deps.go [hunk 3]
```diff
@@ -58,3 +66,13 @@ func runDeps(out io.Writer, filename, context string) error {
 	}
 	return nil
 }
+
+func getBuildArgsForDockerfile(config *config.SkaffoldConfig, dockerfile string) map[string]*string {
+	for _, artifact := range config.Build.Artifacts {
+		if artifact.DockerArtifact != nil && artifact.DockerArtifact.DockerfilePath == dockerfile {
```
Comment (dgageot) [inline cmd/skaffold/app/cmd/docker/deps.go]: Should we compare normalized paths?

File: pkg/skaffold/docker/parse.go [hunk 4]
```diff
@@ -29,23 +29,17 @@ import (
...
-	copy = "copy"
-	env  = "env"
-	from = "from"
-)
-
 // RetrieveImage is overriden for unit testing
 var RetrieveImage = retrieveImage
 
-func readDockerfile(workspace, absDockerfilePath string) ([]string, error) {
+func readDockerfile(buildArgs map[string]*string, workspace, absDockerfilePath string) ([]string, error) {
```
Comment (dgageot) [inline pkg/skaffold/docker/parse.go]: nit: would have added those arguments last

**Comment by bobcatfish** [comment]
Hey @nkubala what do you think about adding a new test case or expanding the existing unit tests to cover this case that was failing? (or maybe it's already covered and i'm missing it?)

**Comment by nkubala** [comment]
@bobcatfish added a test

**Comment by joseaio** [comment]
Any news on this feature?
Any workaround?
   example: use ARG as value for ENV variable > use $ENV var

  ARG MY_ARG=default_value
  ENV MY_ENV=$MY_ARG
  # use $MYENV variable replacements
  ADD ${MYENV}.txt /path/to/file.txt

**Comment by dgageot** [comment]
@joseaio I believe this was fixed in https://github.com/GoogleContainerTools/skaffold/pull/3439
