### PR TITLE
Set statuscheck to false.

### LINKED ISSUE #2495: Skaffold dev fails when user cannot list deployments at cluster scope
The deployment status check from Skaffold tries to list all deployments at cluster scope, when running Skaffold without the `--namespace` flag. For example:

```
cd examples/nodejs
kubectl auth can-i list deploy --all-namespaces  # -> no
skaffold dev
```

Fails with 
```
FATA[0001] exiting dev mode because first deploy failed: could not fetch deployments: could not fetch deployments: deployments.apps is forbidden: User "default-user" cannot list resource "deployments" in API group "apps" at the cluster scope
```
On the other hand:
```
kubectl auth can-i list deploy -n default  # -> yes
skaffold dev -n default
```
works as expected.

---

The reason for this is that `pkg/skaffold/deploy/status_check.go:80` does 
```go
client.AppsV1().Deployments(ns).List(metav1.ListOptions{
		LabelSelector: l.K8sManagedByLabelKeyValueString(),
	})
```
with `ns==""` (due to not specifying a namespace), and that means _all namespaces_.

### PR DESCRIPTION
**Pull request by tejal29**
Turn status-check false by default as a workaround for #2496 and #2495.

### CODE REVIEW

File: cmd/skaffold/app/cmd/flags.go [hunk 1]
```diff
@@ -66,7 +66,7 @@ var FlagRegistry = []Flag{
 		Shorthand:     "n",
 		Usage:         "Run deployments in the specified namespace",
 		Value:         &opts.Namespace,
-		DefValue:      "",
+		DefValue:      "default",
```
Comment (balopat) [inline cmd/skaffold/app/cmd/flags.go]: let's separate this out to a different PR with tests and everything, I'm not sure about that this is what we want to do (we might but I need a bit more time to think it through).

Comment (balopat) [reply cmd/skaffold/app/cmd/flags.go]: more thought around this: there is a difference between leaving it empty and letting the resources determine their namespace vs enforcing `default`.
