### PR TITLE
Fix redundant Jib image flags generated by init

### LINKED ISSUE #3190: `skaffold.yaml` produced by `skaffold init --XXenableJibInit` could be simpler
When I run `skaffold init --XXenableJibInit --force` in `examples/jib`, I get this `skaffold.yaml`.

```
...
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold-jib
    jib:
      args:
      - -Dimage=gcr.io/k8s-skaffold/skaffold-jib
      type: maven
```

I expected to get this kind of output:

```
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold-jib
    jib: {}
```

any reason why we duplicate the image name?

### PR DESCRIPTION
**Pull request by TadCordle**
Fixes #3190.

**Description**

Since the correct `-Dimage` flag is automatically generated during Jib builds, it's unnecessary (or even error prone) to generate the flags during `skaffold init`. 

**Release Notes**

Fix unnecessary Jib image flags generated during `skaffold init`.

### CODE REVIEW

File: pkg/skaffold/jib/jib_init_test.go [hunk 1]
```diff
@@ -187,23 +187,19 @@ func TestCreateArtifact(t *testing.T) {
...
 			manifestImage: "different-image",
 			expectedArtifact: latest.Artifact{
-				ImageName: "different-image",
-				Workspace: filepath.Join("path", "to"),
-				ArtifactType: latest.ArtifactType{
-					JibArtifact: &latest.JibArtifact{Flags: []string{"-Dimage=different-image"}, Type: string(JibGradle)},
-				},
+				ImageName:    "different-image",
+				Workspace:    filepath.Join("path", "to"),
+				ArtifactType: latest.ArtifactType{JibArtifact: &latest.JibArtifact{Type: string(JibGradle)}},
```
Comment (chanseokoh) [inline pkg/skaffold/jib/jib_init_test.go]: About https://github.com/GoogleContainerTools/skaffold/issues/3190#issue-518528937, is it easy to get rid of `type: gradle` or it is safe to put them?

Comment (TadCordle) [reply pkg/skaffold/jib/jib_init_test.go]: @briandealwis would know better than I.

Comment (briandealwis) [reply pkg/skaffold/jib/jib_init_test.go]: It should be safe to remove.

File: pkg/skaffold/jib/jib_init.go [hunk 2]
```diff
@@ -73,14 +73,12 @@ func (j Jib) CreateArtifact(manifestImage string) *latest.Artifact {
...
 			jibMaven.Project = j.Project
 		}
-		jibMaven.Flags = []string{"-Dimage=" + manifestImage}
 		a.ArtifactType = latest.ArtifactType{JibArtifact: jibMaven}
 	} else if j.BuilderName == PluginName(JibGradle) {
 		jibGradle := &latest.JibArtifact{Type: string(JibGradle)}
 		if j.Project != "" {
 			jibGradle.Project = j.Project
 		}
-		jibGradle.Flags = []string{"-Dimage=" + manifestImage}
```
Comment (briandealwis) [inline pkg/skaffold/jib/jib_init.go]: This should have been `--image` too, I think?
