### PR TITLE
Simpler runner code

### LINKED ISSUE #559: should be able to run `skaffold build` without creating a Kubernetes client
### Expected behavior

Build runs.

### Actual behavior

Build fails.

```
Error: getting skaffold config: getting k8s client: Error creating kubeConfig: invalid configuration: no configuration has been provided
```

### Information

- Skaffold version: 3246ef8e2028611460aaf911bd38781d9f19764b
- Operating system: macOS
- Contents of `skaffold.yaml`:

```yaml
apiVersion: skaffold/v1alpha2
kind: Config

build:

  artifacts:
  - imageName: podinfo
    docker:
      dockerfilePath: ./Dockerfile.ci

deploy:

  kubectl: { manifests: [ deploy/skaffold/* ] }

profiles:

  - name: production

    build:

      local: { skipPush: false }
      artifacts:
      - imageName: quay.io/stefanprodan/podinfo
        docker:
          dockerfilePath: ./Dockerfile.ci

    deploy: {}
```

### Steps to reproduce the behavior

1. `mv ~/.kube ~/.kube-`
2. `skaffold build`

### PR DESCRIPTION
**Pull request by dgageot**
This is a first step in my master plan to simplify runner's code

Also fixes #559 and #516

### CODE REVIEW

**Comment by dlorenc** [comment]
> This is a first step in my master plan to simplify runner's code

I like master plans! Could you share a little more info on the goal in here or an issue?

**Comment by dgageot** [comment]
@dlorenc So, next time I need to get your attention, I'll use the words "master plan" in the description. 

I think runner.go has become to hard to read and change. I'd like to simplify it but each time I try, so this is me starting with baby steps. In parallel of making the code easier to read, I'd like to better handle fatal failures. Builds are ok to fail (maybe not the first time) but the rest shouldn't fail with only a warning.

File: pkg/skaffold/watch/watch.go [hunk 1]
```diff
@@ -103,7 +103,10 @@ func (f *fsWatcher) Start(ctx context.Context, onChange func([]string)) error {
 		case <-timer.C:
 			changes := sortedPaths(changedPaths)
 			changedPaths = map[string]bool{}
-			onChange(changes)
+
+			if err := onChange(changes); err != nil {
+				return err
```
Comment (r2d4) [inline pkg/skaffold/watch/watch.go]: nit: wrap error

File: pkg/skaffold/deploy/deploy.go [hunk 2]
```diff
@@ -24,16 +24,12 @@ import (
...
-// from a Deployer.Run()
-type Result struct{}
-
 // Deployer is the Deploy API of skaffold and responsible for deploying
 // the build results to a Kubernetes cluster
 type Deployer interface {
 	// Deploy should ensure that the build results are deployed to the Kubernetes
 	// cluster.
-	Deploy(context.Context, io.Writer, *build.BuildResult) (*Result, error)
+	Deploy(context.Context, io.Writer, []build.Build) error
```
Comment (r2d4) [inline pkg/skaffold/deploy/deploy.go]: :+1:

File: pkg/skaffold/build/deps.go [hunk 3]
```diff
@@ -29,7 +29,16 @@ import (
 	"github.com/sirupsen/logrus"
 )
 
-type DependencyMap struct {
+// DependencyMapFactory can build DependencyMaps from a list of artifacts.
+type DependencyMapFactory func(artifacts []*v1alpha2.Artifact) (DependencyMap, error)
+
+// DependencyMap is a bijection between artifacts and the files they depend on.
+type DependencyMap interface {
```
[the remark this answers is not in the document]
Comment (r2d4) [reply pkg/skaffold/build/deps.go]: Its a little odd that we have the DependencyMap and DependencyResolver interfaces. The latter is the one with the bazel, and dockerfile implementations.

File: pkg/skaffold/runner/runner.go [hunk 4]
```diff
@@ -68,121 +64,129 @@ func NewForConfig(opts *config.SkaffoldOptions, cfg *config.SkaffoldConfig, out
...
-	}
-	if t.GitTagger != nil {
+
+	case t.GitTagger != nil:
 		return &tag.GitCommit{}, nil
-	}
 
-	return nil, fmt.Errorf("Unknown tagger for strategy %s", t)
+	default:
+		return nil, fmt.Errorf("Unknown tagger for strategy %s", t)
```
Comment (r2d4) [inline pkg/skaffold/runner/runner.go]: nit: `Unknown tagger for config %+v` since its a struct now

File: pkg/skaffold/runner/runner.go [hunk 5]
```diff
@@ -68,121 +64,129 @@ func NewForConfig(opts *config.SkaffoldOptions, cfg *config.SkaffoldConfig, out
...
 	}
 
 	return nil
 }
 
 // Run runs the skaffold build and deploy pipeline.
 func (r *SkaffoldRunner) Run(ctx context.Context) error {
-	_, _, err := r.buildAndDeploy(ctx, r.config.Build.Artifacts, nil)
-	return err
+	bRes, err := r.Builder.Build(ctx, r.out, r.Tagger, r.config.Build.Artifacts)
```
Comment (r2d4) [inline pkg/skaffold/runner/runner.go]: See other comment on ` func (r *SkaffoldRunner) Build(ctx context.Context) error {`

File: pkg/skaffold/runner/runner.go [hunk 6]
```diff
@@ -68,121 +64,129 @@ func NewForConfig(opts *config.SkaffoldOptions, cfg *config.SkaffoldConfig, out
...
-	}
 
-	return nil, fmt.Errorf("Unknown tagger for strategy %s", t)
+	default:
+		return nil, fmt.Errorf("Unknown tagger for strategy %s", t)
+	}
 }
 
 // Build builds the artifacts.
 func (r *SkaffoldRunner) Build(ctx context.Context) error {
```
Comment (r2d4) [inline pkg/skaffold/runner/runner.go]: Since we have this function, I think all r.Builder.Build should be translated to r.Build

**Comment by r2d4** [comment]
I don't think this fully fixes https://github.com/GoogleContainerTools/skaffold/issues/559, since we get the kubeclient there as part of NewLocalBuilder to figure out whether or not the cluster is minikube or not.

File: pkg/skaffold/runner/runner.go (hunk 4 above)
Comment (dgageot) [reply pkg/skaffold/runner/runner.go]: Will do.

File: pkg/skaffold/watch/watch.go (hunk 1 above)
Comment (dgageot) [reply pkg/skaffold/watch/watch.go]: Will do.

File: pkg/skaffold/build/deps.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (dgageot) [reply pkg/skaffold/build/deps.go]: Will remove the interface. It was useful at some point for unit test.

[the remark this answers is not in the document]
Comment (dgageot) [reply pkg/skaffold/build/deps.go]: And in a future PR, I'll try to remove the need for DependencyResolver which is only required for tests.

File: pkg/skaffold/deploy/timings.go [hunk 7]
```diff
@@ -0,0 +1,65 @@
...
+	Deployer
+}
+
+func (w withTimings) Deploy(ctx context.Context, out io.Writer, builds []build.Build) error {
+	start := time.Now()
+	fmt.Fprintln(out, "Starting deploy...")
+
+	err := w.Deployer.Deploy(ctx, out, builds)
+	if err != nil {
+		return err
```
[the remark this answers is not in the document]
Comment (dgageot) [reply pkg/skaffold/deploy/timings.go]: I don't really like wrapping the error here since all we do is delegate to a function call without changing the inputs or outputs. It just adds noise to the errors I think.

File: pkg/skaffold/runner/runner.go [hunk 8]
```diff
@@ -68,121 +64,129 @@ func NewForConfig(opts *config.SkaffoldOptions, cfg *config.SkaffoldConfig, out
...
 	return nil
 }
 
 // Run runs the skaffold build and deploy pipeline.
 func (r *SkaffoldRunner) Run(ctx context.Context) error {
-	_, _, err := r.buildAndDeploy(ctx, r.config.Build.Artifacts, nil)
-	return err
+	bRes, err := r.Builder.Build(ctx, r.out, r.Tagger, r.config.Build.Artifacts)
+	if err != nil {
+		return err
```
[the remark this answers is not in the document]
Comment (dgageot) [reply pkg/skaffold/runner/runner.go]: done

File: pkg/skaffold/runner/runner.go (hunk 6 above)
Comment (dgageot) [reply pkg/skaffold/runner/runner.go]: I don't understand how we can do that. r.Build and r.Builder.Build are two different functions with same name but different arguments. I must be missing something.

File: pkg/skaffold/build/timings.go [hunk 9]
```diff
@@ -0,0 +1,52 @@
...
+	return withTimings{
+		Builder: b,
+	}
+}
+
+type withTimings struct {
+	Builder
+}
+
+func (w withTimings) Build(ctx context.Context, out io.Writer, tagger tag.Tagger, artifacts []*v1alpha2.Artifact) ([]Build, error) {
```
[the remark this answers is not in the document]
Comment (dgageot) [reply pkg/skaffold/build/timings.go]: Done.

**Comment by dgageot** [comment]
Hi @r2d4, I tried to take into account all your feedback

File: pkg/skaffold/runner/runner.go (hunk 6 above)
Comment (dgageot) [reply pkg/skaffold/runner/runner.go]: I'm still not sure I know how to improve that. Can this be done in another PR?
