### PR TITLE
Make sure we mute/unmute logs at the correct times

### LINKED ISSUE #2530: Logs should stay muted when a build fails in the dev loop
Run `skaffold dev`. Wait for the app to be deployed. Break a Dockerfile. The user should see the error and the logs should be muted until the build is repaired.

Logs are currently unmuted.

### PR DESCRIPTION
**Pull request by nkubala**
This change makes sure that in the dev loop, we:
* only mute logs whenever we're going to perform an action, and
* only unmute logs when we've successfully performed an action

Fixes #2530

### CODE REVIEW

File: pkg/skaffold/runner/dev.go [hunk 1]
```diff
@@ -33,14 +33,15 @@ import (
...
-	r.logger.Mute()
+	actionPerformed := false
 
 	// acquire the intents
 	buildIntent, syncIntent, deployIntent := r.intents.GetIntents()
 
 	if (r.changeSet.needsRedeploy && deployIntent) ||
 		(len(r.changeSet.needsRebuild) > 0 && buildIntent) ||
 		(len(r.changeSet.needsResync) > 0 && syncIntent) {
+		r.logger.Mute()
```
Comment (balopat) [inline pkg/skaffold/runner/dev.go]: why can't we just put a `defer r.logger.Unmute()` here? It seems equivalent.

Comment (nkubala) [reply pkg/skaffold/runner/dev.go]: because we don't want to unmute the logs if the build fails. that wouldn't fix the issue

Comment (balopat) [reply pkg/skaffold/runner/dev.go]: ah right, the return statements in the middle threw me off.
