### PR TITLE
Set `redeploy` intent only when there are rebuilt artifacts

### LINKED ISSUE #5551: Inconsistencies in Skaffold Control API
### Steps to reproduce the behavior

1. the `getting-started` sample
2. run `skaffold dev --rpc-http-port 65168 --auto-build=false --auto-deploy=false --auto-sync=false`
3. make some change in a file
4. run `curl -X PUT http://localhost:65168/v1/deploy/auto_execute -d '{"enabled": true}'`
5.
    a. Expected:
      Nothing happens since there is no new image available to deploy
    b. Actual:
    Deploy gets triggered and redeploys the same old image without the changes.
6.  run `curl -X PUT http://localhost:65168/v1/build/auto_execute -d '{"enabled": true}'`
7.
    a. Expected:
    The image is rebuilt and redeployed (since redeploy trigger was already set previously)
    b. Actual:
    The image is rebuilt but not redeployed (since a no-op redeploy already happened in the previous step).
    
PS: This issue doesn't impact the IDE outright because it triggers `auto-build` and `auto-deploy` in simultaneous requests so the rebuild and redeploy happen together in the same devloop (skipping the no-op redeploy dev loop above)

### PR DESCRIPTION
**Pull request by gsquared94**
Fixes #5551 #4886 

In an ongoing devloop the `redeploy` intent can be set in one of two ways: (1)there are rebuilt artifacts, or (2)the deploy dependency files have changed. In the current implementation, the redeploy intent is set as soon as there's a new request for an artifact rebuild. This doesn't work well in conjunction with the control APIs since the auto-rebuild can be off in which case the redeploy intent is processed immediately on the old image builds. 

This PR queues a redeploy request of type (1) only _after_ the artifacts have been rebuilt. This fixes the issue of the no-op deploy described in #5551 and also ensures that any rebuilt images are deployed.

### CODE REVIEW

File: pkg/skaffold/runner/dev.go [hunk 1]
```diff
@@ -109,6 +109,9 @@ func (r *SkaffoldRunner) doDev(ctx context.Context, out io.Writer, logger *kuber
 			event.DevLoopFailedInPhase(r.devIteration, sErrors.Build, err)
 			return nil
 		}
+		r.changeSet.needsRedeploy = true
+		needsDeploy = deployIntent && r.changeSet.needsRedeploy
```
Comment (briandealwis) [inline pkg/skaffold/runner/dev.go:113]: Since we just set `r.changeSet.needsRedeploy = true`, can this be simplified to:
```suggestion
		needsDeploy = deployIntent
```

**Review by briandealwis — COMMENTED** [review]
I'm going to defer to @nkubala.

My question is: don't we need to reset the intents at line 62?
```
	if !needsSync && !needsBuild && !needsDeploy {
		return nil
	}
```

**Comment by briandealwis** [comment]
Is it possible to write some tests around this?

**Comment by gsquared94** [comment]
> Is it possible to write some tests around this?



> I'm going to defer to @nkubala.
> 
> My question is: don't we need to reset the intents at line 62?
> 
> ```
> 	if !needsSync && !needsBuild && !needsDeploy {
> 		return nil
> 	}
> ```

That depends on if we want to expire triggers if they aren't immediately actionable or queue them. I think @nkubala intended to have them queue up (like a single deploy request followed some time later by a single build request would run build and deploy both once). I kind of like this behavior; but agree that since it's only maintained as internal state it can cause some confusion. 

Maybe a better flow would be if `buildIntent == true` but `r.changeSet.needsRebuild == false` we expire it immediately and show output `Checking build status: already up-to-date` and similarly for `sync` and `deploy`.

However, I don't want to change that behavior in this PR. :)

**Comment by nkubala** [comment]
> I think @nkubala intended to have them queue up (like a single deploy request followed some time later by a single build request would run build and deploy both once)

this is what i intended at the time, but now i'm not so sure it's what we want. it might be a more predictable UX to just reject the intents sent by a user if skaffold isn't ready to take the corresponding action yet (e.g. receives `build` intent from user, but `r.changeSet.needsRebuild == false`

> Maybe a better flow would be if buildIntent == true but r.changeSet.needsRebuild == false we expire it immediately and show output Checking build status: already up-to-date and similarly for sync and deploy.

if we decide to keep the current behavior, this is definitely something we should do. whatever route we take let's try and eliminate confusion.

cc https://github.com/GoogleContainerTools/skaffold/issues/4886, which i think may be fixed by this issue.

**Review by nkubala — APPROVED** [review]

**Comment by briandealwis** [comment]
I think queuing up changes would make sense if we had a general `/update` API, but this API makes it seem that there is explicit control over build, deploy, and sync.  I found it disconcerting to see deploys happen when I asked for just `"build":true`.

I could see a user wanting to use `"build": true` to verify no build-errors, followed by a `"deploy": true` when they're ready to apply.
