### PR TITLE
Retrieve the proper kind cluster name

### LINKED ISSUE #4198: Kind image loading is broken in TestDev_WithKubecontextOverride
Kind loading is broken in `TestDev_WithKubecontextOverride` - it cannot be called on its own. 

```
--- FAIL: TestDev_WithKubecontextOverride (0.91s)
/integration/TestDev_WithKubecontextOverride/skaffold_run_with_kubecontext_override
time="2020-05-15T18:02:39-07:00" level=info msg="Namespace: skaffoldbkrlk"
time="2020-05-15T18:02:39-07:00" level=info msg="[skaffold run --default-repo gcr.io/k8s-skaffold --kube-context kind-modified-context]"
    TestDev_WithKubecontextOverride/skaffold_run_with_kubecontext_override: helper.go:194: skaffold run: exit status 1, Generating tags...
         - skaffold-example -> gcr.io/k8s-skaffold/skaffold-example:v0.36.0-2130-g78b1b9fc4
        Checking cache...
         - skaffold-example: Found. Tagging
        Tags used in deployment:
         - skaffold-example -> gcr.io/k8s-skaffold/skaffold-example:fe2e30a7f7395ff45b7ece353b2ebdf137541dc7a64f3547e998cfc5fb8cf6ed
        Loading images into kind cluster nodes...
         - gcr.io/k8s-skaffold/skaffold-example:fe2e30a7f7395ff45b7ece353b2ebdf137541dc7a64f3547e998cfc5fb8cf6ed -> Failed
    TestDev_WithKubecontextOverride/skaffold_run_with_kubecontext_override: panic.go:617: loading images into kind nodes: unable to load image with kind "gcr.io/k8s-skaffold/skaffold-example:fe2e30a7f7395ff45b7ece353b2ebdf137541dc7a64f3547e998cfc5fb8cf6ed": running [kind load docker-image --name modified-context gcr.io/k8s-skaffold/skaffold-example:fe2e30a7f7395ff45b7ece353b2ebdf137541dc7a64f3547e998cfc5fb8cf6ed]
         - stdout: ""
         - stderr: "Error: unknown cluster \"modified-context\"\n"
         - cause: exit status 1, 
    --- FAIL: TestDev_WithKubecontextOverride/skaffold_run_with_kubecontext_override (0.91s)
```

I'm thoroughly puzzled still why it can pass with other tests around / before it. 
My best bet is that somehow artifact caching makes it skip the `kind load` - but I couldn't reliably reproduce it yet locally.

### PR DESCRIPTION
**Pull request by dgageot**
Fixes #4198

Signed-off-by: David Gageot <david@gageot.net>

### CODE REVIEW

File: integration/dev_test.go [hunk 1]
```diff
@@ -295,7 +294,7 @@ func createModifiedKubeconfig(namespace string) ([]byte, string, error) {
 	}
 
 	contextName := "modified-context"
-	if isKind, _ := config.IsKindCluster(kubeConfig.CurrentContext); isKind {
+	if config.IsKindCluster(kubeConfig.CurrentContext) {
```
Comment (balopat) [inline integration/dev_test.go:297]: I think this logic is just broken. 
Our kind cluster will be `modified-context` that leads to the error that can't load the image to `modified-context` cluster as it does not exist. Maybe we should rename the kind cluster to `modified-context`?

**Comment by balopat** [comment]
wow not sure what happened with the integration tests, suddenly all of them wanted to push after build and failed with auth errors! I bounced "partition 2" to see if it goes away or not

File: integration/dev_test.go (hunk 1 above)
Comment (dgageot) [reply integration/dev_test.go:297]: I don't think that's what's happening:
+ Before we duplicate the kube context, we have a context that's usually `kind-kind` that references a cluster with the same name. To load images into kind, we have to get rid of the `kind-` prefix or suffix.
+ After we duplicate, the context is `kind-modified-context` but the cluster is still `kind-kind`. But the previous code never retrieved the name of the cluster. It assumed it was the same as the context. Which is the case by default but can be changed by the user.
+ What this code does is retrieve the actual cluster name, removed its prefix/suffix in order to get the *internal* name of the cluster

Comment (balopat) [reply integration/dev_test.go:297]: L222 did exactly that prefix removal: `return true, strings.TrimPrefix(kubeContext, "kind-")` I thought you just refactored things around but did not change the logic - am I missing something?

Comment (balopat) [reply integration/dev_test.go:297]: > After we duplicate, the context is `kind-modified-context` but the cluster is still `kind-kind`. But the previous code never retrieved the name of the cluster. It assumed it was the same as the context. Which is the case by default but can be changed by the user.

This code does not retrieve the name of the cluster either (in the test). 
The production code still uses the same prefix trimming logic - thus will still "think" the cluster is named `modified-context` instead of `kind` - unless

File: pkg/skaffold/config/util_test.go [hunk 2]
```diff
@@ -291,22 +291,40 @@ func TestIsDefaultLocal(t *testing.T) {
...
+func TestKindClusterName(t *testing.T) {
+	tests := []struct {
+		kubeCluster  string
+		expectedName string
+	}{
+		{kubeCluster: "kind", expectedName: "kind"},
+		{kubeCluster: "kind-kind", expectedName: "kind"},
+		{kubeCluster: "kind-other", expectedName: "other"},
+		{kubeCluster: "kind@kind", expectedName: "kind"},
+		{kubeCluster: "other@kind", expectedName: "other"},
```
Comment (balopat) [inline pkg/skaffold/config/util_test.go:321]: we should add a test for the `default` case - where we return the context as the cluster name

File: pkg/skaffold/config/util.go [hunk 3]
```diff
@@ -199,33 +199,52 @@ func isDefaultLocal(kubeContext string) bool {
...
+		return true
 
 	default:
-		return false, ""
+		return false
 	}
 }
 
+// KindClusterName returns the internal kind name of a kubernetes cluster.
+func KindClusterName(clusterName string) string {
```
Comment (balopat) [inline pkg/skaffold/config/util.go:228]:
```suggestion
func KindClusterName(context string) string {
```
wdyt?

File: pkg/skaffold/config/util_test.go (hunk 2 above)
Comment (dgageot) [reply pkg/skaffold/config/util_test.go:321]: The first line does that: `kind` -> `kind`. This is for example what will happen with kind < 0.6. The cluster name in the kubeconfig is by default `kind`

File: pkg/skaffold/config/util.go (hunk 3 above)
Comment (dgageot) [reply pkg/skaffold/config/util.go:228]: No. The name of the cluster is not the name of the context. That's the whole point of this fix.

File: integration/dev_test.go (hunk 1 above)
Comment (dgageot) [reply integration/dev_test.go:297]: You are missing the fact that the cluster name is not the context name.  Also, the kind internal cluster name is not the cluster name.

Here's an example of what can happen in the test:

Before we create a new context:
 + context name: `kind-kind`
 + cluster name: `kind-kind`
 + kind name: `kind`

After we create a new context:
 + context name: `kind-modified-context`
 + cluster name: `kind-kind` (This one doesn't change, that's where the bug comes from)
 + kind name: `kind`

This issue shows the case where users rename their context but keep the cluster name as is. We have to remove the prefix from the cluster name, not the context name.

File: pkg/skaffold/runner/deploy.go [hunk 4]
```diff
@@ -55,7 +56,19 @@ See https://skaffold.dev/docs/pipeline-stages/taggers/#how-tagging-works`)
...
+		if err != nil {
+			return fmt.Errorf("unable to get kubernetes config: %w", err)
+		}
+
+		currentContext, present := currentCfg.Contexts[r.runCtx.KubeContext]
+		if !present {
+			return fmt.Errorf("unable to get current kubernetes context: %w", err)
+		}
+
+		kindCluster := config.KindClusterName(currentContext.Cluster)
```
Comment (balopat) [inline pkg/skaffold/runner/deploy.go:70]: ahhhhhh got it!!!! :D
