### PR TITLE
Pass DOCKER* env variables for jib to connect to minikube

### LINKED ISSUE #1261: Jib example doesn't build
### Actual behavior

The jib example doesn't build. The basic example (examples/getting-started) works well. My console logs :

```
➜  jib git:(master) skaffold dev --default-repo localhost:5000
Starting build...
Found [minikube] context, using local docker daemon.
Building [localhost:5000/gcr_io_k8s-skaffold_skaffold-jib]...
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------------< org.skaffold:hello-spring-boot >-------------------
[INFO] Building hello-spring-boot 0.1.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ hello-spring-boot ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/vmaubert/GIT/skaffold/examples/jib/src/main/resources
[INFO] skip non existing resourceDirectory /home/vmaubert/GIT/skaffold/examples/jib/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ hello-spring-boot ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ hello-spring-boot ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/vmaubert/GIT/skaffold/examples/jib/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:testCompile (default-testCompile) @ hello-spring-boot ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.21.0:test (default-test) @ hello-spring-boot ---
[INFO] No tests to run.
[INFO] 
[INFO] --- jib-maven-plugin:0.9.11:dockerBuild (default-cli) @ hello-spring-boot ---
[WARNING] Base image 'gcr.io/distroless/java' does not use a specific image digest - build may not be reproducible
[INFO] 
[INFO] Containerizing application to Docker daemon as jib__087e74d83f207d1cd326fc12cd7e0110bb02da61...
[INFO] 
[INFO] Getting base image gcr.io/distroless/java...
[INFO] Building dependencies layer...
[INFO] Building classes layer...
[INFO] Finalizing...
[INFO] Loading to Docker daemon...
[INFO] 
[INFO] Container entrypoint set to [java, -Djava.security.egd=file:/dev/./urandom, -XX:+UnlockExperimentalVMOptions, -XX:+UseCGroupMemoryLimitForHeap, -cp, /app/resources:/app/classes:/app/libs/*, hello.Application]
[INFO] 
[INFO] Built image to Docker daemon as jib__087e74d83f207d1cd326fc12cd7e0110bb02da61
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.040 s
[INFO] Finished at: 2018-11-09T10:56:35+01:00
[INFO] ------------------------------------------------------------------------
Cleaning up...
Cleanup complete in 66.502926ms
FATA[0012] exiting dev mode because the first build failed: building [localhost:5000/gcr_io_k8s-skaffold_skaffold-jib]: digest not found 
```

### Information

- Skaffold version: v0.18.0
- Operating system: Fedora 29
- I have a local registry (localhost:5000)

Thank you :-)

### PR DESCRIPTION
**Pull request by dgageot**
Fixes #1261

### CODE REVIEW

File: pkg/skaffold/docker/client.go [hunk 1]
```diff
@@ -122,11 +123,20 @@ func newMinikubeAPIClient() (client.CommonAPIClient, error) {
...
 		client.WithVersion(version),
 		client.WithHTTPClient(httpclient),
 		client.WithHTTPHeaders(getUserAgentHeader()))
+
+	// Keep the minikube environment variables
+	var environment []string
+	for k, v := range env {
+		environment = append(environment, fmt.Sprintf("%s=%s", k, v))
+	}
+	sort.Strings(environment)
```
Comment (priyawadhwa) [inline pkg/skaffold/docker/client.go]: Is this for testing? If so, it probably makes more sense to have it in the unit test?

Comment (dgageot) [reply pkg/skaffold/docker/client.go]: It's not only for the tests but to make debugging easier. When values are always in the same order, it's simpler
