### PR TITLE
Preserve sync subtree for '***'.

### LINKED ISSUE #1807: How to sync subtrees in 0.25.0?
### Expected behavior

I want to sync subtrees like:

```
src/foo/bar/baz.js -> /usr/src/app/src/foo/bar/baz.js
src/foo2/bot.js -> /usr/src/app/src/foo2/bot.js
src/other.js -> /usr/src/app/src/other.js
something.txt -> usr/src/app/something.txt
```

In 0.23.0, I could accomplish this simply with:

```yaml
    sync:
      '**': /usr/src/app/
```

### Actual behavior

0.25.0 (and 0.24.0) strips all path information from the destination files, so they all get collapsed and synced directly to `/usr/src/app/` (and not subdirectories of it).  This is due to PR #1709.

I would argue that PR #1709 broke working use-cases, because now the only way I know how to achieve this simple subtree mapping is to add explicit sync rules for every subdirectory in my project (!).  The use-case that #1709 was trying to fix (collapsing certain subdirectories into a root) can be achieved by adding explicit rules for specific directories.

Docker does not support any kind of `**` glob match, so I would argue that skaffold's behaviour here should be more predictable (substituting the glob's match into the resulting destination path), rather than trying to follow some notion of how Docker's `COPY` command works.

Sync rules are *not* COPYs, they are tarball generators.   I think recursive tar is the model that should be used for syncing, with its defaults of preserving paths unless explicitly pruned by a mapping.

### Information

- Skaffold version: 0.25.0
- Operating system: darwin-amd64
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta4
kind: Config
build:
  artifacts:
  - image: michaelfig/something
    sync:
      '**': /usr/src/app/
deploy:
  kubectl:
    manifests:
    - 'k8s-*.yaml'
```

### Steps to reproduce the behavior

1. Run `skaffold dev`
2. Create/modify a file somewhere deep in the tree.

### PR DESCRIPTION
**Pull request by michaelfig**
Fixes #1807 

This PR implements subtree syncing for '***' globs in the sync specification.

Given:
```yaml
    sync:
      'foo/***/*.js': /usr/src/app/
```

and changing `foo/baz/bot/test.js`, `test.js` will be synchronized to `/usr/src/app/baz/bot/test.js`.

Given:
```yaml
    sync:
      '***': subdir
```

and changing `my/src.txt`, `src.txt` will be synchronized to `${WORKDIR}/subdir/my/src.txt`.

All the existing sync specs in 0.25.0 mean the same as they did before this PR (i.e. they collapse the subPath, so all files in the subtree are synced to the same destination directory, not its children).  To allow for backward compatibility with 0.23.0's subtree syncing, you can use:

```yaml
    sync:
      '**': /usr/src/app/ # v0.23.0
      '***': /usr/src/app/ # this PR
```

The line marked `this PR` will take precedence over the `v0.23.0` line (triple-stars are matched first before other patterns), except when running a version of Skaffold before this PR.  In that case, the `v0.23.0` line will be used, and only `v0.23.0` will produce the same behaviour as this PR.

Hope this helps,
Michael.

### CODE REVIEW

File: pkg/skaffold/sync/sync.go [hunk 1]
```diff
@@ -128,21 +129,43 @@ func intersect(context string, syncMap map[string]string, files []string, workin
...
+				match, err := doublestar.PathMatch(filepath.FromSlash(pat), relPath)
+				if err != nil {
+					return nil, errors.Wrapf(err, "pattern error for %s", relPath)
+				}
+				if match {
+					var subPath string
+					if isTripleStar {
+						// Map the paths as a tree from the prefix.
+						subtreePrefix := strings.Split(p, "***")[0]
+						subPath = strings.TrimPrefix(relPath, subtreePrefix)
```
Comment (michaelfig) [inline pkg/skaffold/sync/sync.go]: Need:
```go
filepath.FromSlash(subtreePrefix)
```
Otherwise the prefix-pruning fails on Windows.

File: pkg/skaffold/sync/sync_test.go [hunk 2]
```diff
@@ -275,6 +275,61 @@ func TestNewSyncItem(t *testing.T) {
...
+			},
+			workingDir: "/some/dir",
+			builds: []build.Artifact{
+				{
+					ImageName: "test",
+					Tag:       "test:123",
+				},
+			},
+			evt: watch.Events{
+				Added: []string{filepath.Join("dir1", "dir2/node.js")},
```
[the remark this answers is not in the document]
Comment (tejal29) [reply pkg/skaffold/sync/sync_test.go]: i dont like the fact that this for loop is so long and it gets difficult to read.
How about?
```

tripleStarSyncMaps, otherSyncMaps = segregateSyncMaps(syncMaps)
for _, f := range files {
 ...
 var match bool
 // first try all tripleStarSyncMaps
 match, dst, err := matchesTripleStarSyncMap(f)
 if err != nil {
    return nil, err
 }
 if match {
   ret[f] = dst
   continue
 }
 // Try matching others
 match, dst, err := match(otherSyncMaps, f)
 if !match {
  logrus.Infof("Changed file %s does not match any sync pattern. Skipping sync", relPath)
  return nil, nil
 }
 ret[f] = dst
}
...
}


func segregateSyncMaps(syncMap map[string]string) (map[string]string, map[string] string) {
  for p, dst := range syncMap {
     pat := strings.Replace(p, "***", "**", -1)
     if len(pat) != len(p) {
       tripleStarPatter[pat] = dst
     } else {
      doubelStarPattern[p] = dst
    } 
 } 
 return tripleStarPattern, doubleStarPatter
}
```

That ways, we individually test smaller functions.

File: pkg/skaffold/sync/sync.go [hunk 3]
```diff
@@ -128,21 +129,43 @@ func intersect(context string, syncMap map[string]string, files []string, workin
 			return nil, errors.Wrapf(err, "changed file %s can't be found relative to context %s", f, context)
 		}
 		var matches bool
-		for p, dst := range syncMap {
```
Comment (tejal29) [inline pkg/skaffold/sync/sync.go]: i dont like the fact that this for loop is so long and it gets difficult to read.
How about we first find all the TripleStar Patterns, match them and then try all the others?

```

tripleStarSyncMaps, otherSyncMaps = segregateSyncMaps(syncMaps)
for _, f := range files {
 ...
 var match bool
 // first try all tripleStarSyncMaps
 match, dst, err := matchesTripleStarSyncMap(f)
 if err != nil {
    return nil, err
 }
 if match {
   ret[f] = dst
   continue
 }
 // Try matching others
 match, dst, err := matchOthers(otherSyncMaps, f)
 if !match {
  logrus.Infof("Changed file %s does not match any sync pattern. Skipping sync", relPath)
  return nil, nil
 }
 ret[f] = dst
}
...
}


func segregateSyncMaps(syncMap map[string]string) (map[string]string, map[string] string) {
  for p, dst := range syncMap {
     pat := strings.Replace(p, "***", "**", -1)
     if len(pat) != len(p) {
       tripleStarPatter[pat] = dst
     } else {
      doubelStarPattern[p] = dst
    } 
 } 
 return tripleStarPattern, doubleStarPatter
}
```

That ways, we individually test smaller functions.

**Comment by tejal29** [comment]
Thank you for the bug fix! The kokoro job failed due to intergration test flakiness #1538. 
This should be fixed. I have the kokoro-run label. Hopefully a new build will be kicked off soon.

File: pkg/skaffold/sync/sync_test.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (michaelfig) [reply pkg/skaffold/sync/sync_test.go]: AFAICT, the file watcher only returns relative events.  What, specifically, are you suggesting should be the absolute path?

[the remark this answers is not in the document]
Comment (michaelfig) [reply pkg/skaffold/sync/sync_test.go]: No, I see you're right.  I'll have a look.

File: pkg/skaffold/sync/sync.go (hunk 3 above)
Comment (michaelfig) [reply pkg/skaffold/sync/sync.go]: Good suggestion.  Thanks!

**Comment by michaelfig** [comment]
@tejal29 I implemented your proposed changes.  I found and fixed some test failures with absolute paths on Windows.  Would you mind please relabeling `kokoro-run`?

File: pkg/skaffold/sync/sync.go [hunk 4]
```diff
@@ -119,41 +120,108 @@ func latestTag(image string, builds []build.Artifact) string {
...
+	tripleStarPattern = make(map[string]string)
+	doubleStarPattern = make(map[string]string)
+	for p, dst := range syncMap {
+		if strings.Contains(p, "***") {
+			tripleStarPattern[p] = dst
+		} else {
+			doubleStarPattern[p] = dst
+		}
+	}
+	return
```
Comment (tejal29) [inline pkg/skaffold/sync/sync.go]: Thanks, i never knew you can return like this in go.
