### PR TITLE
Only test images that were built

### LINKED ISSUE #4289: container-structure-test fails on cached images
## Expected behavior

Skaffold's tests should either be skipped for cached artifacts OR they should work against cached artifacts.

(What's odd is that the tests are skipped if all artifacts are found in the cache.)

### Actual behavior

Currently Skaffold's structure-tests fail for artifacts found in the artifact cache as it uses the naked image name instead of the image tagged with a digest.

(abridged log with lots of debug info thrown out)
```console
$ skaffold build -v debug
Checking cache...
 - gcr.io/gcp-dev-tools/duct-tape/go: Not found. Building
 - gcr.io/gcp-dev-tools/duct-tape/netcore: Found Locally
Building [gcr.io/gcp-dev-tools/duct-tape/go]...
Sending build context to Docker daemon  6.144kB
...
Successfully tagged gcr.io/gcp-dev-tools/duct-tape/go:d01b3a6
INFO[0010] Build complete in 6.398226954s               
INFO[0010] Running structure tests for files [/Users/bsd/Projects/GPE/repo-sk4j/test/structure-tests-go.yaml] 
DEBU[0010] Running command: [container-structure-test test -v warn --image gcr.io/gcp-dev-tools/duct-tape/go:3e5998fd5bb186e0b517e2c26a6ae482ac894d353efa35600ad928597b33ce90 --config /Users/bsd/Projects/GPE/repo-sk4j/test/structure-tests-go.yaml] 

================================================
====== Test file: structure-tests-go.yaml ======
================================================
=== RUN: Command Test: run with no /dbg should fail
--- PASS
stderr: Error: installation requires a volume mount at /dbg

=== RUN: Command Test: run with /dbg should install
--- PASS
stdout: Installing runtime debugging support files in /dbg
Installation complete

=== RUN: File Existence Test: dlv
--- PASS

=================================================
==================== RESULTS ====================
=================================================
Passes:      3
Failures:    0
Total tests: 3

PASS

INFO[0016] Running structure tests for files [/Users/bsd/Projects/GPE/repo-sk4j/test/structure-tests-netcore.yaml] 
DEBU[0016] Running command: [container-structure-test test -v warn --image gcr.io/gcp-dev-tools/duct-tape/netcore --config /Users/bsd/Projects/GPE/repo-sk4j/test/structure-tests-netcore.yaml] 
=====================================================
====== Test file: structure-tests-netcore.yaml ======
=====================================================
=== RUN: run with no /dbg should fail
--- FAIL
Error: error setting env vars: Error creating container: no such image

=== RUN: run with /dbg should install
--- FAIL
Error: error setting env vars: Error creating container: no such image

=== RUN: vsdbg for .net core
--- FAIL
Error: error setting env vars: Error creating container: no such image


=====================================================
====================== RESULTS ======================
=====================================================
Passes:      0
Failures:    3
Total tests: 3

FAIL
FATA[0000] FAIL                                         
FATA[0015] test failed: running structure tests: running container-structure-test: exit status 1 
```

### PR DESCRIPTION
**Pull request by dgageot**
Fixes #4289

Signed-off-by: David Gageot <david@gageot.net>

### CODE REVIEW

File: pkg/skaffold/test/test.go [hunk 1]
```diff
@@ -74,17 +76,17 @@ func (t FullTester) Test(ctx context.Context, out io.Writer, bRes []build.Artifa
...
-	if len(testCase.StructureTests) == 0 {
+func (t FullTester) runStructureTests(ctx context.Context, out io.Writer, bRes []build.Artifact, tc *latest.TestCase) error {
+	if len(tc.StructureTests) == 0 {
 		return nil
 	}
 
-	files, err := util.ExpandPathsGlob(t.workingDir, testCase.StructureTests)
-	if err != nil {
-		return fmt.Errorf("expanding test file paths: %w", err)
+	fqn, found := resolveArtifactImageTag(tc.ImageName, bRes)
```
Comment (tejal29) [inline pkg/skaffold/test/test.go:84]: can we add a test case where tc.ImageName is not part of the build result?

Comment (dgageot) [reply pkg/skaffold/test/test.go:84]: Done!
