### PR TITLE
fixing non-oneof inline struct handling in schemas

### LINKED ISSUE #1900: json schema generator incorrectly assumes that `inline` fields are `oneOf` fields
For example: 

https://github.com/GoogleContainerTools/skaffold/blob/master/docs/content/en/schemas/v1beta7.json#L1016 theoretically should be just a simple list of properties instead of the `anyOf` section.

### PR DESCRIPTION
**Pull request by balopat**
Fixes #1900, #1901. 
And adds unit tests for schema generation + zero-type checking in `skaffold fix` (fixing a panic case).

### CODE REVIEW

**Comment by balopat** [comment]
I just realized that with this change we have to add "oneOf" tag to all the oneOf fields in old schema versions as well - I'll do that soon.

File: pkg/skaffold/schema/v1beta1/config.go [hunk 1]
```diff
@@ -206,8 +206,8 @@ type HelmImageStrategy struct {
 }
 
 type HelmImageConfig struct {
-	HelmFQNConfig        *HelmFQNConfig        `yaml:"fqn,omitempty"`
-	HelmConventionConfig *HelmConventionConfig `yaml:"helm,omitempty"`
+	HelmFQNConfig        *HelmFQNConfig        `yaml:"fqn,omitempty" yamltags:"oneOf=helmImageStrategy"`
```
Comment (tejal29) [inline pkg/skaffold/schema/v1beta1/config.go]: should this be applied to previous configs as well?

File: hack/schemas/main.go [hunk 2]
```diff
@@ -275,28 +285,44 @@ func (g *schemaGenerator) Apply(inputPath string) ([]byte, error) {
...
+			//if not anyof, continue
+			if !isOneOf(referenced) {
+				if def.Properties == nil {
+					def.Properties = make(map[string]*Definition)
+				}
+				for k, v := range referenced.Properties {
+					def.Properties[k] = v
+				}
+				def.PreferredOrder = append(def.PreferredOrder, referenced.PreferredOrder...)
+				def.Required = append(def.Required, referenced.Required...)
```
Comment (tejal29) [inline hack/schemas/main.go]: Shd this be only added to this struct if its required?

File: hack/schemas/testdata/inline-anyof/output.json [hunk 3]
```diff
@@ -0,0 +1,92 @@
+{
+  "type": "object",
+  "anyOf": [
+    {
+      "$ref": "#/definitions/SkaffoldPipeline"
+    }
+  ],
+  "$schema": "http://json-schema-org/draft-07/schema#",
+  "definitions": {
+    "InlineOneOfStruct": {
```
Comment (tejal29) [inline hack/schemas/testdata/inline-anyof/output.json]: So now along with the possibilities of `TestStruct`, we are generating the Schema for InlineOneofStruct?

File: hack/schemas/testdata/inline-anyof/output.json [hunk 4]
```diff
@@ -0,0 +1,92 @@
...
+          "description": "should be the first choice",
+          "x-intellij-html-description": "should be the first choice"
+        },
+        "field2": {
+          "type": "string",
+          "description": "should be the second choice",
+          "x-intellij-html-description": "should be the second choice"
+        }
+      },
+      "preferredOrder": [
```
Comment (tejal29) [inline hack/schemas/testdata/inline-anyof/output.json]: Since field1 and field2 are "oneOf" is this preferredOrder valid?

File: hack/schemas/testdata/inline-anyof/input.go [hunk 5]
```diff
@@ -0,0 +1,34 @@
...
+	// RequiredField should be required
+	RequiredField     string `yaml:"reqField" yamltags:"required"`
+	InlineOneOfStruct `yaml:"inline"`
+}
+
+//InlineOneOfStruct is embedded inline into TestStruct
+type InlineOneOfStruct struct {
+
+	//Field1 should be the first choice
+	Field1 string `yaml:"field1" yamltags:"oneOf=tag"`
```
Comment (tejal29) [inline hack/schemas/testdata/inline-anyof/input.go]: shd this be "oneOf=inlineOneofStruct"

File: hack/schemas/testdata/inline-anyof/output.json (hunk 3 above)
Comment (balopat) [reply hack/schemas/testdata/inline-anyof/output.json]: question asked in #1908, thank you!

File: hack/schemas/testdata/inline-anyof/output.json (hunk 4 above)
Comment (balopat) [reply hack/schemas/testdata/inline-anyof/output.json]: question asked in #1908, thank you!

File: hack/schemas/main.go [hunk 6]
```diff
@@ -275,28 +285,44 @@ func (g *schemaGenerator) Apply(inputPath string) ([]byte, error) {
...
-			ref := strings.TrimPrefix(anyOf.Ref, defPrefix)
+		for _, inlineStruct := range def.inlines {
+
+			ref := strings.TrimPrefix(inlineStruct.Ref, defPrefix)
 			referenced := definitions[ref]
 
+			//if not anyof, continue
+			if !isOneOf(referenced) {
+				if def.Properties == nil {
+					def.Properties = make(map[string]*Definition)
```
Comment (nkubala) [inline hack/schemas/main.go]: `def.Properties = make(map[string]*Definition, len(referenced.Properties))`

File: hack/schemas/main.go [hunk 7]
```diff
@@ -275,29 +285,37 @@ func (g *schemaGenerator) Apply(inputPath string) ([]byte, error) {
...
-			Properties:           def.Properties,
-			PreferredOrder:       def.PreferredOrder,
-			AdditionalProperties: false,
-		})
 
-		for _, anyOf := range def.AnyOf {
-			ref := strings.TrimPrefix(anyOf.Ref, defPrefix)
-			referenced := definitions[ref]
+		for _, inlineStruct := range def.inlines {
+
```
Comment (nkubala) [inline hack/schemas/main.go]: remove newline

**Comment by balopat** [comment]
> Few other test scenarios:
> 
> 1. What if an Inline Struct is a combination of oneof and other fields? shd this result as an error

this should be validated by schema unit tests - they are not currently tested. 

> 2. Inline Struct contains another Inline?

I would think this wouldn't work with schemagen yet, but haven't tried it - we should create an issue to explore/cover/validate against this edge case but doesn't belong to this PR.
