### PR TITLE
Fail Helm deployments early with missing templated values

### LINKED ISSUE #5072: Fail fast in Helm Templated fields
### Expected behavior

There is a closed issue/PR https://github.com/GoogleContainerTools/skaffold/pull/2793 which implements fail fast behaviour a for a specific field: EnvTemplate. Therefore, for consistency other templated field might also fail fast for consistency.

### Actual behavior
When starting helm deployment without the given env variable using
`skaffold run`

it results in helm errors

```
Helm release <no value>-service not installed. Installing...
Error: create: failed to create: Secret "sh.helm.release.v1.<no value>-service.v1" is invalid: [metadata.name: Invalid value: 
"sh.helm.release.v1.<no value>-service.v1": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), metadata.labels: Invalid value: "<no value>-service": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')]

```

### Information

- Skaffold version: v1.17.0
- Operating system: MacOS Catalina
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: some-service
build:
  artifacts:
    - image: eu.gcr.io/tools-org/some-service
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: "{{.ISTIO_SUBSET}}-some-service"
        chartPath: helm/some-service
        artifactOverrides:
          image: eu.gcr.io/tools-org/some-service
        setValueTemplates:
          istio.version: "{{.ISTIO_SUBSET}}-v1"
      - name: "{{.ISTIO_SUBSET}}-some-service-istio"
        chartPath: helm/istio
        setValueTemplates:
          context: "{{.ISTIO_SUBSET}}"

```

### PR DESCRIPTION
**Pull request by briandealwis**
Fixes #5072

**Description**

Fails Helm deployments early when release or namespaces reference missing templated values.

**User facing changes (remove if N/A)**
Helm deployments fail if the release name or namespaces are templated with missing values.

### CODE REVIEW

File: pkg/skaffold/deploy/helm/deploy.go [hunk 1]
```diff
@@ -124,16 +124,20 @@ func (h *Deployer) Deploy(ctx context.Context, out io.Writer, builds []build.Art
...
-			releaseName, _ := util.ExpandEnvTemplate(r.Name, nil)
 			return nil, userErr(fmt.Sprintf("deploying %q", releaseName), err)
 		}
 
 		// collect namespaces
 		for _, r := range results {
 			var namespace string
-			namespace, err = util.ExpandEnvTemplate(r.Namespace, nil)
+			// `<no value>` is not allowed within a namespace
+			namespace, err = util.ExpandEnvTemplateOrFail(r.Namespace, nil)
```
Comment (tejal29) [inline pkg/skaffold/deploy/helm/deploy.go:140]: shd we  move this check before deploy for config  helm.releases[x].Namespace ?

File: pkg/skaffold/deploy/helm/deploy.go [hunk 2]
```diff
@@ -231,7 +235,7 @@ func (h *Deployer) Dependencies() ([]string, error) {
 // Cleanup deletes what was deployed by calling Deploy.
 func (h *Deployer) Cleanup(ctx context.Context, out io.Writer) error {
 	for _, r := range h.Releases {
-		releaseName, err := util.ExpandEnvTemplate(r.Name, nil)
+		releaseName, err := util.ExpandEnvTemplateOrFail(r.Name, nil)
```
Comment (tejal29) [inline pkg/skaffold/deploy/helm/deploy.go:238]: I wasnt aware release names supports env templates. 
Probably should be added to docs  here https://skaffold.dev/docs/references/yaml/#deploy-helm-releases-name

**Review by tejal29 — CHANGES_REQUESTED** [review]

File: pkg/skaffold/deploy/helm/deploy.go (hunk 1 above)
Comment (briandealwis) [reply pkg/skaffold/deploy/helm/deploy.go:140]: This namespace is [actually expanded and checked in `deployRelease()` itself](https://github.com/GoogleContainerTools/skaffold/blob/0a639aa25e65a4a5b448fdb21b10e91670d40f40/pkg/skaffold/deploy/helm/deploy.go#L355-L358).  So we're good on that front.

But this should be using [`h.releaseNamespace(r)`](https://github.com/GoogleContainerTools/skaffold/blob/0a639aa25e65a4a5b448fdb21b10e91670d40f40/pkg/skaffold/deploy/helm/util.go#L156) since the user could override the namespace on the command-line.

Comment (briandealwis) [reply pkg/skaffold/deploy/helm/deploy.go:140]: Ah, we're ignoring the returned namespaces in our test.
https://github.com/GoogleContainerTools/skaffold/blob/0a639aa25e65a4a5b448fdb21b10e91670d40f40/pkg/skaffold/deploy/helm/helm_test.go#L966

Comment (briandealwis) [reply pkg/skaffold/deploy/helm/deploy.go:140]: Hmm, this should be the deployed artifact's namespace, and so should be expanded.  Looking into this further.

Comment (briandealwis) [reply pkg/skaffold/deploy/helm/deploy.go]: We should just be using the namespace returned from Helm.

This code path isn't tested, but let me see if I can add some tests for this.

**Review by tejal29 — APPROVED** [review]
