### PR TITLE
skaffold diagnose to not initialize runconfig for yaml only flag

### LINKED ISSUE #5701: skaffold diagnose breaks when minikube is paused and docker is force quit
### Steps to reproduce the behavior

1. Start a minikube cluster
2. Set the cluster as the active context
3. Pause the cluster
4. Force quit Docker (The minikube cluster should then stop)
5. run `skaffold diagnose`
6. Get one of 2 minikube errors

```
invalid skaffold config: getting minikube env: running [/usr/local/bin/minikube docker-env --shell none -p minikube]
 - stdout: "\n\n"
 - stderr: "X Exiting due to GUEST_STATUS: state: unknown state \"minikube\": docker container inspect minikube --format=: exit status 1\nstdout:\n\n\nstderr:\nError response from daemon: dial unix docker.raw.sock: connect: connection refused\n\n* \n* If the above advice does not help, please let us know: \n  - https://github.com/kubernetes/minikube/issues/new/choose\n"
 - cause: exit status 80
```
```
invalid skaffold config: getting minikube env: running [/usr/local/bin/minikube docker-env --shell none -p cloud-code-minikube]
 - stdout: "* There is no local cluster named \"cloud-code-minikube\"\n  - To fix this, run: \"minikube start -p cloud-code-minikube\"\n"
 - stderr: ""
 - cause: exit status 85
```

### Expected behavior

`skaffold diagnose` shouldn't say that the config is invalid and should output the config

### Actual behavior

Command errors out when analyzing the valid config saying it is invalid. Should behave just as it would if minikube was stopped normally and correctly analyze the config.

### Information

- Skaffold version: v1.21.0
- Operating system: Mac version 11.2.1
- Installed via: Cloud Code
- Contents of skaffold.yaml:

```yaml
# To learn more about the skaffold.yaml schema visit
# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v2beta4
kind: Config
# defines the Kubernetes manifests to deploy on each run
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/**.yaml
profiles:
# use the cloudbuild profile to build images using Google Cloud Build
- name: cloudbuild
  build:
    googleCloudBuild: {}
# use the dockerfile profile to build images using Docker instead of Jib
- name: dockerfile
  build:
    artifacts:
      - image: java-hello-world
- name: jib
  build:
    tagPolicy:
      sha256: {}
    # defines where to find the code at build time and where to push the resulting image
    artifacts:
      - image: java-hello-world
        # To learn more about how Jib builds Java containers visit
        # https://github.com/GoogleContainerTools/jib
        jib:
          args:
          - -Dmaven.test.skip=true
```

#### Notes
Was working on implementing `skaffold diagnose` into Cloud Code for VS Code when the command kept erroring out. Is likely a minikube bug that is being propagated into skaffold.

### PR DESCRIPTION
**Pull request by tejal29**
Fixes #5701 

In this PR the code is refactored to make sure we don't create a skaffold RunContext object when skaffold diagnose is run with `--yaml-only` flag.

### CODE REVIEW

File: cmd/skaffold/app/cmd/diagnose.go [hunk 1]
```diff
@@ -46,22 +52,13 @@ func NewCmdDiagnose() *cobra.Command {
 }
 
 func doDiagnose(ctx context.Context, out io.Writer) error {
-	runCtx, configs, err := runContext(out, opts)
+	configs, err := withFallbackConfigFunc(out, opts, parser.GetAllConfigs)
```
Comment (gsquared94) [inline cmd/skaffold/app/cmd/diagnose.go:55]: I think that `withFallbackConfigFunc` is trigger the flow of auto-generating `skaffold.yaml` if it doesn't exist (auto skaffold init). We could call `parser.GetAllConfigs` directly for `skaffold diagnose`?

**Review by gsquared94 — APPROVED** [review]
