### PR TITLE
Use git binary or fallback to go-git

### LINKED ISSUE #323: Fails when running in a git worktree directory
### Expected behavior
Runs successfully

### Actual behavior
While tagging the first image:
```
Error: running skaffold steps: build: build step: generating tag: determining current git commit: reference not found
```
### Information

Skaffold version: v0.3.0 
Operating system: Fedora 27 64 bit
Content of skaffold.yaml:
```
apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: gcr.io/k8s-skaffold/skaffold-example
    workspace: .
  local: {}
deploy:
  kubectl:
    manifests:
      - k8s-*
```

### Steps to reproduce the behavior

  1. `git clone https://github.com/GoogleCloudPlatform/skaffold.git && cd skaffold`
  2. `git worktree add /tmp/repo <branch> && cd /tmp/repo/examples/getting-started`
  3. `skaffold run`

### PR DESCRIPTION
**Pull request by dgageot**
The idea is to rollback to using `git` binary by default because go-git doesn't support sa few corner cases. If git is not found it will fallback to using go-git with should be ok 99% of the time

Fixes #323, #563 and #623

Signed-off-by: David Gageot <david@gageot.net>

### CODE REVIEW

File: pkg/skaffold/build/tag/git_commit.go [hunk 1]
```diff
@@ -34,6 +41,45 @@ type GitCommit struct {
 
 // GenerateFullyQualifiedImageName tags an image with the supplied image name and the git commit.
 func (c *GitCommit) GenerateFullyQualifiedImageName(workingDir string, opts *TagOptions) (string, error) {
+	_, err := exec.LookPath("git")
```
Comment (dlorenc) [inline pkg/skaffold/build/tag/git_commit.go]: nit: inline

File: pkg/skaffold/build/tag/git_commit.go [hunk 2]
```diff
@@ -57,38 +99,73 @@ func (c *GitCommit) GenerateFullyQualifiedImageName(workingDir string, opts *Tag
...
+
+func commitOrTag(currentTag string, tags []string, opts *TagOptions) (string, error) {
+	if len(tags) > 0 {
+		currentTag = tags[0]
 	}
 
-	// The file state is dirty. To generate a unique suffix, let's hash all the modified files.
-	// We add a -dirty-unique-id suffix to work well with local iterations.
+	fqn := fmt.Sprintf("%s:%s", opts.ImageName, currentTag)
+	return fqn, nil
```
Comment (dlorenc) [inline pkg/skaffold/build/tag/git_commit.go]: Why return error? It's always nil

**Comment by dgageot** [comment]
@dlorenc Thanks for the review! It should be fixed now.
