### PR TITLE
Pull 'cache-from' images on Google Cloud Build

### LINKED ISSUE #936: cacheFrom option doesn't work
Thanks a lot for building skaffold! 
I feel like I will not need any CI/CD tools soon :) ...almost.

I want to speed up the container building process for my project on Google Cloud.
The problem is that **cacheFrom** option is ignored completely.

### Expected behavior
**cacheFrom** should force build process to use cache from the previously built image
### Actual behavior
build process repeats every time without using the cache 
### Information
I have checked the previously build image on gcr.io - it exists

- Skaffold version: v0.12.0
- Operating system: mac os 10.13.3
- Contents of skaffold.yaml:
```
  - name: stage
    build:
      googleCloudBuild:
        projectId: neural-pub
      artifacts:
        - imageName: gcr.io/neural-pub/api
          workspace: ./api
          docker:
            cacheFrom:
            - gcr.io/neural-pub/api
        - imageName: gcr.io/neural-pub/web
          workspace: ./web
          docker:
            cacheFrom:
            - gcr.io/neural-pub/web
    deploy:
      kubectl:
        manifests:
          - ./ingress/k8s-stage-*
          - ./api/k8s-stage-*
          - ./web/k8s-stage-*
```

### Steps to reproduce the behavior

1. skaffold run --profile stage
2. run this command again

I am wondering - does this feature work on Google Cloud?

### PR DESCRIPTION
**Pull request by dgageot**
Fixes #936

Signed-off-by: David Gageot <david@gageot.net>

### CODE REVIEW

File: pkg/skaffold/build/gcb/desc_test.go [hunk 1]
```diff
@@ -71,3 +71,35 @@ func TestBuildDescription(t *testing.T) {
...
+
+	builder := Builder{
+		GoogleCloudBuild: &v1alpha2.GoogleCloudBuild{
+			DockerImage: "docker/docker",
+		},
+	}
+	desc := builder.buildDescription(artifact, "bucket", "object")
+
+	expected := []*cloudbuild.BuildStep{{
+		Name: "docker/docker",
```
Comment (dlorenc) [inline pkg/skaffold/build/gcb/desc_test.go]: This is unrelated to your change, but should we be using https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/docker instead of docker/docker as the image?

Comment (dgageot) [reply pkg/skaffold/build/gcb/desc_test.go]: By default, we do. This is just a test

Comment (dlorenc) [reply pkg/skaffold/build/gcb/desc_test.go]: Ah, great.
