### PR TITLE
api: Strict port number handling and --enable-rpc deprecation

### LINKED ISSUE #6375: `--rpc-port` should either succeed or fail (TestRunPortForward flake)
[`TestRunPortForward`](https://github.com/GoogleContainerTools/skaffold/blob/main/integration/port_forward_test.go#L55) flakes on Travis on occasion.  The problem is that we run Skaffold requesting a specific RPC port (35964) but it is seemingly unavailable and so Skaffold chooses a different port instead of failing.  The test waits trying to connect to the requested RPC port and times out.

Basically we should honour the requested port specified in `--rpc-port` and fail if unavailable.  This issue is somewhat similar to the reasoning in #5839.

```
=== RUN   TestRunPortForward
time="2021-08-05T01:07:28Z" level=trace msg="Partitions: "
time="2021-08-05T01:07:28Z" level=trace msg="P0 total: 300.000000, size: 6\n"
time="2021-08-05T01:07:28Z" level=trace msg="P1 total: 299.980000, size: 8\n"
time="2021-08-05T01:07:28Z" level=trace msg="P2 total: 299.990000, size: 15\n"
time="2021-08-05T01:07:28Z" level=trace msg="P3 total: 87.830000, size: 16\n"
time="2021-08-05T01:07:28Z" level=debug msg="getting client config for kubeContext: ``"
time="2021-08-05T01:07:28Z" level=info msg="Namespace: skaffoldc2wlk"
time="2021-08-05T01:07:28Z" level=info msg="Running [skaffold run --namespace skaffoldc2wlk --default-repo gcr.io/k8s-skaffold --port-forward --rpc-port 35964 --enable-rpc] in examples/microservices"
    rpc_test.go:378: waiting for connection...
time="2021-08-05T01:07:28Z" level=warning msg="starting gRPC server on port 35965. (35964 is already in use)"
    rpc_test.go:378: waiting for connection...
    rpc_test.go:378: waiting for connection...
    rpc_test.go:378: waiting for connection...
    rpc_test.go:378: waiting for connection...
    rpc_test.go:378: waiting for connection...
    rpc_test.go:378: waiting for connection...
    rpc_test.go:378: waiting for connection...
    rpc_test.go:378: waiting for connection...
    rpc_test.go:378: waiting for connection...
    rpc_test.go:378: waiting for connection...
    rpc_test.go:378: waiting for connection...
    rpc_test.go:378: waiting for connection...
    rpc_test.go:378: waiting for connection...
    rpc_test.go:378: waiting for connection...
    rpc_test.go:378: waiting for connection...
    rpc_test.go:378: waiting for connection...
    rpc_test.go:378: waiting for connection...
    rpc_test.go:378: waiting for connection...
    rpc_test.go:378: waiting for connection...
    rpc_test.go:380: error retrieving event log: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp :35964: connect: connection refused"
    helper.go:194: Skaffold log:
         Generating tags...
        >  - leeroy-web -> gcr.io/k8s-skaffold/leeroy-web:v1.29.0-12-g2ffaeeb
        >  - leeroy-app -> gcr.io/k8s-skaffold/leeroy-app:v1.29.0-12-g2ffaeeb
        >  - base -> gcr.io/k8s-skaffold/base:v1.29.0-12-g2ffaeeb
        > Checking cache...
        >  - leeroy-web: Found Locally
        >  - leeroy-app: Found Locally
        >  - base: Found Locally
        > Starting test...
        > Tags used in deployment:
        >  - leeroy-web -> gcr.io/k8s-skaffold/leeroy-web:81bea89013cde47d2d10613a4efc4389d18fca03dbc35e7b85c90c8b010fc408
        >  - leeroy-app -> gcr.io/k8s-skaffold/leeroy-app:3963b2bcd69186ca063a4a38e1c69b6fa7b1f3774e8991a4cb7cb4db60a78533
        >  - base -> gcr.io/k8s-skaffold/base:285e9d36fd581f2e88fc59983275583b49d7d6e73bb6e1572f99f97306ef9263
        > Starting deploy...
        > Loading images into k3d cluster nodes...
        >  - gcr.io/k8s-skaffold/leeroy-web:81bea89013cde47d2d10613a4efc4389d18fca03dbc35e7b85c90c8b010fc408 -> Found
        >  - gcr.io/k8s-skaffold/leeroy-app:3963b2bcd69186ca063a4a38e1c69b6fa7b1f3774e8991a4cb7cb4db60a78533 -> Found
        > Images loaded in 132.101079ms
        >  - deployment.apps/leeroy-web created
        >  - service/leeroy-app created
        >  - deployment.apps/leeroy-app created
        > Waiting for deployments to stabilize...
        >  - skaffoldc2wlk:deployment/leeroy-web is ready. [1/2 deployment(s) still pending]
        >  - skaffoldc2wlk:deployment/leeroy-app is ready.
        > Deployments stabilized in 2.402 seconds
        > Press Ctrl+C to exit
        > Port forwarding deployment/leeroy-web in namespace skaffoldc2wlk, remote port 8080 -> http://127.0.0.1:9002
        > Port forwarding service/leeroy-app in namespace skaffoldc2wlk, remote port 50051 -> http://127.0.0.1:50053
        > Port forwarding deployment/leeroy-app in namespace skaffoldc2wlk, remote port http -> http://127.0.0.1:9003
        > 
time="2021-08-05T01:07:48Z" level=info msg="Ran [skaffold run --namespace skaffoldc2wlk --default-repo gcr.io/k8s-skaffold --port-forward --rpc-port 35964 --enable-rpc] in 20.106 seconds"
--- FAIL: TestRunPortForward (20.12s)
```

### LINKED ISSUE #6417: [Flake] TestEventsRPC is flaky
I have seen this multiple times 
```
rpc_test.go:93: error retrieving event log: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp :36288: connect: connection refused"
    helper.go:194: Skaffold log:
         Listing files to watch...
        >  - test-dev
        > Generating tags...
        >  - test-dev -> gcr.io/k8s-skaffold/test-dev:v1.29.0-35-gba4e2a8-dirty
        > Starting build...
        > Found [kind-kind] context, using local docker daemon.
        > Building [test-dev]...
        > Sending build context to Docker daemon  3.072kB
        > Step 1/3 : FROM busybox
        >  ---> 69593048aa3a
        > Step 2/3 : COPY foo /foo
        >  ---> Using cache
        >  ---> 608862fe6e54
        > Step 3/3 : CMD while true; do cat /foo; sleep 1; done
        >  ---> Using cache
        >  ---> c302772802f6
        > Successfully built c302772802f6
        > Successfully tagged gcr.io/k8s-skaffold/test-dev:v1.29.0-35-gba4e2a8-dirty
        > Starting test...
        > Tags used in deployment:
        >  - test-dev -> gcr.io/k8s-skaffold/test-dev:c302772802f6c4ce0c7d4d200f03fdcd0cdac4ac74ae980763254fdd55ebb205
        > Starting deploy...
        > Loading images into kind cluster nodes...
        >  - gcr.io/k8s-skaffold/test-dev:c302772802f6c4ce0c7d4d200f03fdcd0cdac4ac74ae980763254fdd55ebb205 -> Found
        > Images loaded in 194.78357ms
        >  - deployment.apps/test-dev created
        > Press Ctrl+C to exit
        > Watching for changes...
        > [test-dev]foo
        > [test-dev]foo
        > [test-dev]foo
        > [test-dev]foo
        > [test-dev]foo
        > [test-dev]foo
        > [test-dev]foo
        > [test-dev]foo
        > [test-dev]foo
        > [test-dev]foo
        > [test-dev]foo
        > [test-dev]foo
        > [test-dev]foo
        > [test-dev]foo
        > [test-dev]foo
        > [test-dev]foo
        > 
--- FAIL: TestEventsRPC (20.84s)
```

### LINKED ISSUE #6425: Proposal: strict port handling and enable flags for Skaffold API (deprecate --enable-rpc)
## Problem

Right now our GRPC/HTTP servers try to choose a port that's different than the provided port number if that's busy. This is problematic for a number of reasons:

1. we query the system to find `usedPorts`, and then make a decision based on that → this is **not atomic** (something might've bind()ed to that port by then, which makes the tests flaky)
2. potential callers of skaffold who provide a preferred port would not<sup>[citation needed]</sup>  expect skaffold to choose a different port (or they will be told to parse `starting gRPC server on port %d`) → **either case bad UX fo the caller?**
3. it's already causing test flakes: #6375 #6417

Context: I believe this port choosing logic was added in response to #4253.

## Proposed Solution

1. **Do not start API server by default** unless the caller specifies `--rpc-port` or both `--rpc-http-port`. (Current behavior: by default `dev`/`run` commands start grpc/http ports 50051/50052, and find adjacent available ports if they are not available).

1. Usage of either `--rpc-port` or `--rpc-http-port` now imply `--enable-rpc=true`.

   :warning: This means the **`--enable-rpc` flag will be deprecated.** All notable customers such as Cloud Code for VSC+IntelliJ are impacted from this.
   
   :warning: This flag will be marked as deprecated in the v1.31 release, and will be removed in v1.32 or in 3 months (whichever is longer, per [deprecation policy](https://skaffold.dev/docs/references/deprecation/)) since the API is a beta feature. 

1. If specified port numbers are busy, **Skaffold now fails instead of trying to find an adjacent available port.** (Let caller find a free port, they can call random() if they like). We might 

## Impact on Existing Users

**Taken only Cloud Code into consideration:**

This is a breaking change for those (1) relying on API servers starting by default and (2) those relying on skaffold's "find an adjacent open port if given port is unavailable" (and parse the actual port from logs). Thankfully Cloud Code is unimpacted:

* CC for VSCode uses only `--rpc-http-port` and they use [a library](https://github.com/sindresorhus/get-port) to find an available port (which uses :0 mechanism, more prone to collisions). They also use `--enable-rpc=true` which will be deprecated with this proposal. 
* CC for IntelliJ uses only `--rpc-port` and they also scan local ports to find an open port (chooses rand port from an open range, less prone to collisions.) They also use `--enable-rpc=true` which will be deprecated with this proposal.

In both cases, the port finding is susceptible to a race condition where the caller thinks the found port number is available, and they pass it to Skaffold, but some other process might've started using it. I don't think we can fix this problem (short of using Unix domain sockets and Windows named pipes).

/cc @nkubala 
/area cleanup
/kind design discussion

### PR DESCRIPTION
**Pull request by ahmetb**
Fixes #6425
Fixes #6417
Fixes #6375
**Related**: #6425 (proposal), supersedes #6443

**Description**

This path implements the proposal in #6425 and contains various breaking
changes to most users of Skaffold APIs regarding enabling the Skaffold API,
and how port numbers behave.

This patch also fixes the test flakes for the following integration tests (each
ran 100 times) by behaving more strictly around busy ports.

- TestEventsRPC (#6417)
- TestRunPortForward (#6375)

**User facing changes (remove if N/A)**

* API is no longer enabled by default for "dev" and "debug" commands.
  This might be a breaking change for some users who were relying on the
  behavior.

* APIs are only enabled if --rpc-port or --rpc-http-port (or both) are set.
  These flags no longer have defaults 50051 and 50052.

* --enable-rpc flag is now marked as "deprecated" for 1.31 release.
  It will be removed in 3 months or 1 release (whichever is longer) since the
  Skaffold API is a beta feature.

* If given port is busy, skaffold now fails with an error instead of trying
  to find an available port and printing it to logs.

**Follow-up Work**

Since Skaffold API feature is _beta_, `--enable-rpc` flag deprecation will
start in the release this is incorporated in, and will be removed in the next
release or 3 months (whichever is longer) per deprecation policy.

Subsequently, we can remove the tests and code looking for this flag.

### CODE REVIEW

File: pkg/skaffold/server/server.go [hunk 1]
```diff
@@ -189,29 +191,24 @@ func newGRPCServer(preferredPort int, usedPorts *util.PortSet) (func() error, in
 	}, port, nil
 }
 
-func newHTTPServer(preferredPort, proxyPort int, usedPorts *util.PortSet) (func() error, error) {
```
Comment (briandealwis) [inline pkg/skaffold/server/server.go:192]: We should

File: pkg/skaffold/config/types.go [hunk 2]
```diff
@@ -106,6 +108,47 @@ type Muted struct {
...
+}
+
+func (s *IntOrUndefined) SetNil() error {
+	s.value = nil
+	return nil
+}
+
+func (s *IntOrUndefined) String() string {
+	if s.value == nil {
+		return ""
```
Comment (briandealwis) [inline pkg/skaffold/config/types.go:143]: This is the value used in the help text.  So you could use `<unset>` or something like that to help users:
```
      --rpc-http-port=: tcp port to expose the Skaffold API over HTTP REST
      --rpc-port=: tcp port to expose the Skaffold API over gRPC
```

File: pkg/skaffold/server/server.go [hunk 3]
```diff
@@ -96,18 +96,25 @@ func SetAutoSyncCallback(callback func(bool)) {
...
+	grpcCallback, grpcPort, err := newGRPCServer(preferredGRPCPort)
 	if err != nil {
 		return grpcCallback, fmt.Errorf("starting gRPC server: %w", err)
 	}
+	httpCallback := emptyCallback
 
-	httpCallback, err := newHTTPServer(opts.RPCHTTPPort, rpcPort, &usedPorts)
+	if opts.RPCHTTPPort.Value() != nil {
+		httpCallback, err = newHTTPServer(*opts.RPCHTTPPort.Value(), grpcPort)
+	}
```
Comment (briandealwis) [inline pkg/skaffold/server/server.go:117]: If `--enable-rpc` was specified alone, then we need to implicitly work as if the user specified `--rpc-port=50051 --rpc-http-port=50052`.

Since you're disabling the `--enable-rpc` default for `dev` and `debug`, failing if the ports are unavailable is the right thing to do in this situation since the user can't really figure out the ports anyways.

I think you should extract this port-checking-and-determination to a separate function that can be tested.  Something like
```
grpcPort, httpPort := evaluateOptions(opts)
if grpcPort < 0 && httpPort < 0 {
    logrus.Debug("skaffold API not starting as it's not requested")
    return emptyCallback, nil
}
```

Port 0 may make sense for users who don't care about the port but are streaming events for debugging purposes.

File: pkg/skaffold/server/server.go (hunk 1 above)
Comment (ahmetb) [reply pkg/skaffold/server/server.go:192]: probably not. in existing code, the PortSet instance was not shared with the other PortSet instance used in port-forwrding, so it already had no use. the code on the other side already checks for availibility, too, so it seemed redundant to me.

File: pkg/skaffold/config/types.go (hunk 2 above)
Comment (ahmetb) [reply pkg/skaffold/config/types.go:143]: I actually wanted to get rid of the `=:` part (just need `:`), but could not figure it out. I'll probably do what you said.

File: pkg/skaffold/server/server.go (hunk 3 above)
Comment (ahmetb) [reply pkg/skaffold/server/server.go:117]: Now that --enable-rpc is gone, here are the possible scenarios:


input1 | input2 | http port | grpc port | 
--|--|--|--|
-rpc-port=unset  | -http-port=unset | not started | not started
-rpc-port=X  | -http-port=unset | not started | X
-rpc-port=X  | -http-port=Y | Y | X
-rpc-port=unset  | -http-port=Y | Y | bind to a random port with :0

We also don't need 50051 & 50052 defaults anymore (CC does not rely on these).

We can extract to a fn and try to test it but the check is basically:

    if both grpc and http port opts are unset {
       return
    }

@briandealwis thoughts?

Comment (briandealwis) [reply pkg/skaffold/server/server.go:117]: This table is great it needs `--enable-rpc` too: we need to support `--enable-rpc` until we remove `--enable-rpc` after the deprecation period.

> We also don't need 50051 & 50052 defaults anymore (CC does not rely on these).

But users may.  CC is not the only user of the gRPC + REST APIs.

Comment (ahmetb) [reply pkg/skaffold/server/server.go:117]: > This table is great it needs `--enable-rpc` too: we need to support `--enable-rpc` until we remove `--enable-rpc` after the deprecation period.

Currently, this is what I had in mind without incorporating the default ports

--enable-rpc | --rpc-port | --http-port | http port | grpc port | 
|--|--|--|--|--|
| false  | *  | *  | not started | not started
| unset | -rpc-port=unset  | -http-port=unset | not started | not started <sup>1</sup>
| unset | -rpc-port=unset  | -http-port=unset | not started | not started <sup>1</sup>
| true | -rpc-port=unset  | -http-port=unset | bind random (:0)  <sup>2</sup> | bind random (:0) <sup>2</sup>
| true or unset | -rpc-port=X  | -http-port=unset | not started | X
| true or unset | -rpc-port=X  | -http-port=Y | Y | X
| true or unset | -rpc-port=unset  | -http-port=Y | Y | bind random (:0)

<sup>1</sup>: This is breaking change for users who were relying on skaffold dev/debug commands starting the server implicitly by default.

<sup>2</sup>: This is breaking change for users who were relying on default ports.

> But users may. CC is not the only user of the gRPC + REST APIs.

Given the complexity of the table above, I'm not sure if we can roll it forward without breaking anyone. Let me know if you see a way. My plan was to roll this forward in lockstep with CC team.

Comment (ahmetb) [reply pkg/skaffold/server/server.go:117]: Refined the table above, make sure to refer to the one on GitHub UI.

Comment (nkubala) [reply pkg/skaffold/server/server.go:117]: I don't know that there's a way to make these changes without breaking an existing flow, and given that I think we should choose the flow that we think will affect the least users, which to me feels like providing `--enable-rpc=true` without specifying either port explicitly. users who are expecting the server to be available on `50051/50052` will be broken, but can introspect on the logs for the port we've selected, and can also begin passing the port explicitly to get their existing behavior back. we can even issue a specific deprecation notice/suggestion for this specific flow.

my intuition is that this will affect a small subset of users and the fix is relatively painless. @briandealwis WDYT

Comment (briandealwis) [reply pkg/skaffold/server/server.go:117]: This is my suggestion

--enable-rpc | --rpc-port | --http-port | http port | grpc port | 
|--|--|--|--|--|
| false  | *  | *  | not started | not started
| true | unset  | unset | ~bind random (:0)~ **port 50052, fail if unavailable** | ~bind random (:0)~ **port 50051, fail if unavailable**
| true | X  | unset | **port 50052, fail if unavailable** | X
| true | unset  | Y | Y | **port 50051, fail if unavailable**
| ~true or~ **unset** | X  | unset | not started | X
| ~true or~ **unset** | X  | Y | Y | X
| ~true or~ **unset** | unset  | Y | Y | bind random (:0)

So the only change is that `--enable-rpc` will fail when either port 50051 or 50052 are unavailable whereas we previously allocating a new nearby port.  The warning text can recommend using `--rpc-port=0` or `--rpc-http-port=0` for a randomly assigned port.

We could even collapse the `--enable-rpc == false` with the `--enable-rpc == unset` cases

Comment (briandealwis) [reply pkg/skaffold/server/server.go:117]: (I think this agrees with Nick)

Comment (ahmetb) [reply pkg/skaffold/server/server.go:117]: @briandealwis problem with the changes suggested in rows 3 and 4 is that we are removing "if busy find adjacent port" logic.

So if you start HTTP server on :X, but we default gRPC to port 50051, the second instance of skaffold running simultaneously will fail to launch.

Therefore, I recommend retaining the recommended behavior in rows 3 and 4. 

We can implement your recommendation in row 2 and add a warning message for the case both ports are unset.

Comment (ahmetb) [reply pkg/skaffold/server/server.go:117]: > problem with the changes suggested in rows 3 and 4 is that we are removing "if busy find adjacent port" logic.

To be clear, this is going to happen if someone's explicitly setting the --enable-rpc (i.e. IDE integration or otherwise) and they're running multiple `skaffold` processes. Cloud Code currently does this (it specifies either --rpc-port or --rpc-http-port), so if they somehow they start a 2nd skaffold instance, we'd fail if we choose the legacy default port and another process was using it.

Comment (ahmetb) [reply pkg/skaffold/server/server.go:117]: @briandealwis @nkubala I am inclined to keep the initially proposed behavior here

> So the only change is that `--enable-rpc` will fail when either port 50051 or 50052 are unavailable whereas we previously allocating a new nearby port. The warning text can recommend using `--rpc-port=0` or `--rpc-http-port=0` for a randomly assigned port.

This will be a problem for two reasons.

1. if we keep such default ports, they can't be "default values" on the flags, because setting the flag now means enable the API, which we're moving away from
2. it's problematic for Cloud Code implementations such as VSCode, where they choose -rpc-http-port explicitly. if "we choose -rpc-port as 50051 and fail if busy", then multiple skaffold instances ran by CC for VSC will fail, we don't want this during the rollout of this.

The only thing I want to add is: If `--enable-rpc` is specified but no ports whatsoever, print a warning saying skaffold is choosing ports.

**Comment by ahmetb** [comment]
I added 1fd70e2 which provides the warning message.
@nkubala @briandealwis take another look please, this should be ok to move forward.

**Review by tejal29 — CHANGES_REQUESTED** [review]
Lets make it more user friendly by showing the random port instead of warning message forcing users to quit skaffold.

**Comment by ahmetb** [comment]
> Can we just show the random port assigned in warn instead of info if the `opts.EnableRPC && opts.RPCPort.Value() == nil && opts.RPCHTTPPort.Value() == nil` and remove this warn message here.

@tejal29 Ack. This only applies to the GRPC port, since we don't start HTTP by default as part of the proposal. But I updated the warning in d81eb1268.

**Comment by ahmetb** [comment]
@tejal29 PTAL if you can, it seems like today is the release cutoff date. cc: @nkubala

**Review by tejal29 — APPROVED** [review]
