### PR TITLE
Check for new skaffold version when skaffold.yaml parsing fails

### LINKED ISSUE #1570: Skaffold should check for updates when the skaffold yaml has a wrong version
Sometimes, users have an outdated version of Skaffold and try to run it on recent examples.
they get this error:

```
FATA[0000] creating runner: parsing skaffold config: unknown api version: 'skaffold/v1beta4'
```

It would be super useful to then run a version check and tell the user if a more recent version is available, which version and a link to the installation instructions.

### PR DESCRIPTION
**Pull request by corneliusweig**
Re-uses the already existing asynchronous version check. Now, if parsing fails, the check is repeated synchronously and an appropriate warning is shown.

Fixes #1570

### CODE REVIEW

File: pkg/webhook/kubernetes/deployment.go [hunk 1]
```diff
@@ -139,6 +139,7 @@ func WaitForDeploymentToStabilize(d *appsv1.Deployment, ip string) error {
 		if err != nil {
 			return false, nil
 		}
+		defer resp.Body.Close()
```
Comment (nkubala) [inline pkg/webhook/kubernetes/deployment.go]: were you running into an issue that this fixed? since it's unrelated to the rest of this change I'd like to see it in a separate commit, just so we can better track it.

File: pkg/skaffold/update/update.go [hunk 2]
```diff
@@ -43,23 +42,28 @@ func IsUpdateCheckEnabled() bool {
...
 	if err != nil {
-		return semver.Version{}, errors.Wrap(err, "parsing latest version from GCS")
+		return semver.Version{}, false, errors.Wrap(err, "parsing latest version from GCS")
 	}
-	return v, nil
+	current, err := version.ParseVersion(version.Get().Version)
+	if err != nil {
+		return semver.Version{}, false, errors.Wrap(err, "parsing current semver, skipping update check")
+	}
+	isAhead := latest.GT(current)
```
Comment (nkubala) [inline pkg/skaffold/update/update.go]: nit: can combine this with the next line to avoid creating a new variable

File: pkg/webhook/kubernetes/deployment.go (hunk 1 above)
Comment (corneliusweig) [reply pkg/webhook/kubernetes/deployment.go]: I didn't have an issue, no. But the doc says

> It is the caller's responsibility to close Body.

So I assumed it was simply forgotten here (...and all other calls to `http.Get(...)` do call close).

File: pkg/skaffold/update/update.go (hunk 2 above)
Comment (corneliusweig) [reply pkg/skaffold/update/update.go]: yeah, I also thought about this. Should be changed now.

File: pkg/webhook/kubernetes/deployment.go (hunk 1 above)
Comment (nkubala) [reply pkg/webhook/kubernetes/deployment.go]: mmm ok I guess I'm fine with it here :)

File: pkg/skaffold/update/update.go [hunk 3]
```diff
@@ -43,23 +42,27 @@ func IsUpdateCheckEnabled() bool {
 	return v == "" || strings.ToLower(v) == "true"
 }
 
-// GetLatestVersion uses a VERSION file stored on GCS to determine the latest released version of skaffold
-func GetLatestVersion(ctx context.Context) (semver.Version, error) {
+// VersionCheck uses a VERSION file stored on GCS to determine the latest released version of skaffold
```
Comment (balopat) [inline pkg/skaffold/update/update.go]: please clarify the meaning of the returned values in the godoc

File: cmd/skaffold/app/cmd/cmd.go [hunk 4]
```diff
@@ -98,15 +97,11 @@ func updateCheck(ch chan string) error {
...
 	if err != nil {
-		return errors.Wrap(err, "parsing current semver, skipping update check")
+		return errors.Wrap(err, "version check")
 	}
-	latest, err := update.GetLatestVersion(context.Background())
-	if err != nil {
-		return errors.Wrap(err, "getting latest version")
-	}
-	if latest.GT(current) {
+	if isAhead {
```
Comment (balopat) [inline cmd/skaffold/app/cmd/cmd.go]: I find `isAhead` confusing - what is ahead of what? `currentVersionOutdated` or `updateNeeded` seem more understandable.

File: pkg/skaffold/update/update.go (hunk 3 above)
Comment (corneliusweig) [reply pkg/skaffold/update/update.go]: Very good points. Your comments are quite related, which made me think that the API for `GetLatestVersion` is actually pretty bad. I think I have found a much better solution which addresses both your concerns.

Please let me know if you prefer those commits to be squashed.
