### PR TITLE
Fix skaffold build templating output and add tests

### LINKED ISSUE #1839: Fix skaffold build output templating
While reproducing #922 i discovered "--output" flag does not work as documented.

### Expected behavior
`skaffold build -o` should work as documented.
### Actual behavior
Running `skaffold build -o` does not work without `--quiet` flag present.
The help does not mention this.

The help also mentions,
```
tejaldesai@ (deploy_build) $ ../../out/skaffold build help
Usage:
  skaffold build [flags]

Flags:
  -b, --build-image stringArray      Choose which artifacts to build. Artifacts with image names that contain the expression will be built only. Default is to build sources for all artifacts
      --cache-artifacts              Set to true to enable caching of artifacts.
      --cache-file string            Specify the location of the cache file (default $HOME/.skaffold/cache)
  -d, --default-repo string          Default repository value (overrides global config)
      --enable-rpc skaffold dev      Enable gRPC for exposing Skaffold events (true by default for skaffold dev)
  -f, --filename string              Filename or URL to the pipeline file (default "skaffold.yaml")
  -h, --help                         help for build
  -n, --namespace string             Run deployments in the specified namespace
  -o, --output *flags.TemplateFlag   Format output with go-template. For full struct documentation, see https://godoc.org/github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd#BuildOutput (default {{range .Builds}}{{.ImageName}} -> {{.Tag}}
```
The default value is incorrect. it should be `{{range .Builds}}{{.ImageName}} -> {{.Tag}}{{end}}`
Also, this default is not respected.
```
tejaldesai@ (deploy_build) $ ../../out/skaffold build -q -o 
Usage:
  skaffold build [flags]

Flags:
  -b, --build-image stringArray      Choose which artifacts to build. Artifacts with image names that contain the expression will be built only. Default is to build sources for all artifacts
      --cache-artifacts              Set to true to enable caching of artifacts.
      --cache-file string            Specify the location of the cache file (default $HOME/.skaffold/cache)
  -d, --default-repo string          Default repository value (overrides global config)
      --enable-rpc skaffold dev      Enable gRPC for exposing Skaffold events (true by default for skaffold dev)
  -f, --filename string              Filename or URL to the pipeline file (default "skaffold.yaml")
  -h, --help                         help for build
  -n, --namespace string             Run deployments in the specified namespace
  -o, --output *flags.TemplateFlag   Format output with go-template. For full struct documentation, see https://godoc.org/github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd#BuildOutput (default {{range .Builds}}{{.ImageName}} -> {{.Tag}}
                                     {{end}})
  -p, --profile stringArray          Activate profiles by name
  -q, --quiet                        Suppress the build output and print image built on success
      --rpc-port int                 tcp port to expose event API (default 50051)
      --skip-tests                   Whether to skip the tests after building
      --toot                         Emit a terminal beep after the deploy is complete

Global Flags:
      --color int          Specify the default output color in ANSI escape codes (default 34)
  -v, --verbosity string   Log level (debug, info, warn, error, fatal, panic) (default "warning")

FATA[0000] flag needs an argument: 'o' in -o  
```
### Information

- Skaffold version: version...
- Operating system: ...
- Contents of skaffold.yaml:

```yaml
<paste your skaffold.yaml here>
```

### Steps to reproduce the behavior

1. ...
2. ...

### PR DESCRIPTION
**Pull request by tejal29**
fixes #1839 

In this commit

- Add better description on flags so its clear, `skaffold build -o` is only useful with --quiet.
- suppress "Complete in " line with --quiet flag so that  `skaffold build --quiet > build.out` output can consumed to by `skaffold deploy` to correctly parse and construct a build.Artifacts object.
- Refactor runBuild to move creating a runner and actually building artifacts to another function, so it can be mocked in tests.
- add tests for --quiet flag and make sure output is as expected when a template is specified vs when its not.
- change default template to "{{.}}"

### CODE REVIEW

File: cmd/skaffold/app/cmd/build.go [hunk 1]
```diff
@@ -100,3 +91,26 @@ func runBuild(out io.Writer) error {
...
+
+	runner, config, err := newRunner(opts)
+	var targetArtifacts []*latest.Artifact
+	for _, artifact := range config.Build.Artifacts {
+		if runner.IsTargetImage(artifact) {
+			targetArtifacts = append(targetArtifacts, artifact)
+		}
+	}
+	if err != nil {
+		return nil, func() { cancel() }, errors.Wrap(err, "creating runner")
```
Comment (dgageot) [inline cmd/skaffold/app/cmd/build.go]: Could you return `cancel` instead of `func() { cancel() }`?

File: cmd/skaffold/app/cmd/build.go [hunk 2]
```diff
@@ -100,3 +91,26 @@ func runBuild(out io.Writer) error {
 
 	return nil
 }
+
+func createRunnerAndBuild(buildOut io.Writer) ([]build.Artifact, func(), error) {
+	ctx, cancel := context.WithCancel(context.Background())
```
Comment (dgageot) [inline cmd/skaffold/app/cmd/build.go]: Can you move those two lines outside the function to avoid returning a func()?

File: cmd/skaffold/app/cmd/build_test.go [hunk 3]
```diff
@@ -0,0 +1,124 @@
...
+			Tag:       "test",
+		}}, func() {}, nil
+	}
+
+	orginalCreateRunner := createRunnerAndBuildFunc
+	defer func(c func(buildOut io.Writer) ([]build.Artifact, func(), error)) {
+		createRunnerAndBuildFunc = c
+	}(orginalCreateRunner)
+	var tests = []struct {
+		name           string
```
Comment (dgageot) [inline cmd/skaffold/app/cmd/build_test.go]: This is called `description` is almost every test

File: cmd/skaffold/app/cmd/build_test.go [hunk 4]
```diff
@@ -0,0 +1,124 @@
...
+		template       string
+		expectedOutput []byte
+		mock           func(io.Writer) ([]build.Artifact, func(), error)
+		shdErr         bool
```
Comment (dgageot) [inline cmd/skaffold/app/cmd/build_test.go]: This is called `shouldErr` is almost every test

File: cmd/skaffold/app/cmd/build_test.go [hunk 5]
```diff
@@ -0,0 +1,124 @@
...
+	}{
+		{
+			name:           "quiet flag print build images with no template",
+			expectedOutput: []byte("{[{gcr.io/skaffold/example test}]}"),
+			shdErr:         false,
```
Comment (dgageot) [inline cmd/skaffold/app/cmd/build_test.go]: We usually skip those `shdErr: false`

File: cmd/skaffold/app/cmd/build.go [hunk 6]
```diff
@@ -100,3 +95,18 @@ func runBuild(out io.Writer) error {
...
+	var targetArtifacts []*latest.Artifact
+	for _, artifact := range config.Build.Artifacts {
+		if runner.IsTargetImage(artifact) {
+			targetArtifacts = append(targetArtifacts, artifact)
+		}
+	}
+	if err != nil {
+		return nil, errors.Wrap(err, "creating runner")
+	}
+	defer runner.RPCServerShutdown()
```
Comment (dgageot) [inline cmd/skaffold/app/cmd/build.go]: Shouldn't it be called just after `runner, config, err := newRunner(opts)`

File: cmd/skaffold/app/cmd/build.go [hunk 7]
```diff
@@ -100,3 +95,18 @@ func runBuild(out io.Writer) error {
...
+
+func createRunnerAndBuild(ctx context.Context, buildOut io.Writer) ([]build.Artifact, error) {
+	runner, config, err := newRunner(opts)
+	var targetArtifacts []*latest.Artifact
+	for _, artifact := range config.Build.Artifacts {
+		if runner.IsTargetImage(artifact) {
+			targetArtifacts = append(targetArtifacts, artifact)
+		}
+	}
+	if err != nil {
```
Comment (dgageot) [inline cmd/skaffold/app/cmd/build.go]: Should be just after we get the `err`

File: cmd/skaffold/app/cmd/build.go (hunk 6 above)
Comment (tejal29) [reply cmd/skaffold/app/cmd/build.go]: yeah i think, i moved code over by mistake.

File: cmd/skaffold/app/cmd/build_test.go [hunk 8]
```diff
@@ -0,0 +1,127 @@
...
+	errRunner := func(c context.Context, buildOut io.Writer) ([]build.Artifact, error) {
+		return nil, errors.New("some error")
+	}
+	mockCreateRunner := func(c context.Context, buildOut io.Writer) ([]build.Artifact, error) {
+		return []build.Artifact{{
+			ImageName: "gcr.io/skaffold/example",
+			Tag:       "test",
+		}}, nil
+	}
+	orginalCreateRunner := createRunnerAndBuildFunc
```
Comment (dgageot) [inline cmd/skaffold/app/cmd/build_test.go]: This can be simplified:

```
defer func(f func(context.Context, io.Writer) ([]build.Artifact, error)) {createRunnerAndBuildFunc = f}(createRunnerAndBuildFunc)
```

The original value of `createRunnerAndBuildFunc` is captured so you don't need to create an `orginalCreateRunner` variable

File: cmd/skaffold/app/cmd/build_test.go [hunk 9]
```diff
@@ -0,0 +1,127 @@
...
+			createRunnerAndBuildFunc = test.mock
+			var output bytes.Buffer
+			err := runBuild(&output)
+			testutil.CheckErrorAndDeepEqual(t, test.shouldErr, err, string(test.expectedOutput), output.String())
+		})
+	}
+}
+
+func TestRunBuild(t *testing.T) {
+	errRunner := func(c context.Context, buildOut io.Writer) ([]build.Artifact, error) {
```
Comment (dgageot) [inline cmd/skaffold/app/cmd/build_test.go]: I would omit the argument names since they are not used.

File: cmd/skaffold/app/cmd/build_test.go [hunk 10]
```diff
@@ -0,0 +1,127 @@
...
+		return nil, errors.New("some error")
+	}
+	mockCreateRunner := func(c context.Context, buildOut io.Writer) ([]build.Artifact, error) {
```
Comment (dgageot) [inline cmd/skaffold/app/cmd/build_test.go]: I would omit the argument names since they are not used.

File: cmd/skaffold/app/cmd/build_test.go [hunk 11]
```diff
@@ -0,0 +1,127 @@
...
+
+func TestQuietFlag(t *testing.T) {
+	mockCreateRunner := func(c context.Context, buildOut io.Writer) ([]build.Artifact, error) {
+		return []build.Artifact{{
+			ImageName: "gcr.io/skaffold/example",
+			Tag:       "test",
+		}}, nil
+	}
+
+	orginalCreateRunner := createRunnerAndBuildFunc
```
Comment (dgageot) [inline cmd/skaffold/app/cmd/build_test.go]: same as below (Sorry I read from bottom to top...)

File: cmd/skaffold/app/cmd/build_test.go (hunk 8 above)
Comment (tejal29) [reply cmd/skaffold/app/cmd/build_test.go]: umm the value of createRunnerAndBuildFunc is set to a mock function here, 
```
	for _, test := range tests {
		t.Run(test.description, func(t *testing.T) {
			quietFlag = true
			defer func() { quietFlag = false }()
			if test.template != "" {
				buildFormatFlag = flags.NewTemplateFlag(test.template, BuildOutput{})
			}
			defer func() { buildFormatFlag = nil }()
			createRunnerAndBuildFunc = test.mock
```

File: cmd/skaffold/app/cmd/build_test.go (hunk 11 above)
Comment (tejal29) [reply cmd/skaffold/app/cmd/build_test.go]: same. they are set to mock functions in the test runs.

File: cmd/skaffold/app/cmd/build_test.go (hunk 9 above)
Comment (tejal29) [reply cmd/skaffold/app/cmd/build_test.go]: fixed.

File: cmd/skaffold/app/cmd/build_test.go (hunk 10 above)
Comment (tejal29) [reply cmd/skaffold/app/cmd/build_test.go]: fixed
