### PR TITLE
fix show some option in skaffold delete #1995

### LINKED ISSUE #1995: Skaffold delete help shows some options which don't make sense.
### Expected behavior
`delete` should only have relevant args.

### Actual behavior
Some of the args for `delete` don't make sense e.g. "--skip-tests", "cache-artifacts", "cache-file".
We should fix this.
```tejaldesai@tejaldesai~/go/src/github.com/GoogleContainerTools/skaffold: (remove_pre_built_image_builder)$ skaffold delete --help
Delete the deployed resources

Usage:
  skaffold delete [flags]

Flags:
      --cache-artifacts                 Set to true to enable caching of artifacts.
      --cache-file string               Specify the location of the cache file (default $HOME/.skaffold/cache)
  -d, --default-repo string             Default repository value (overrides global config)
      --enable-rpc skaffold dev         Enable gRPC for exposing Skaffold events (true by default for skaffold dev)
  -f, --filename string                 Filename or URL to the pipeline file (default "skaffold.yaml")
  -h, --help                            help for delete
      --insecure-registry stringArray   Target registries for built images which are not secure
  -n, --namespace string                Run deployments in the specified namespace
      --no-prune                        Skip removing images and containers built by Skaffold
  -p, --profile stringArray             Activate profiles by name
      --rpc-http-port int               tcp port to expose event REST API over HTTP (default 50052)
      --rpc-port int                    tcp port to expose event API (default 50051)
      --skip-tests                      Whether to skip the tests after building
      --toot                            Emit a terminal beep after the deploy is complete

Global Flags:
      --color int          Specify the default output color in ANSI escape codes (default 34)
  -v, --verbosity string   Log level (debug, info, warn, error, fatal, panic) (default "warning")
```

some of the delete args are incorrect, we should fix it :)
### Information

- Skaffold version: version...
- Operating system: ...
- Contents of skaffold.yaml:

```yaml
<paste your skaffold.yaml here>
```

### Steps to reproduce the behavior

1. ...
2. ...

### PR DESCRIPTION
**Pull request by u5surf**
fixes #1995

### CODE REVIEW

File: cmd/skaffold/app/cmd/cmd.go [hunk 1]
```diff
@@ -142,6 +142,19 @@ func FlagToEnvVarName(f *pflag.Flag) string {
 	return fmt.Sprintf("SKAFFOLD_%s", strings.Replace(strings.ToUpper(f.Name), "-", "_", -1))
 }
 
+func AddRunDeleteFlags(cmd *cobra.Command) {
+	cmd.Flags().BoolVar(&opts.EnableRPC, "enable-rpc", false, "Enable gRPC for exposing Skaffold events (true by default for `skaffold dev`)")
+	cmd.Flags().IntVar(&opts.RPCPort, "rpc-port", constants.DefaultRPCPort, "tcp port to expose event API")
```
Comment (tejal29) [inline cmd/skaffold/app/cmd/cmd.go]: Can you move these flags to AddCommonFlags ?
```
AddRunDevFlags(cmd *cobra.Command) {
   AddRunCommonDevFlags(cmd)
  cmd.Flags().BoolVar(&opts.CacheArtifacts, "cache-artifacts", false, "Set to true to enable caching of artifacts.")
  cmd.Flags().StringVarP(&opts.CacheFile, "cache-file", "", "", "Specify the location of the cache file (default $HOME/.skaffold/cache)")

}
```
