### PR TITLE
Ignore empty manifests

### LINKED ISSUE #499: Deployment Fails with YAML start of document ---
### Expected behavior

YAML documents starting with `---` shouldn't cause errors during deployment

### Actual behavior

YAML is rendered incorrectly, but only on files with image interpolation, that causes deployment to fail

### Information

```
Starting deploy...
WARN[0007] run: deploy: deploy step: deploying manifests: running kubectl: stdout: compositecontroller.metacontroller.k8s.io "consumer-deployment-controller" created
customresourcedefinition.apiextensions.k8s.io "consumer-deployment-controllers.mindetic.gt8" created
, stderr: error: error validating "STDIN": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
, err: exit status 1: exit status 1 
Watching for changes...
^CCleaning up...
WARN[0012] cleanup: deleting manifests: running kubectl: stdout: compositecontroller.metacontroller.k8s.io "consumer-deployment-controller" deleted
customresourcedefinition.apiextensions.k8s.io "consumer-deployment-controllers.mindetic.gt8" deleted
, stderr: Error from server (NotFound): error when stopping "STDIN": deployments.extensions "consumer-deployment-controller" not found
Error from server (NotFound): error when deleting "STDIN": services "consumer-deployment-controller" not found
, err: exit status 1: exit status 1
```

```
Skaffold version: v0.5.0
Operating system: Linux
```

Content of skaffold.yaml:

```
apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: "gcr.io/gt8-mindetic/consumer-deployment-controller"
deploy:
  kubectl:
    manifests:
      - ./opt/kubernetes/composite-controller.yaml
      - ./opt/kubernetes/consumer-deployment-controller.yaml
      - ./opt/kubernetes/service.yaml
      - ./opt/kubernetes/deployment.yaml

```

Deployment.yaml

```

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: consumer-deployment-controller
  namespace: metacontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-deployment-controller
  template:
    metadata:
      labels:
        app: consumer-deployment-controller
    spec:
      containers:
      - name: controller
        image: gcr.io/***/consumer-deployment-controller
        imagePullPolicy: Always
```

### PR DESCRIPTION
**Pull request by dgageot**
Fixes #499

Signed-off-by: David Gageot <david@gageot.net>

### CODE REVIEW

File: pkg/skaffold/deploy/kubectl.go [hunk 1]
```diff
@@ -208,6 +208,8 @@ func (k *KubectlDeployer) readManifests() (manifestList, error) {
 		manifests = append(manifests, manifest)
 	}
 
+	logrus.Debugln(manifests.String())
```
Comment (dlorenc) [inline pkg/skaffold/deploy/kubectl.go]: Nit: could you add a bit of context to these log statements so they're more useful later?
