### PR TITLE
Fix handling of multi stage builds

### LINKED ISSUE #2315: Multi stage build not working in v0.32.0 but work fine in v0.31.0
### Expected behavior
Kaniko (and possibly Docker) targets to work like in v0.31.0

### Actual behavior
Kaniko targets don't work as expected when building and instead gives an error

### Information

- Skaffold version: 0.32.0
- Operating system: Arch 5.1.11-arch1-1-ARCH
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta11
kind: Config

build:
  artifacts:
  - image: registry.gitlab.com/example/example/dump
    context: docker/aws
    kaniko:
      cache: {}
      target: dump
  - image: registry.gitlab.com/example/example/postgis
    context: docker/postgis
    kaniko:
      cache: {}
  - image: registry.gitlab.com/example/example/upload
    context: docker/aws
    kaniko:
      cache: {}
      target: upload
  cluster:
    dockerConfig:
      secretName: kaniko
    namespace: kaniko
    pullSecretName: gitlab-registry
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:latest"

deploy:
  kustomize:
    path: kustomize/overlays/prod

profiles:
- name: dev
  activation:
  - kubeContext: minikube
  build:
    artifacts:
    - image: example/dev/dump
      context: docker/aws
      docker:
        target: dump
    - image: example/dev/postgis
      context: docker/postgis
    - image: example/dev/upload
      context: docker/aws
      docker:
        target: upload
    local: {}
  deploy:
    kustomize:
      path: kustomize/overlays/dev
```

Dockerfile for context `docker/aws`:

```
FROM alpine AS aws
RUN apk add --no-cache \
	python
RUN wget https://s3.amazonaws.com/aws-cli/awscli-bundle.zip \
&& unzip awscli-bundle.zip \
&& ./awscli-bundle/install \
	-b /usr/local/bin/aws \
	-i /usr/local/aws \
&& rm -r awscli-bundle*

FROM aws AS dump
RUN apk add --no-cache \
	jq \
	postgresql-client
COPY --chown=root:root files/dump.sh /scripts/
CMD ["/scripts/dump.sh"]

FROM aws AS upload
COPY --chown=root:root files/upload.sh /scripts/
CMD ["/scripts/upload.sh"]
```

### Steps to reproduce the behavior

1. Run the following file on skaffold v0.32.0
2. Get the following error:

```
skaffold build
Generating tags...
 - registry.gitlab.com/example/example/dump -> registry.gitlab.com/example/example/dump:latest
 - registry.gitlab.com/example/example/postgis -> registry.gitlab.com/example/example/postgis:latest
 - registry.gitlab.com/example/example/upload -> registry.gitlab.com/example/example/upload:latest
Tags generated in 242.837µs
Starting build...
Creating kaniko secret [gitlab-registry]...
Creating docker config secret [kaniko]...
Building [registry.gitlab.com/example/example/dump]...

Complete in 8.165794902s
FATA[0008] build failed: building [registry.gitlab.com/example/example/dump]: kaniko build for [registry.gitlab.com/example/example/dump]: getting dependencies for registry.gitlab.com/example/example/dump: listing copied files: retrieving image config: getting image: UNAUTHORIZED: authentication required; [map[Type:repository Class: Name:library/aws Action:pull]]
```

### PR DESCRIPTION
**Pull request by dgageot**
Fixes #2315

### CODE REVIEW

File: pkg/skaffold/docker/parse.go [hunk 1]
```diff
@@ -185,11 +186,26 @@ func extractCopyCommands(nodes []*parser.Node, onlyLastImage bool, insecureRegis
...
-			if err != nil {
-				return nil, err
+			from := fromInstruction(node)
+			if from.as != "" {
+				// Stage names are case insensitive
+				stages[strings.ToLower(from.as)] = true
+			}
+
+			// If `from` references a previous stage, then the `workdir`
+			// was already changed.
```
Comment (nkubala) [inline pkg/skaffold/docker/parse.go]: is this always true? can I not change the `workdir` in my dockerfile after I copy something from a previous stage?

```dockerfile
COPY --from=prev_stage /app/app.go . # we could be anywhere at this point
WORKDIR /workdir # this contains some script that operates on the file that I just copied
RUN ./script.sh
```

this example might be contrived but isn't it theoretically possible?

Comment (dgageot) [reply pkg/skaffold/docker/parse.go]: Would you have a full Dockerfile that doesn’t pass the tests?

Comment (nkubala) [reply pkg/skaffold/docker/parse.go]: hmm, I tested this Dockerfile and it seems to work. I guess I just got a little confused by this comment, disregard!
