### PR TITLE
fix: add proper artifactOverrides->setValueTemplates conversion when upgrading from v2beta29

### LINKED ISSUE #8321: [regression] Skaffold v1 -> v2 helm `artifactsOverride` usage not automatically updated -> failures
We have a report where a user using Skaffold in CI/CD noted that for their helm chart which does not set a namespace, Skaffold v2 is deploying the helm chart to a different namespace than Skaffold v1 (this actually errors for them in this case).  Still waiting for more repro information and more specific project/skaffold information, will update the issue with that when it is available

### PR DESCRIPTION
**Pull request by aaron-prindle**
fixes #8321

### CODE REVIEW

File: pkg/skaffold/schema/v2beta29/upgrade.go [hunk 1]
```diff
@@ -151,12 +185,112 @@ func upgradeOnePipeline(oldPipeline, newPipeline interface{}) error {
...
+						}
+
+						newsMap[k] = append(newsMap[k], next.JSONPatch{
+							Op:    newsMap[k][i].Op,
+							Path:  newPathModified + ".tag",
+							From:  newsMap[k][i].From,
+							Value: n,
+						})
+
+						if oldPL.Deploy.HelmDeploy.Releases[i].ImageStrategy.HelmConventionConfig.ExplicitRegistry {
```
Comment (renzodavid9) [inline pkg/skaffold/schema/v2beta29/upgrade.go:225]: I think here we should use `idx` instead of `i` as index. `idx` is the index that we get from the json patch path, `i` is the current patch that we are processing, right?

File: pkg/skaffold/schema/v2beta29/upgrade.go [hunk 2]
```diff
@@ -151,12 +185,112 @@ func upgradeOnePipeline(oldPipeline, newPipeline interface{}) error {
...
+							newsMap[k][i] = next.JSONPatch{
+								Op:    newsMap[k][i].Op,
+								Path:  newPathModified + ".repository",
+								From:  newsMap[k][i].From,
+								Value: n,
+							}
+						}
+					} else {
+						// is 'fqn' imageStrategy
+						// replace commonly used image name chars that are illegal helm template chars "/" & "-" with "_"
```
Comment (renzodavid9) [inline pkg/skaffold/schema/v2beta29/upgrade.go:269]: I think this comment shouldn't be here. It is already in line 208, before `validV := pkgutil.SanitizeHelmTemplateValue(old.Value.Node.Value().(string))`

File: pkg/skaffold/schema/v2beta29/upgrade.go [hunk 3]
```diff
@@ -151,12 +185,112 @@ func upgradeOnePipeline(oldPipeline, newPipeline interface{}) error {
...
+				idx, err := strconv.Atoi(strings.Split(old.Path, "/")[4])
+				if err != nil {
+					return err
+				}
+				newPathModified := strings.ReplaceAll(strings.ReplaceAll(old.Path, "/deploy/helm", "/manifests/helm"),
+					"artifactOverrides", "setValueTemplates")
+				if oldPL.Deploy.HelmDeploy != nil {
+					// replace commonly used image name chars that are illegal helm template chars "/" & "-" with "_"
+					validV := pkgutil.SanitizeHelmTemplateValue(old.Value.Node.Value().(string))
+					n := &util.YamlpatchNode{}
```
Comment (gsquared94) [inline pkg/skaffold/schema/v2beta29/upgrade.go:210]: should this be `n := util.YamlpatchNode{}`? Otherwise you seem to be unmarshalling to a double pointer.

File: pkg/skaffold/schema/v2beta29/upgrade.go (hunk 1 above)
Comment (aaron-prindle) [reply pkg/skaffold/schema/v2beta29/upgrade.go:225]: Ah good catch, this was a bad copy paste that happened to work in my testing.  Thanks!

File: pkg/skaffold/schema/v2beta29/upgrade.go (hunk 2 above)
Comment (aaron-prindle) [reply pkg/skaffold/schema/v2beta29/upgrade.go:269]: removed

File: pkg/skaffold/schema/v2beta29/upgrade.go (hunk 3 above)
Comment (aaron-prindle) [reply pkg/skaffold/schema/v2beta29/upgrade.go:209]: Fixed the double pointer usage - instead changed the unmarshalling code to use `n` instead of `&n`

**Comment by aaron-prindle** [comment]
PTAL, addressed comments

**Review by renzodavid9 — APPROVED** [review]

**Review by gsquared94 — APPROVED** [review]
