### PR TITLE
Identify minikube cluster for any profile name

### LINKED ISSUE #3668: enable skaffold to work on minikube profiles
Currently, if `kube-context` is pointing to a minikube profile that is not `minikube`, bunch of things will fail: 
 - we don't detect that this is a minikube profile 
 - even if we would, we'd call `minikube docker-env` without profile 

My recommendation would be:
- decide if the api-server URL is local or not (192.168.0.0/16, 172.0.0.0/24)
- if not local, assume remote  
- if local - check if minikube exists as a binary in the path, if yes: `minikube profile list` and see if any of them match the IP address - if yes, use the profile name for that profile throughout the code

### PR DESCRIPTION
**Pull request by gsquared94**
Fixes #3668

### Description
Currently we need to explicitly specify the minikube profile name as a skaffold flag or limit it to only 'minikube'. This PR introduces several checks for detecting a minikube cluster so that the flag will no longer be required and we can name the cluster anything.
We check:
- The context is 'minikube', or
- ~~The k8s nodes have a minikube label (refer https://github.com/kubernetes/minikube/pull/6717), or~~
- The cluster certificate path is within the `~/.minikube` directory (refer [this](https://github.com/GoogleContainerTools/skaffold/pull/4701#pullrequestreview-474795316) comment), or
- The `minikube profile list` returns a config name matching the context, and
- If the minikube driver is a VM then the node IP should also match the k8s api server url

### CODE REVIEW

File: pkg/skaffold/cluster/minikube.go [hunk 1]
```diff
@@ -0,0 +1,204 @@
...
+	// short circuit if context is 'minikube'
+	if kubeContext == constants.DefaultMinikubeContext {
+		return true, nil
+	}
+	_, err := mkBinaryFunc()
+	if err != nil {
+		return false, nil // minikube binary not found
+	}
+
+	if ok, err := matchNodeLabel(kubeContext); err != nil {
```
Comment (tejal29) [inline pkg/skaffold/cluster/minikube.go:70]: as per the description is matchNoede && matchProfileAndServerURL? or is it a OR?
```
(( The k8s nodes have a minikube label (refer kubernetes/minikube#6717), or
The minikube profile list returns a config name matching the context ) and
If the minikube driver is a VM then the node IP should also match the k8s api server url)
```

File: pkg/skaffold/cluster/minikube.go [hunk 2]
```diff
@@ -0,0 +1,204 @@
...
+	if _, err := os.Stat(filename); os.IsNotExist(err) {
+		return "", fmt.Errorf("unable to find minikube executable. File not found %s", filename)
+	}
+	return filename, nil
+}
+
+func matchNodeLabel(profileName string) (bool, error) {
+	client, err := k8s.Client()
+	if err != nil {
+		return false, fmt.Errorf("getting Kubernetes client: %w", err)
```
Comment (tejal29) [inline pkg/skaffold/cluster/minikube.go:116]: can we just return false or true here and in `matchProfileAndServerURL`. 

That ways, we can simply check
```
def IsMinikube (kubeContext string ) bool {
    .... 
   return matchNodeLabel || matchProfileAndServerURL 
}
```

File: pkg/skaffold/cluster/minikube.go [hunk 3]
```diff
@@ -0,0 +1,204 @@
...
+	MinikubeExec(arg ...string) (*exec.Cmd, error)
+}
+
+type clientImpl struct{}
+
+func getClient() Client {
+	return clientImpl{}
+}
+
+func (clientImpl) IsMinikube(kubeContext string) (bool, error) {
```
Comment (tejal29) [inline pkg/skaffold/cluster/minikube.go:60]: Can we change this to just return bool and log error.

File: pkg/skaffold/cluster/minikube.go [hunk 4]
```diff
@@ -0,0 +1,204 @@
...
+	logrus.Debugf("kubernetes server url: %s", apiServerURL)
+
+	ok, err := matchServerURLFor(kubeContext, apiServerURL)
+	if err != nil {
+		return false, fmt.Errorf("checking minikube node url: %w", err)
+	}
+	return ok, nil
+}
+
+func matchServerURLFor(profileName string, serverURL *url.URL) (bool, error) {
```
Comment (tejal29) [inline pkg/skaffold/cluster/minikube.go:151]: Same here, log error and return only bool.

File: pkg/skaffold/cluster/minikube.go (hunk 1 above)
Comment (gsquared94) [reply pkg/skaffold/cluster/minikube.go:70]: either matching node label or matching profile name(and  server url for some driver types) suffices. The description has an `or` between them.

File: pkg/skaffold/cluster/minikube.go (hunk 3 above)
Comment (gsquared94) [reply pkg/skaffold/cluster/minikube.go]: done

File: pkg/skaffold/cluster/minikube.go (hunk 4 above)
Comment (gsquared94) [reply pkg/skaffold/cluster/minikube.go:153]: I'll end up having a bunch of log messages in these functions. I think I'll leave it as is and log only in the top method

File: pkg/skaffold/cluster/minikube.go (hunk 2 above)
Comment (gsquared94) [reply pkg/skaffold/cluster/minikube.go:118]: I'll end up having a bunch of log messages in these functions. I think I'll leave it as is and log only in the top method

**Comment by gsquared94** [comment]
> few nit changes to simply the code

Hopefully addressed all of them.

File: pkg/skaffold/cluster/minikube.go [hunk 5]
```diff
@@ -0,0 +1,206 @@
...
+func matchNodeLabel(profileName string) (bool, error) {
+	client, err := k8s.Client()
+	if err != nil {
+		return false, fmt.Errorf("getting Kubernetes client: %w", err)
+	}
+	opts := v1.ListOptions{
+		LabelSelector: fmt.Sprintf("minikube.k8s.io/name=%s", profileName),
+		Limit:         100,
+	}
+	l, err := client.CoreV1().Nodes().List(opts)
```
Comment (briandealwis) [inline pkg/skaffold/cluster/minikube.go:124]: This may be a very expensive call if the cluster is far away.

File: pkg/skaffold/cluster/minikube.go [hunk 6]
```diff
@@ -0,0 +1,206 @@
...
+func minikubeBinary() (string, error) {
+	execName := "minikube"
+	if found, _ := util.DetectWSL(); found {
+		execName = "minikube.exe"
+	}
+	filename, err := exec.LookPath(execName)
+	if err != nil {
+		return "", errors.New("unable to find minikube executable. Please add it to PATH environment variable")
+	}
+	if _, err := os.Stat(filename); os.IsNotExist(err) {
```
Comment (briandealwis) [inline pkg/skaffold/cluster/minikube.go:109]: I wonder when this would happen!

File: pkg/skaffold/cluster/minikube.go [hunk 7]
```diff
@@ -0,0 +1,206 @@
...
+	b, err := mkBinaryFunc()
+	if err != nil {
+		return nil, fmt.Errorf("getting minikube executable: %w", err)
+	}
+	return exec.Command(b, arg...), nil
+}
+
+func minikubeBinary() (string, error) {
+	execName := "minikube"
+	if found, _ := util.DetectWSL(); found {
```
[the remark this answers is not in the document]
Comment (gsquared94) [reply pkg/skaffold/cluster/minikube.go:102]: this is actually [existing code](https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/docker/client.go#L181) that I relocated.

File: pkg/skaffold/cluster/minikube.go (hunk 6 above)
Comment (gsquared94) [reply pkg/skaffold/cluster/minikube.go:109]: this is actually [existing code](https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/docker/client.go#L181) that I just relocated. So I didn't try to delve too deeply into the implementation

Comment (gsquared94) [reply pkg/skaffold/cluster/minikube.go:109]: I guess it'd happen if you have the minikube binary in `$PWD` and not on `$PATH`.

Comment (gsquared94) [reply pkg/skaffold/cluster/minikube.go:109]: ya, I think that's the case
```
❯ cat main.go
package main

import (
        "fmt"
        "os"
)

func main() {
        if _, err := os.Stat("minikube"); os.IsNotExist(err) {
                fmt.Println("Not found!")
        } else {
                fmt.Println("Found!")
        }
}
❯ go run main.go
Not found!
❯ touch minikube
❯ go run main.go
Found!
```

File: pkg/skaffold/cluster/minikube.go [hunk 8]
```diff
@@ -0,0 +1,206 @@
...
+	if err != nil {
+		return "", errors.New("unable to find minikube executable. Please add it to PATH environment variable")
+	}
+	if _, err := os.Stat(filename); os.IsNotExist(err) {
+		return "", fmt.Errorf("unable to find minikube executable. File not found %s", filename)
+	}
+	return filename, nil
+}
+
+func matchNodeLabel(profileName string) (bool, error) {
```
[the remark this answers is not in the document]
Comment (gsquared94) [reply pkg/skaffold/cluster/minikube.go:115]: I sort of used it interchangeably since creating a minikube profile `x` creates a kubeContext `x` too.

File: pkg/skaffold/cluster/minikube.go [hunk 9]
```diff
@@ -0,0 +1,206 @@
...
+		return true
+	}
+	_, err := mkBinaryFunc()
+	if err != nil {
+		return false // minikube binary not found
+	}
+
+	if ok, err := matchNodeLabel(kubeContext); err != nil {
+		logrus.Debugf("failed to check minikube node labels: %v", err)
+		return false
```
[the remark this answers is not in the document]
Comment (gsquared94) [reply pkg/skaffold/cluster/minikube.go]: yes, changed.

File: pkg/skaffold/cluster/minikube.go [hunk 10]
```diff
@@ -0,0 +1,206 @@
...
+	} else if ok {
+		logrus.Debugf("Detected minikube cluster for context %s due to matched labels", kubeContext)
+		return true
+	}
+
+	if ok, err := matchProfileAndServerURL(kubeContext); err != nil {
+		logrus.Debugf("failed to match minikube profile: %v", err)
+		return false
```
[the remark this answers is not in the document]
Comment (gsquared94) [reply pkg/skaffold/cluster/minikube.go]: yes, changed.

File: pkg/skaffold/cluster/minikube.go [hunk 11]
```diff
@@ -0,0 +1,206 @@
...
+	} else if ok {
+		logrus.Debugf("Detected minikube cluster for context %s due to matched profile name or server url", kubeContext)
```
[the remark this answers is not in the document]
Comment (gsquared94) [reply pkg/skaffold/cluster/minikube.go]: done

File: pkg/skaffold/cluster/minikube.go [hunk 12]
```diff
@@ -0,0 +1,206 @@
...
+	"github.com/GoogleContainerTools/skaffold/pkg/skaffold/kubernetes/context"
+	"github.com/GoogleContainerTools/skaffold/pkg/skaffold/util"
+)
+
+var GetClient = getClient
+
+// To override during tests
+var (
+	mkBinaryFunc  = minikubeBinary
+	k8sConfigFunc = context.GetRestClientConfig
```
[the remark this answers is not in the document]
Comment (gsquared94) [reply pkg/skaffold/cluster/minikube.go]: done

File: pkg/skaffold/cluster/minikube.go [hunk 13]
```diff
@@ -0,0 +1,206 @@
...
+	_, err := mkBinaryFunc()
+	if err != nil {
+		return false // minikube binary not found
+	}
+
+	if ok, err := matchNodeLabel(kubeContext); err != nil {
+		logrus.Debugf("failed to check minikube node labels: %v", err)
+		return false
+	} else if ok {
+		logrus.Debugf("Detected minikube cluster for context %s due to matched labels", kubeContext)
```
[the remark this answers is not in the document]
Comment (gsquared94) [reply pkg/skaffold/cluster/minikube.go]: done

File: pkg/skaffold/cluster/minikube.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (gsquared94) [reply pkg/skaffold/cluster/minikube.go]: I get your point. Changed everywhere to keep consistent with what the parameter actually represents.

File: pkg/skaffold/cluster/minikube.go [hunk 14]
```diff
@@ -0,0 +1,206 @@
...
+
+type clientImpl struct{}
+
+func getClient() Client {
+	return clientImpl{}
+}
+
+func (clientImpl) IsMinikube(kubeContext string) bool {
+	// short circuit if context is 'minikube'
+	if kubeContext == constants.DefaultMinikubeContext {
```
Comment (nkubala) [inline pkg/skaffold/cluster/minikube.go:62]: i've always wondered if this should be

```golang
if strings.Contains(kubeContext, constants.DefaultMinikubeContext)
```

it wouldn't surprise me if people were creating multiple minikube instances, and naming them `minikube-2` or other random use cases like that. the tradeoff is that this will break users who have remote cluster contexts configured that contain `minikube` in the name....which seems pretty rare. WDYT?

File: pkg/skaffold/cluster/minikube.go [hunk 15]
```diff
@@ -0,0 +1,206 @@
...
+	_, err := minikubeBinaryFunc()
+	if err != nil {
+		logrus.Debugf("Minikube cluster not detected: %v", err)
+		return false // minikube binary not found
+	}
+
+	if ok, err := matchNodeLabel(kubeContext); err != nil {
+		logrus.Debugf("failed to check minikube node labels: %v", err)
+	} else if ok {
+		logrus.Debugf("Minikube cluster detected: context %q nodes have minikube labels", kubeContext)
```
Comment (nkubala) [inline pkg/skaffold/cluster/minikube.go:74]: wondering if these should be `trace` level logs. i think we might be abusing `debug` level logging in skaffold but i'm not really sure

File: pkg/skaffold/cluster/minikube.go [hunk 16]
```diff
@@ -0,0 +1,206 @@
...
+}
+
+func matchNodeLabel(kubeContext string) (bool, error) {
+	client, err := k8s.Client()
+	if err != nil {
+		return false, fmt.Errorf("getting Kubernetes client: %w", err)
+	}
+	opts := v1.ListOptions{
+		LabelSelector: fmt.Sprintf("minikube.k8s.io/name=%s", kubeContext),
+		Limit:         100,
```
Comment (nkubala) [inline pkg/skaffold/cluster/minikube.go:122]: why provide a limit here?

File: pkg/skaffold/cluster/minikube.go [hunk 17]
```diff
@@ -0,0 +1,206 @@
...
+	if err != nil {
+		return false, fmt.Errorf("getting kubernetes config: %w", err)
+	}
+	apiServerURL, _, err := rest.DefaultServerURL(config.Host, config.APIPath, schema.GroupVersion{}, false)
+
+	if err != nil {
+		return false, fmt.Errorf("getting kubernetes server url: %w", err)
+	}
+
+	logrus.Debugf("kubernetes server url: %s", apiServerURL)
```
Comment (nkubala) [inline pkg/skaffold/cluster/minikube.go:144]: this definitely seems like `trace` level

File: pkg/skaffold/cluster/minikube.go [hunk 18]
```diff
@@ -0,0 +1,206 @@
...
+	MinikubeExec(arg ...string) (*exec.Cmd, error)
+}
+
+type clientImpl struct{}
+
+func getClient() Client {
+	return clientImpl{}
+}
+
+func (clientImpl) IsMinikube(kubeContext string) bool {
```
Comment (nkubala) [inline pkg/skaffold/cluster/minikube.go:60]: what if we cached this in the global config? we're already using kube contexts as keys in the config anyway: we could just add an `isMinikube` field and then check here to short circuit this whole logic.

File: pkg/skaffold/cluster/minikube.go (hunk 14 above)
Comment (gsquared94) [reply pkg/skaffold/cluster/minikube.go:63]: After my latest change, it's pretty cheap to check either from the certificate path or the profile names. So I'd rather have false negatives which get caught later than have false positives by making the comparison `contains` over `equals`.

**Comment by gsquared94** [comment]
> Querying the API server is just too expensive — we have some users developing against a cluster on the other side of the world. I thought @tstromberg's suggestion was to load up the kubeconfig files and look at the corresponding cluster's `certificate-authority` to see if it was in ~/.minikube:
> 
> ```
>     certificate-authority: /Users/bdealwis/.minikube/ca.crt
> ```

@briandealwis implemented this approach and removed the label checker. Although the label checker was a very deterministic check and we could have cached the result to not have to run it multiple times. Maybe we can revisit if current set of heuristics don't prove sufficient.

File: pkg/skaffold/cluster/minikube.go (hunk 17 above)
Comment (gsquared94) [reply pkg/skaffold/cluster/minikube.go]: I changed most of the logs to `trace` level

File: pkg/skaffold/cluster/minikube.go (hunk 16 above)
Comment (gsquared94) [reply pkg/skaffold/cluster/minikube.go]: no-op since I removed the code.

File: pkg/skaffold/cluster/minikube.go (hunk 15 above)
Comment (gsquared94) [reply pkg/skaffold/cluster/minikube.go]: I changed most of the logs to trace level

File: pkg/skaffold/cluster/minikube.go (hunk 18 above)
Comment (gsquared94) [reply pkg/skaffold/cluster/minikube.go:61]: The checks are quite inexpensive now so we might not need a cache. I'm slightly leaning towards not adding this to the global config because:
- it could pollute the config if the user has a workflow where say they use a random named minikube cluster each time and delete that afterwards.
- it could get stale- if they create minikube `test` cluster, delete that and later create kind or gke cluster called `test`
### 🤷🏾‍♂️

File: pkg/skaffold/cluster/minikube.go [hunk 19]
```diff
@@ -0,0 +1,215 @@
...
+			if serverURL.Host == fmt.Sprintf("%s:%d", n.IP, n.Port) {
+				return true, nil
+			}
+		}
+	}
+	return false, nil
+}
+
+// minikubePath returns the path to the user's minikube dir
+func minikubePath() string {
```
Comment (gsquared94) [inline pkg/skaffold/cluster/minikube.go:186]: copied this function from [minikube](https://github.com/kubernetes/minikube/blob/master/pkg/minikube/localpath/localpath.go#L41)

File: pkg/skaffold/cluster/minikube.go [hunk 20]
```diff
@@ -0,0 +1,215 @@
...
+func (clientImpl) IsMinikube(kubeContext string) bool {
+	// short circuit if context is 'minikube'
+	if kubeContext == constants.DefaultMinikubeContext {
+		return true
+	}
+	_, err := minikubeBinaryFunc()
+	if err != nil {
+		logrus.Tracef("Minikube cluster not detected: %v", err)
+		return false
+	}
```
Comment (tejal29) [inline pkg/skaffold/cluster/minikube.go:70]:
```suggestion
	if _, err := minikubeBinaryFunc();  err != nil {
		logrus.Tracef("Minikube cluster not detected: %v", err)
		return false
	}
```

File: pkg/skaffold/cluster/minikube.go [hunk 21]
```diff
@@ -0,0 +1,215 @@
...
+
+	ok, err := matchServerURLFor(kubeContext, apiServerURL)
+	if err != nil {
+		return false, fmt.Errorf("checking minikube node url: %w", err)
+	}
+	return ok, nil
+}
+
+func matchServerURLFor(kubeContext string, serverURL *url.URL) (bool, error) {
+	cmd, err := minikubeExec("profile", "list", "-o", "json")
```
Comment (tejal29) [inline pkg/skaffold/cluster/minikube.go:151]: the error here should never be encountered, since we first check is executable is present in L66.
I feel this function has too many branches. 
WDYT about removing "minikubeExec" from all `matchServerURLFor`, `matchProfileAndServerURL` and pass it in the function signature.
currently, all the above functions are not used anywhere else.

File: pkg/skaffold/cluster/minikube.go [hunk 22]
```diff
@@ -0,0 +1,215 @@
...
+	if err != nil {
+		return false, fmt.Errorf("executing minikube command: %w", err)
```
Comment (tejal29) [inline pkg/skaffold/cluster/minikube.go:153]: this err is because minikube binary could not be found. consider changing this to "could not fetch minikube binary ..."

File: pkg/skaffold/cluster/minikube.go [hunk 23]
```diff
@@ -0,0 +1,215 @@
...
+	}
+
+	out, err := util.RunCmdOut(cmd)
+	if err != nil {
+		return false, fmt.Errorf("getting minikube profiles: %w", err)
+	}
+
+	var data data
+	if err = json.Unmarshal(out, &data); err != nil {
+		log.Fatal(fmt.Errorf("failed to unmarshal data: %w", err))
```
Comment (tejal29) [inline pkg/skaffold/cluster/minikube.go:163]: could not unmarshal `minikube profile list` output.
Fatal will cause the code to stop. 
Did you mean use to trace instead?

File: pkg/skaffold/cluster/minikube.go [hunk 24]
```diff
@@ -0,0 +1,215 @@
...
+	}
+
+	for _, v := range data.Valid {
+		if v.Config.Name != kubeContext {
+			continue
+		}
+
+		if v.Config.Driver != "hyperkit" && v.Config.Driver != "virtualbox" {
```
Comment (tejal29) [inline pkg/skaffold/cluster/minikube.go:171]: convert this to constants

File: pkg/skaffold/cluster/minikube.go (hunk 23 above)
Comment (gsquared94) [reply pkg/skaffold/cluster/minikube.go:163]: my bad, definitely intended to use trace

File: pkg/skaffold/cluster/minikube.go (hunk 22 above)
Comment (gsquared94) [reply pkg/skaffold/cluster/minikube.go]: Done

File: pkg/skaffold/cluster/minikube.go (hunk 24 above)
Comment (gsquared94) [reply pkg/skaffold/cluster/minikube.go]: Done

File: pkg/skaffold/cluster/minikube.go (hunk 23 above)
Comment (gsquared94) [reply pkg/skaffold/cluster/minikube.go]: Done

File: pkg/skaffold/cluster/minikube.go (hunk 21 above)
Comment (gsquared94) [reply pkg/skaffold/cluster/minikube.go]: removed `err` object instead

File: pkg/skaffold/cluster/minikube.go (hunk 18 above)
Comment (briandealwis) [reply pkg/skaffold/cluster/minikube.go:65]: Maybe we should have a KubeContext type instead of passing around string.

File: pkg/skaffold/cluster/minikube.go [hunk 25]
```diff
@@ -0,0 +1,214 @@
...
+// minikubePath returns the path to the user's minikube dir
+func minikubePath() string {
+	minikubeHomeEnv := os.Getenv("MINIKUBE_HOME")
+	if minikubeHomeEnv == "" {
+		return filepath.Join(homedir.HomeDir(), ".minikube")
+	}
+	if filepath.Base(minikubeHomeEnv) == ".minikube" {
+		return minikubeHomeEnv
+	}
+	return filepath.Join(minikubeHomeEnv, ".minikube")
```
Comment (briandealwis) [inline pkg/skaffold/cluster/minikube.go:193]: This doesn't seem right: MINIKUBE_HOME doesn't have to contain a `.minikube` directory.  At least their code [uses patterns like the following to access data](https://github.com/kubernetes/minikube/blob/1a19f8f0a5368f4081a8b3f6f10b2635e043b690/cmd/minikube/cmd/ssh-key.go#L35):
```
filepath.Join(localpath.MiniPath(), "machines", cc.Name, "id_rsa")
```

File: pkg/skaffold/cluster/minikube.go [hunk 26]
```diff
@@ -0,0 +1,214 @@
...
+
+func (clientImpl) IsMinikube(kubeContext string) bool {
+	// short circuit if context is 'minikube'
+	if kubeContext == constants.DefaultMinikubeContext {
+		return true
+	}
+	if _, err := minikubeBinaryFunc(); err != nil {
+		logrus.Tracef("Minikube cluster not detected: %v", err)
+		return false
+	}
```
Comment (briandealwis) [inline pkg/skaffold/cluster/minikube.go:73]: Should this check be performed first?  If we can't find the minikube binary, then it doesn't really matter if `context == 'minikube'`, since we can't run `minikube docker-env`?

File: pkg/skaffold/cluster/minikube.go [hunk 27]
```diff
@@ -0,0 +1,214 @@
...
+
+	if ok, err := matchClusterCertPath(kubeContext); err != nil {
```
Comment (briandealwis) [inline pkg/skaffold/cluster/minikube.go:75]: Should we just fetch the cluster-info and pass it into `matchClusterCertPath()` and into `matchProfileAndServerURL()`?

File: pkg/skaffold/cluster/minikube.go [hunk 28]
```diff
@@ -0,0 +1,214 @@
...
+		if v.Config.Driver != HyperKit && v.Config.Driver != VirtualBox {
+			// Since node IPs don't match server API for other drivers we assume profile name match is enough.
+			// TODO: Revisit once https://github.com/kubernetes/minikube/issues/6642 is fixed
+			return true, nil
+		}
+		for _, n := range v.Config.Nodes {
+			if serverURL.Host == fmt.Sprintf("%s:%d", n.IP, n.Port) {
+				return true, nil
+			}
+		}
```
Comment (briandealwis) [inline pkg/skaffold/cluster/minikube.go:179]: It feels to me like this is inverted:
  - we should check if any of the nodes match the cluster server _regardless of the driver type_.  That way we're insulated from whenever kubernetes/minikube#6642 is fixed.  (At least, my understanding is that the cluster-info's server IP won't match the node IP — my minikube is 127.0.0.1:32780 but the profile lists 172.17.0.2)
  - then see if the minikube profile name matches the kubeContext — this is a heuristic, but unless the user has manually edited their kubeconfig files, it should be true

File: pkg/skaffold/cluster/minikube.go (hunk 25 above)
Comment (gsquared94) [reply pkg/skaffold/cluster/minikube.go:193]: It seems to be there to safeguard against someone erroneously adding it so they don't get `~/.minikube/.minikube/`.

File: pkg/skaffold/cluster/minikube.go (hunk 21 above)
Comment (tejal29) [reply pkg/skaffold/cluster/minikube.go]: Instead of removing the `err` object, can you pass the `minikubeExec` path found it in L66 and avoid calling `minikubeExec` at all.

File: pkg/skaffold/cluster/minikube.go [hunk 29]
```diff
@@ -0,0 +1,214 @@
...
+
+	ok, err := matchServerURLFor(kubeContext, apiServerURL)
+	if err != nil {
+		return false, fmt.Errorf("checking minikube node url: %w", err)
+	}
+	return ok, nil
+}
+
+func matchServerURLFor(kubeContext string, serverURL *url.URL) (bool, error) {
+	cmd, _ := minikubeExec("profile", "list", "-o", "json")
```
[the remark this answers is not in the document]
Comment (gsquared94) [reply pkg/skaffold/cluster/minikube.go:154]: yes, we already validate that the binary exists by this point. Creating a `Cmd` doesn't return any other error

File: pkg/skaffold/cluster/minikube.go [hunk 30]
```diff
@@ -0,0 +1,214 @@
...
+	return clientImpl{}
+}
+
+func (clientImpl) IsMinikube(kubeContext string) bool {
+	// short circuit if context is 'minikube'
+	if kubeContext == constants.DefaultMinikubeContext {
+		return true
+	}
+	if _, err := minikubeBinaryFunc(); err != nil {
+		logrus.Tracef("Minikube cluster not detected: %v", err)
```
[the remark this answers is not in the document]
Comment (gsquared94) [reply pkg/skaffold/cluster/minikube.go:71]: ya `minikubeBinaryFunc` errors out only when the binary isn't found and all errors are already prefaced with `unable to find minikube executable...`

File: pkg/skaffold/cluster/minikube.go [hunk 31]
```diff
@@ -0,0 +1,214 @@
...
+		return false, fmt.Errorf("getting minikube profiles: %w", err)
+	}
+
+	var data data
+	if err = json.Unmarshal(out, &data); err != nil {
+		return false, fmt.Errorf("failed to unmarshal data: %w", err)
+	}
+
+	for _, v := range data.Valid {
+		if v.Config.Name != kubeContext {
```
[the remark this answers is not in the document]
Comment (gsquared94) [reply pkg/skaffold/cluster/minikube.go:166]: I'd argue assuming `minikube` context matches a minikube cluster is a much bigger assumption. Since `minikube create cluster` is the obvious minikube cluster creation command which defaults to a `minikube` context we've made that assumption in the current code. So `minikube create cluster -p test` (which is the obvious command to create a named cluster) would default to a `test` context and we should be able to make the same assumption here?

[the remark this answers is not in the document]
Comment (gsquared94) [reply pkg/skaffold/cluster/minikube.go:166]: Obviously your other comment is correct that I should make this check after checking for the URLs first.

File: pkg/skaffold/cluster/minikube.go (hunk 27 above)
Comment (gsquared94) [reply pkg/skaffold/cluster/minikube.go:75]: Fixed in https://github.com/GoogleContainerTools/skaffold/pull/4742

File: pkg/skaffold/cluster/minikube.go (hunk 28 above)
Comment (gsquared94) [reply pkg/skaffold/cluster/minikube.go:179]: Fixed in https://github.com/GoogleContainerTools/skaffold/pull/4742

File: pkg/skaffold/cluster/minikube.go (hunk 26 above)
Comment (gsquared94) [reply pkg/skaffold/cluster/minikube.go:73]: Fixed in https://github.com/GoogleContainerTools/skaffold/pull/4742

**Comment by gsquared94** [comment]
> A I noticed a few issues that should be fixed.

Fixed them in follow up PR https://github.com/GoogleContainerTools/skaffold/pull/4742

File: pkg/skaffold/cluster/minikube.go (hunk 31 above)
[the remark this answers is not in the document]
Comment (briandealwis) [reply pkg/skaffold/cluster/minikube.go:166]: It's very unlikely that I might create a k3d or kind cluster called "minikube".  It's not unlikely that I might create a k3d or kind cluster named "test".

[the remark this answers is not in the document]
Comment (gsquared94) [reply pkg/skaffold/cluster/minikube.go:166]: Valid point. I'll remove the name check entirely then and just leave the URL checks.

File: pkg/skaffold/cluster/minikube.go (hunk 18 above)
Comment (gsquared94) [reply pkg/skaffold/cluster/minikube.go:65]: created https://github.com/GoogleContainerTools/skaffold/issues/4751
