### PR TITLE
Fixes #5404: Skaffold configs downloaded from a url can define remote config dependencies

### LINKED ISSUE #5404: Providing a url to `-f` flag doesn't work with remote configs
### Expected behavior
Run:
```bash
skaffold run -f https://raw.githubusercontent.com/gsquared94/skaffold-remote-configs-demo/main/skaffold.yaml
```
Skaffold uses the url provided as the main config and downloads any remote configs specified in that file.
### Actual behavior
Skaffold fails with the error:
```
parsing skaffold config: could not find skaffold config /Users/gaghosh/https:/raw.githubusercontent.com/gsquared94/skaffold-remote-configs-demo/main/skaffold.yaml that is referenced as a dependency in config /Users/gaghosh/https:/raw.githubusercontent.com/gsquared94/skaffold-remote-configs-demo/main/skaffold.yaml
```
### Information

- Skaffold version: v1.20.0
- Operating system: ...
- Contents of skaffold.yaml:
https://raw.githubusercontent.com/gsquared94/skaffold-remote-configs-demo/main/skaffold.yaml

### PR DESCRIPTION
**Pull request by gsquared94**
Fixes #5404 

This PR makes two changes:
- Fix the config parsing logic that was erroneously checking that a dependency config file exists on disk even if it's a URL. 
- Add missing check that multiple configs in the same file cannot have the same name.

### CODE REVIEW

File: cmd/skaffold/app/cmd/parse_config.go [hunk 1]
```diff
@@ -108,11 +108,18 @@ func getConfigs(cfgOpts configOpts, opts config.SkaffoldOptions, r *record) ([]*
 func processEachConfig(config *latest.SkaffoldConfig, cfgOpts configOpts, opts config.SkaffoldOptions, r *record, index int) ([]*latest.SkaffoldConfig, error) {
 	// check that the same config name isn't repeated in multiple files.
 	if config.Metadata.Name != "" {
-		prevConfig, found := r.configNameToFile[config.Metadata.Name]
-		if found && prevConfig != cfgOpts.file {
-			return nil, fmt.Errorf("skaffold config named %q found in multiple files: %q and %q", config.Metadata.Name, prevConfig, cfgOpts.file)
+		prev, found := r.configNameToFile[config.Metadata.Name]
+		if found {
+			sl := strings.SplitN(prev, "@", 2) // map value is always formatted as `file_name@config_index`
```
Comment (briandealwis) [inline cmd/skaffold/app/cmd/parse_config.go:113]: This overloading of `configNameToFile` seems error-prone (`@` is a valid character in file names).  It also seems unnecessary since it's entirely our code: we could just have the map take `string` &rarr; `struct { name, index }`.  But more to the point, we don't seem to use this index anywhere else, so couldn't this search-for-duplicates just use a local variable to maintain its state?

And maybe this search-for-duplicates should be done separately?

File: cmd/skaffold/app/cmd/parse_config.go [hunk 2]
```diff
@@ -108,11 +108,18 @@ func getConfigs(cfgOpts configOpts, opts config.SkaffoldOptions, r *record) ([]*
 func processEachConfig(config *latest.SkaffoldConfig, cfgOpts configOpts, opts config.SkaffoldOptions, r *record, index int) ([]*latest.SkaffoldConfig, error) {
```
Comment (briandealwis) [inline cmd/skaffold/app/cmd/parse_config.go:108]: Would be helpful to describe what `index` represents here.  (And `it's` &rarr; `its`)

File: cmd/skaffold/app/cmd/parse_config.go [hunk 3]
```diff
@@ -108,11 +108,18 @@ func getConfigs(cfgOpts configOpts, opts config.SkaffoldOptions, r *record) ([]*
...
+		prev, found := r.configNameToFile[config.Metadata.Name]
+		if found {
+			sl := strings.SplitN(prev, "@", 2) // map value is always formatted as `file_name@config_index`
+			prevConfig, prevIndex := sl[0], sl[1]
+			if prevConfig != cfgOpts.file {
+				return nil, fmt.Errorf("skaffold config named %q found in multiple files: %q and %q", config.Metadata.Name, prevConfig, cfgOpts.file)
+			}
+			if prevIndex != fmt.Sprint(index) {
+				return nil, fmt.Errorf("multiple skaffold configs named %q found in file %q", config.Metadata.Name, cfgOpts.file)
+			}
```
Comment (briandealwis) [inline cmd/skaffold/app/cmd/parse_config.go:120]: Can duplicate references not be handled by `ParseConfigAndUpgrade()`?  So all we'd need is a set of seen config names?

File: cmd/skaffold/app/cmd/parse_config.go [hunk 4]
```diff
@@ -193,15 +200,17 @@ func processEachDependency(d latest.ConfigDependency, cfgOpts configOpts, opts c
...
 		path = cfgOpts.file
 	}
-	fi, err := os.Stat(path)
-	if err != nil {
-		if os.IsNotExist(errors.Unwrap(err)) {
-			return nil, fmt.Errorf("could not find skaffold config %s that is referenced as a dependency in config %s", path, cfgOpts.file)
+	if !util.IsURL(path) {
+		fi, err := os.Stat(path)
+		if err != nil {
+			if os.IsNotExist(errors.Unwrap(err)) {
```
Comment (briandealwis) [inline cmd/skaffold/app/cmd/parse_config.go:206]: The unwrap isn't correct: it's possible the `ErrNoExist` is actually a wrapped error.  See the example at
https://golang.org/pkg/os/#IsNotExist

File: cmd/skaffold/app/cmd/parse_config.go [hunk 5]
```diff
@@ -193,15 +200,17 @@ func processEachDependency(d latest.ConfigDependency, cfgOpts configOpts, opts c
...
+		}
+		if fi.IsDir() {
+			path = filepath.Join(path, "skaffold.yaml")
 		}
-		return nil, fmt.Errorf("parsing dependencies for skaffold config %s: %w", cfgOpts.file, err)
-	}
-	if fi.IsDir() {
-		path = filepath.Join(path, "skaffold.yaml")
 	}
 	cfgOpts.isDependency = cfgOpts.isDependency || path != cfgOpts.file
```
Comment (briandealwis) [inline cmd/skaffold/app/cmd/parse_config.go:215]: This line is a bit puzzling and warrants a comment as I'm not sure how this situation can arise.

File: cmd/skaffold/app/cmd/parse_config_test.go [hunk 6]
```diff
@@ -419,8 +441,11 @@ requires:
 				Profiles:            test.profiles,
 			})
 
-			t.CheckDeepEqual(test.err, err, cmp.Comparer(errorsComparer))
-			t.CheckErrorAndDeepEqual(test.err != nil, err, test.expected, cfgs)
+			if test.err != "" {
+				t.CheckDeepEqual(errors.New(strings.ReplaceAll(test.err, "WORK_DIR", wd)), err, cmp.Comparer(errorsComparer))
+			} else {
+				t.CheckDeepEqual(test.expected, cfgs)
+			}
```
Comment (briandealwis) [inline cmd/skaffold/app/cmd/parse_config_test.go:448]: Might be easier to have an `duplicateError` type, and instead use a function to check the correctness of the error.

Better yet: create an error-code for this situation and test that error code.  This should be reported upwards.

File: cmd/skaffold/app/cmd/parse_config.go (hunk 3 above)
Comment (gsquared94) [reply cmd/skaffold/app/cmd/parse_config.go]: It can't exactly be inside `ParseConfigAndUpgrade()` since that works with `VersionedConfig` which doesn't have any method like `GetName`. To make that change I'd have to modify every version of the skaffold config to satisfy that interface. But you're right in that I can do this check upfront. Moved.

File: cmd/skaffold/app/cmd/parse_config.go (hunk 2 above)
Comment (gsquared94) [reply cmd/skaffold/app/cmd/parse_config.go:122]: fixed typo; added description

File: cmd/skaffold/app/cmd/parse_config.go (hunk 1 above)
Comment (gsquared94) [reply cmd/skaffold/app/cmd/parse_config.go]: don't know what I was doing here 🤦🏽‍♂️. Removed.

Comment (gsquared94) [reply cmd/skaffold/app/cmd/parse_config.go]: We can't effectively maintain all info in a local variable since we also want to print out the file names that cause the conflict.

File: cmd/skaffold/app/cmd/parse_config.go (hunk 4 above)
Comment (gsquared94) [reply cmd/skaffold/app/cmd/parse_config.go:213]: This is a weird one. It was existing code so I didn't mess around with it. It's calculating that the `FileNotFound` error from `ReadConfiguration` is wrapped exactly once in `ParseConfig`. So it unwraps exactly once to get the underlying error. 🤦🏽‍♂️ 

I'll convert this to a concrete error type.

Comment (briandealwis) [reply cmd/skaffold/app/cmd/parse_config.go:213]: The [code for `IsNotExist` notes](https://golang.org/src/os/error.go?s=3221:3252#L86):
> New code should use `errors.Is(err, os.ErrNotExist)`

`errors.Is()` will unwrap the error sequentially.

Comment (gsquared94) [reply cmd/skaffold/app/cmd/parse_config.go]: oh, got it. Fixed

File: cmd/skaffold/app/cmd/parse_config_test.go (hunk 6 above)
Comment (gsquared94) [reply cmd/skaffold/app/cmd/parse_config_test.go:448]: I will make this change in fixing https://github.com/GoogleContainerTools/skaffold/issues/5412

File: cmd/skaffold/app/cmd/parse_config.go (hunk 5 above)
Comment (gsquared94) [reply cmd/skaffold/app/cmd/parse_config.go:225]: added

File: cmd/skaffold/app/cmd/parse_config.go [hunk 7]
```diff
@@ -92,6 +92,19 @@ func getConfigs(cfgOpts configOpts, opts config.SkaffoldOptions, r *record) ([]*
 	}
 	logrus.Debugf("parsed %d configs from configuration file %s", len(parsed), cfgOpts.file)
 
+	// validate that config names are unique if specified
+	seen := make(map[string]bool)
+	for _, cfg := range parsed {
+		cfgName := cfg.(*latest.SkaffoldConfig).Metadata.Name
```
Comment (briandealwis) [inline cmd/skaffold/app/cmd/parse_config.go:98]: Maybe we should have a `ConfigName()` method on `VersionedConfig`?

File: cmd/skaffold/app/cmd/parse_config.go (hunk 5 above)
Comment (briandealwis) [reply cmd/skaffold/app/cmd/parse_config.go:225]: What's previous and current?  Oh!  Is configOpts from the config that required `d` as a dependency?  That was not clear.

File: cmd/skaffold/app/cmd/parse_config_test.go (hunk 6 above)
Comment (briandealwis) [reply cmd/skaffold/app/cmd/parse_config_test.go:448]: The tests are failing as you're getting windows path separators.  Maybe you need to replace `/` &rarr; `\` too in the WORKDIR references.

File: cmd/skaffold/app/cmd/parse_config.go [hunk 8]
```diff
@@ -92,6 +92,19 @@ func getConfigs(cfgOpts configOpts, opts config.SkaffoldOptions, r *record) ([]*
...
+		if cfgName == "" {
+			continue
+		}
+		if seen[cfgName] {
+			return nil, fmt.Errorf("multiple skaffold configs named %q found in file %q", cfgName, cfgOpts.file)
```
Comment (briandealwis) [inline cmd/skaffold/app/cmd/parse_config.go:103]: Maybe `seen` should be a map of `name` &rarr; file?  Then you could include at least two of the file nams.

**Review by briandealwis — APPROVED** [review]
LGTM once the tests pass on Windows.
