### PR TITLE
When pulling images and authentication fails, first try anonymous pull

### LINKED ISSUE #4447: Fetching the gcr.io/buildpacks/builder:v1 image should not require being logged in to gcloud
macOS 10.15.5

In https://github.com/GoogleCloudPlatform/cloud-code-samples/tree/master/java/java-hello-world with a modified `skaffold.yaml` that uses buildpacks as the builder (shown below), I tried to run `skaffold dev` and got an error fetching the `gcr.io/buildpacks/builder:v1` image due to not being logged in to `gcloud`. I expected this to not require being logged in.

From @dgageot: `Skaffold is trying to use gcloud auth automatically without the user having to configure it. But it’s maybe too aggressive`

```
$ skaffold version
v1.12.0
$ gcloud version
Google Cloud SDK 289.0.0
alpha 2020.02.25
app-engine-java 1.9.79
app-engine-python 1.9.90
beta 2020.02.25
bq 2.0.56
cloud-datastore-emulator 2.1.0
core 2020.04.10
gsutil 4.49
minikube
skaffold
$ gcloud auth list

No credentialed accounts.

To login, run:
  $ gcloud auth login `ACCOUNT`
apiVersion: skaffold/v2beta5

$ pwd
/Users/michihara/Code/cloud-code-samples/java/java-hello-world
$ cat skaffold.yaml
apiVersion: skaffold/v2beta5
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: java-hello-world
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/**.yaml
$ skaffold dev
Listing files to watch...
 - java-hello-world
Generating tags...
 - java-hello-world -> java-hello-world:latest
Checking cache...
 - java-hello-world: Not found. Building
Found [docker-desktop] context, using local docker daemon.
Building [java-hello-world]...
ERROR: (gcloud.auth.docker-helper) You do not currently have an active account selected.
Please run:

  $ gcloud auth login

to obtain new credentials, or if you have already logged in with a
different account:

  $ gcloud config set account ACCOUNT

to select an already authenticated account to use.
exiting dev mode because first build failed: couldn't build "java-hello-world": failed to fetch builder image 'gcr.io/buildpacks/builder:v1': error getting credentials - err: exit status 1, out: ``
```

### PR DESCRIPTION
**Pull request by dgageot**
Fixes #4447

Signed-off-by: David Gageot <david@gageot.net>

### CODE REVIEW

**Comment by dgageot** [comment]
Not sure we can remove this output. Anyways, the config is still funky and
that shows it to the user. Wdyt?

**Comment by briandealwis** [comment]
I was hoping the following would work (try as public, and then with auth), except it fails with my private repository on Docker Hub when I'm logged out: 

```diff
--- pkg/skaffold/docker/image.go
+++ pkg/skaffold/docker/image.go
@@ -312,17 +312,11 @@ func (l *localDaemon) isAlreadyPushed(ctx context.Context, ref, registryAuth str
 
 // Pull pulls an image reference from a registry.
 func (l *localDaemon) Pull(ctx context.Context, out io.Writer, ref string) error {
-       // Eargerly create credentials.
-       registryAuth, err := l.encodedRegistryAuth(ctx, DefaultAuthHelper, ref)
-       // Let's ignore the error because maybe the image is public
-       // and can be pulled without credentials.
-
        rc, err := l.apiClient.ImagePull(ctx, ref, types.ImagePullOptions{
-               RegistryAuth: registryAuth,
                PrivilegeFunc: func() (string, error) {
                        // If the first pull is unauthorized, retry without ignoring the
                        // authentication error.
-                       return registryAuth, err
+                       return l.encodedRegistryAuth(ctx, DefaultAuthHelper, ref)
                },
        })
        if err != nil {
```

The failure happens in `ImagePull()` the `tryImageCreate()` returns an `github.com/docker/docker/errdefs.ErrNotFound` error, not an `ErrUnauthorized`.

**Comment by dgageot** [comment]
Yes, that’s what i tried first.

File: pkg/skaffold/docker/image.go [hunk 1]
```diff
@@ -312,13 +312,18 @@ func (l *localDaemon) isAlreadyPushed(ctx context.Context, ref, registryAuth str
...
-	}
+	// Let's ignore the error because maybe the image is public
+	// and can be pulled without credentials.
 
 	rc, err := l.apiClient.ImagePull(ctx, ref, types.ImagePullOptions{
 		RegistryAuth: registryAuth,
+		PrivilegeFunc: func() (string, error) {
+			// If the first pull is unauthorized, retry without ignoring the
+			// authentication error.
+			return registryAuth, err
```
Comment (briandealwis) [inline pkg/skaffold/docker/image.go:325]: So AFAICT this doesn't *retry*: 
  1. If `encodedRegistryAuth()` returns an error, this anonymous function returns that error causing `ImagePull()` to short-circuit and immediately return that error — it doesn't retry. 
  2. If `encodedRegistryAuth()` had been able to obtain `registryAuth` without an error, then `ImagePull()` will just retry with the auth and get the same unauthorized error.

If `encodedRegistryAuth()` did encounter an error, then `registryAuth` is an empty string.  Maybe it would make sense have this anonymous function instead do `return "", err`?  So that
  - if `encodedRegistryAuth()` had encountered an error, then we've tried the no-auth case (since `registryAuth == ""`, and so we use `ImagePull()`'s short-circuiting to return the auth error
  - if `encodedRegistryAuth()` didn't encounter an error (so `err == nil`), but our credential was seeming invalid (unauthorized), then we'll retry with no auth

```suggestion
			// The first pull is unauthorized. There are two situations:
			//   1. if `encodedRegistryAuth()` errored, then `registryAuth == ""` and so we've
			//     tried an anonymous pull which has failed.  So return the original error from
			//     `encodedRegistryAuth()`.
			//   2. If `encodedRegistryAuth()` succeeded (so `err == nil`), then our credential was rejected, so
			//     return "" to retry as an anonymous pull.
			return "", err
```

Comment (briandealwis) [reply pkg/skaffold/docker/image.go:325]: Alternatively we could invert the logic of this function and try a pull with no auth first, and then retrying with auth if that fails?  It's an additional round-trip, and counter to what Docker does.  Though it is the process Jib uses.

Comment (chanseokoh) [reply pkg/skaffold/docker/image.go:325]: This may be complete irrelevant, but just FYI, GCR and Docker Hub have different behaviors for public images.

- GCR: public images in are completely public. No strings attached.
- Docker Hub: it always returns "401 Unauthorized" first, and it wants you to always go through the bearer auth token authentication. Of course, for public images, you don't have to send any credentials when talking to `auth.docker.io/token` to get a token. I don't know if go-containerregistry or whatever in Skaffold is automatically taking care of this under the hood though. Here's an example when accessing `openjdk` (i.e., `GET https://registry-1.docker.io/v2/library/openjdk/manifests/8`).
```
CONFIG: -------------- RESPONSE --------------
HTTP/1.1 401 Unauthorized
...
Www-Authenticate: Bearer realm="https://auth.docker.io/token",service="registry.docker.io",scope="repository:library/openjdk:pull"
```

**Comment by briandealwis** [comment]
This came up again in Sean's friction log.  We can suppress the output with `CLOUDSDK_CORE_VERBOSITY=none` and the error message is still meaningful enough for the user to figure out what's going on:
```diff
diff --git examples/buildpacks/skaffold.yaml examples/buildpacks/skaffold.yaml
index d78c0a329..4938c8f14 100644
--- examples/buildpacks/skaffold.yaml
+++ examples/buildpacks/skaffold.yaml
@@ -4,7 +4,7 @@ build:
   artifacts:
   - image: skaffold-buildpacks
     buildpacks:
-      builder: "gcr.io/buildpacks/builder:v1"
+      builder: "gcr.io/<private-project>/first"
       env:
       - GOPROXY={{.GOPROXY}}
     sync:
```

```console
$  CLOUDSDK_CORE_VERBOSITY=none skaffold build
Generating tags...
 - skaffold-buildpacks -> skaffold-buildpacks:v1.13.1-50-g456977b80-dirty
Checking cache...
 - skaffold-buildpacks: Not found. Building
Found [minikube] context, using local docker daemon.
Building [skaffold-buildpacks]...
couldn't build "skaffold-buildpacks": failed to fetch builder image 'gcr.io/<private-project>/first:latest': pulling image from repository: Error response from daemon: unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication
```
