### PR TITLE
Fix syncing for Jib

### LINKED ISSUE #1921: Sync does not work for Skaffold-Jib
For Maven and Gradle, `src/main/resources` is a standard location for placing static files.  But attempting to enable sync files from `src/main/resources` fails with Skaffold+Jib. 
```diff
+    sync:
+      'src/main/resources/**': '/app/resources'
```

### Expected behavior

The `README.md` file should be sync'd.

### Actual behavior

I have `~/go/src/github.com/GoogleContainerTools/skaffold` linked to `~/Projects/GPE/repo-skaffold`, and normally do my builds from `~/Projects/GPE/repo-skaffold`.

With `skaffold dev`, a change to a file with a sync rule will fail with:
```
FATA[0094] calling final callback: sync: intersecting sync map and added, modified files: changed file /Users/bsd/go/src/github.com/GoogleContainerTools/skaffold/examples/jib/src/main/resources can't be found relative to context .: Rel: can't make /Users/bsd/go/src/github.com/GoogleContainerTools/skaffold/examples/jib/src/main/resources relative to . 
```

### Information

The Jib builder's `GetDependencies` works by invoking an internal Jib build goal (`_skaffold-files` on Maven, `_jibSkaffoldFiles` on Gradle) that returns the build files and directories to source files.  The Jib Builder then expands the source directories to return the contents.

In digging into the problem, there are two issues:
  1. When expanding the paths returned by Jib's `skaffold-files`, `getDependencies()` returns both files and directories.  In the example below, the binding returns the directory `src/main/resources` and its contents `src/main/resources/README`.  But the directory doesn't match a sync-rule and so the attempt to sync fails.  
  1. The Jib's `skaffold-files` goal returns absolute canonical paths (where symlinks are expanded), which can be a problem when the context is actually in a symlinked directory (either itself or the parent) as neither `filepath.Abs()` nor `filepath.Rel()` expand symlinks.  So the attempt [in `sync.go`'s `intersect()` to relativize the paths fails](https://github.com/GoogleContainerTools/skaffold/blob/b1dce640bd28bbf80f4097c5eb04ae3531f11628/pkg/skaffold/sync/sync.go#L142).

### Steps to reproduce the behavior

1. `mkdir examples/jib/src/main/resources`
2. `cp README.md examples/jib/src/main/resources/`
3. Apply the following diff to add a sync rule.
4. `cd examples/jib; skaffold dev` and then make a change to `src/main/resources/README.md`

```diff
--- a/examples/jib/skaffold.yaml
+++ b/examples/jib/skaffold.yaml
@@ -4,6 +4,8 @@ build:
   artifacts:
   - image: gcr.io/k8s-skaffold/skaffold-jib
     jibMaven: {}
+    sync:
+      'src/main/resources/**': '/app/resources'
 
 # optional profile to run the jib build on Google Cloud Build
 profiles:
```

### Proposed Fix

Fixing Problem 1 is straightforward: fix Jib's [`getDependencies()`](https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/jib/jib.go#L70) to only return files.

I can fix Problem 2 by processing changing Jib's `getDependencies()` to apply `filepath.EvalSymlinks()` to the context directory prior to relativizing the files.  But the code in `sync.go`'s `intersect()` looks like it's trying to handle absolute files anyways.  Perhaps I should push this expansion here?

https://github.com/GoogleContainerTools/skaffold/blob/b1dce640bd28bbf80f4097c5eb04ae3531f11628/pkg/skaffold/sync/sync.go#L135-L142

### PR DESCRIPTION
**Pull request by briandealwis**
Syncing with a Jib project doesn't work (#1921):
  - jib.go's `getDependencies()` returns both files and directories.  A directory `a/b/c` doesn't match a sync-rule with a glob `a/b/c/**` and so changing file `a/b/c/README` causes sync to fail.
  - The Skaffold-Jib binding calls out to Maven-Jib and Gradle-Jib to return paths files and directories.  These are normally _canonical paths_ where symlinks are expanded, and so the paths may not match the specified workspace which is usually relative to the `skaffold.yaml` like ".".

This PR fixes Jib's `getDependencies()` to relativize paths to the given workspace or the canonicalized workspace.  It also filters out directories.

Fixes #1921

### CODE REVIEW

**Comment by briandealwis** [comment]
I should note that sync with Jib requires building against something like `openjdk` as sync relies on the presence of `tar`, which doesn't exist in the `gcr.io/distroless/java` (Jib's default image).

**Comment by briandealwis** [comment]
🤦‍♂️ WIndows paths

File: pkg/skaffold/jib/jib.go [hunk 1]
```diff
@@ -78,3 +100,18 @@ func getDependencies(cmd *exec.Cmd) ([]string, error) {
 	sort.Strings(deps)
 	return deps, nil
 }
+
+// relativize tries to make path relative to the root location(s)
```
Comment (corneliusweig) [inline pkg/skaffold/jib/jib.go]:
```suggestion
// relativize tries to make path relative below one of the root locations
```

File: pkg/skaffold/jib/jib.go [hunk 2]
```diff
@@ -17,22 +17,34 @@ limitations under the License.
...
 )
 
-func getDependencies(cmd *exec.Cmd) ([]string, error) {
+func getDependencies(workspace string, cmd *exec.Cmd) ([]string, error) {
 	stdout, err := util.RunCmdOut(cmd)
 	if err != nil {
 		return nil, err
 	}
 
+	// Jib's dependencies are absolute, and usually canonicalized, so must canonicalize the workspace
```
Comment (corneliusweig) [inline pkg/skaffold/jib/jib.go]: I take it that "usually" means that they are not always canonicalized? Or do you simply want to cover that possibility `relativize`?

File: pkg/skaffold/jib/jib.go [hunk 3]
```diff
@@ -60,14 +72,24 @@ func getDependencies(cmd *exec.Cmd) ([]string, error) {
 		}
 
 		if !info.IsDir() {
+			// try to relativize the path
+			if relative, err := relativize(dep, workspace, canonicalWorkspace); err == nil {
```
Comment (corneliusweig) [inline pkg/skaffold/jib/jib.go]: I wonder if `dep` is most of the time canonical here. If so, you could swap `workspace` and `canonicalWorkspace` so that the good case comes first.

File: pkg/skaffold/jib/jib.go [hunk 4]
```diff
@@ -78,3 +100,18 @@ func getDependencies(cmd *exec.Cmd) ([]string, error) {
 	sort.Strings(deps)
 	return deps, nil
 }
+
+// relativize tries to make path relative to the root location(s)
+func relativize(path string, roots ...string) (string, error) {
+	if !filepath.IsAbs(path) {
+		return path, nil
+	}
+	dotDotSlash := fmt.Sprintf("..%c", filepath.Separator)
```
Comment (corneliusweig) [inline pkg/skaffold/jib/jib.go]: I wonder if `dotDotSlash` can be put in a const variable?

**Comment by corneliusweig** [comment]
> I should note that sync with Jib requires building against something like `openjdk` as sync relies on the presence of `tar`, which doesn't exist in the `gcr.io/distroless/java` (Jib's default image).

@briandealwis Do you think there's a chance to get a distroless variant with tar? Currently, this affects _all_ copy operations into the k8s container (also see https://github.com/GoogleContainerTools/skaffold/issues/1814#issuecomment-473654285)

**Comment by briandealwis** [comment]
Distroless doesn't include a shell, so even if distroless included tar, any use would have to explicitly specify a full path to the executable.

File: pkg/skaffold/jib/jib.go (hunk 4 above)
Comment (briandealwis) [reply pkg/skaffold/jib/jib.go]: I had hoped so too but the compiler complained

File: pkg/skaffold/jib/jib.go [hunk 5]
```diff
@@ -60,14 +72,24 @@ func getDependencies(cmd *exec.Cmd) ([]string, error) {
...
 			continue
 		}
 
 		if err = godirwalk.Walk(dep, &godirwalk.Options{
 			Unsorted: true,
 			Callback: func(path string, _ *godirwalk.Dirent) error {
-				deps = append(deps, path)
+				if info, err := os.Stat(path); err == nil && !info.IsDir() {
+					// try to relativize the path
+					if relative, err := relativize(path, workspace, canonicalWorkspace); err == nil {
```
[the remark this answers is not in the document]
Comment (briandealwis) [reply pkg/skaffold/jib/jib.go]: It's still valid to return an absolute path: Skaffold-Jib also returns references to SNAPSHOT jars found in the user's local repository (e.g., under ~/.m2/repository).

File: pkg/skaffold/jib/jib.go (hunk 2 above)
Comment (briandealwis) [reply pkg/skaffold/jib/jib.go]: To cover that possibility: the Jib `skaffold-files` goal simply reports builder-provided information.  So it's best not to assume anything, really.

File: pkg/skaffold/jib/jib.go (hunk 3 above)
Comment (briandealwis) [reply pkg/skaffold/jib/jib.go]: Good idea.

File: pkg/skaffold/jib/jib.go (hunk 4 above)
Comment (briandealwis) [reply pkg/skaffold/jib/jib.go]: Aha: `const dotDotSlash = ".." + string(filepath.Separator)`

**Comment by briandealwis** [comment]
Huh, `filepath.IsAbs("\a")` is false on Windows.

**Comment by corneliusweig** [comment]
> Huh, `filepath.IsAbs("\a")` is false on Windows.

:scream:

**Comment by briandealwis** [comment]
PTAL @balopat

File: pkg/skaffold/jib/jib.go [hunk 6]
```diff
@@ -60,14 +72,24 @@ func getDependencies(cmd *exec.Cmd) ([]string, error) {
 		}
 
 		if !info.IsDir() {
+			// try to relativize the path
+			if relative, err := relativize(dep, workspaceRoots...); err == nil {
```
Comment (balopat) [inline pkg/skaffold/jib/jib.go]: we should handle the relativization errors here

File: pkg/skaffold/jib/jib.go (hunk 2 above)
Comment (balopat) [reply pkg/skaffold/jib/jib.go]: Frankly, I don't understand this comment yet either :) What do we exactly mean by "canonicalization"? Everything relative? Everything absolute? Symlinks resolved to absolute? Not sure I'm following.

File: pkg/skaffold/jib/jib.go [hunk 7]
```diff
@@ -78,3 +100,33 @@ func getDependencies(cmd *exec.Cmd) ([]string, error) {
...
 	return deps, nil
 }
+
+// calculateRoots returns a list of possible symlink-expanded paths
+func calculateRoots(path string) ([]string, error) {
+	path, err := filepath.Abs(path)
+	if err != nil {
+		return nil, errors.Wrapf(err, "unable to resolve %s", path)
+	}
+	canonical, err := filepath.EvalSymlinks(path)
```
Comment (balopat) [inline pkg/skaffold/jib/jib.go]: based on my understanding reading `EvalSymlinks`'s godoc, it will leave relative paths as relative. This should be fine right?

File: pkg/skaffold/jib/jib.go [hunk 8]
```diff
@@ -78,3 +100,33 @@ func getDependencies(cmd *exec.Cmd) ([]string, error) {
...
+	if err != nil {
+		return nil, errors.Wrapf(err, "unable to canonicalize workspace %s", path)
+	}
+	if path == canonical {
+		return []string{path}, nil
+	}
+	return []string{canonical, path}, nil
```
Comment (balopat) [inline pkg/skaffold/jib/jib.go]: Why are we returning both the symlink expanded and the non expanded version?

File: pkg/skaffold/jib/jib.go [hunk 9]
```diff
@@ -78,3 +100,33 @@ func getDependencies(cmd *exec.Cmd) ([]string, error) {
...
+}
+
+// relativize tries to make path relative to one of the given roots
+func relativize(path string, roots ...string) (string, error) {
+	if !filepath.IsAbs(path) {
+		return path, nil
+	}
+	for _, root := range roots {
+		// check that the path can be made relative and is contained (since `filepath.Rel("/a", "/b") => "../b"`)
+		if rel, err := filepath.Rel(root, path); err == nil && !strings.HasPrefix(rel, dotDotSlash) {
```
Comment (balopat) [inline pkg/skaffold/jib/jib.go]: I think we should handle the errors here explicitly as well - it should be easier to debug errors.

Comment (balopat) [reply pkg/skaffold/jib/jib.go]: Maybe concatenate them, if there are more. There are max two roots as I'm reading this...

File: pkg/skaffold/jib/jib.go [hunk 10]
```diff
@@ -78,3 +100,33 @@ func getDependencies(cmd *exec.Cmd) ([]string, error) {
...
+	}
+	if path == canonical {
+		return []string{path}, nil
+	}
+	return []string{canonical, path}, nil
+}
+
+// relativize tries to make path relative to one of the given roots
+func relativize(path string, roots ...string) (string, error) {
+	if !filepath.IsAbs(path) {
```
Comment (balopat) [inline pkg/skaffold/jib/jib.go]: Why are we assuming here that if the path is relative, it is relative to the right root? Can we assume that?

Comment (balopat) [inline pkg/skaffold/jib/jib.go]: Why are we assuming here that if the path is relative, it is relative to the right root? Can we assume that?

Comment (balopat) [inline pkg/skaffold/jib/jib.go]: Why are we assuming here that if the path is relative, it is relative to the right root? Can we assume that?

Comment (balopat) [inline pkg/skaffold/jib/jib.go]: Why are we assuming here that if the path is relative, it is relative to the right root? Can we assume that?

File: pkg/skaffold/jib/jib.go (hunk 8 above)
Comment (briandealwis) [reply pkg/skaffold/jib/jib.go]: This is @corneliusweig's [question](https://github.com/GoogleContainerTools/skaffold/pull/1926/files/4d799283170dde3fa008587382ae7a1a43a291fd#r272745633) too: basically Jib's `skaffold-files` goal just returns information provided from the Maven/Gradle.  These files *seem* to be absolute and canonical, but the docs don't actually guarantee that.  Expanding symlinks for *every* file seems like it could be expensive, so I instead expand the workspace so we can try comparing the expanded and unexpanded workspace paths as prefixes.

File: pkg/skaffold/jib/jib.go (hunk 9 above)
Comment (briandealwis) [reply pkg/skaffold/jib/jib.go]: These aren't real errors: it just means that the file could not be made relative, which usually means that `path` is already relative.  (Can also happen on Windows if they're on different volumes.)

**Comment by briandealwis** [comment]
> I'll take that on

I meant separately.

**Comment by corneliusweig** [comment]
> > I'll take that on
> 
> I meant separately.

Keep in mind that the sync config will be changed soon.
