### PR TITLE
fix: Quotes in dockerfiles env vars break copy dependency checks

### LINKED ISSUE #6762: Quotes in Dockerfile environment variables, used in COPY statements, break dependency checks
### Expected behavior
A double quoted value assigned to an environment variable in the Dockerfile, such as
```
DIRNAME="some_dir"
```
shouldn't cause the file dependency checks to fail when examining the Dockerfile's COPY commands.  (this occurs when running `skaffold build` or `skaffold dev`)

So for instance (in the Dockerfile):
```
DIRNAME="some_dir"
COPY src/$DIRNAME  /app/$DIRNAME
```
is getting interpreted as:
```
src/"some_dir" 
```
(note the double quotes above in the directory name)
and is manifesting in the error of:
```
getting hash for artifact "my_artifact": getting dependencies for "my_artifact": file pattern [src/"some_dir"] must match at least one file
```

### Actual behavior
i'm thinking that double quotes aren't technically a problem for this kind of glob operation, so likely there's an issue with how they're being processed in skaffold.

### Information

- Skaffold version: v1.33.1
- Operating system: Ubuntu Linux 20.04
- Installed via: curl script

### PR DESCRIPTION
**Pull request by kadern0**
Fixes #6762
Signed-off-by: Pablo Caderno <kaderno@gmail.com>

**Description**

Fixes the issue with quoted variables and "COPY" commands.

Before:
```
skaffold build
Generating tags...
 - bert -> bert:151b8d3-dirty
 - ernie -> ernie:151b8d3
Checking cache...
 - bert: Error checking cache.
getting hash for artifact "bert": getting dependencies for "bert": file pattern [./src/"some_dir"] must match at least one file
```
After:
```
skaffold build
Generating tags...
 - bert -> bert:151b8d3-dirty
 - ernie -> ernie:151b8d3
Checking cache...
 - bert: Not found. Building
 - ernie: Found Locally
Starting build...
Found [ed-ks2] context, using local docker daemon.
Building [bert]...
Sending build context to Docker daemon  7.168kB
Step 1/20 : FROM golang:1.15 as builder
 ---> 40349a2425ef
Step 2/20 : COPY main.go .
 ---> Using cache
 ---> 5bcddb464805
Step 3/20 : ARG SKAFFOLD_GO_GCFLAGS
 ---> Using cache
 ---> 0fe720d5c3d6
Step 4/20 : RUN go build -gcflags="${SKAFFOLD_GO_GCFLAGS}" -o /app main.go
 ---> Using cache
 ---> b0fa60be1cbd
Step 5/20 : FROM alpine:3.10
 ---> e7b300aee9f9
Step 6/20 : ENV MY_NAME="John Doe" MY_DOG=Rex\ The\ Dog     MY_CAT=fluffy
 ---> Using cache
 ---> 0a651a254ade
Step 7/20 : ENV GOTRACEBACK=single
 ---> Using cache
 ---> 0588ba733bf7
Step 8/20 : ENV DIR2=some_dir
 ---> Using cache
 ---> ac1901e9b83c
Step 9/20 : ENV DIRNAME="some_dir"
 ---> Using cache
 ---> 0a5beef983fa
Step 10/20 : ENV NOBREAK="asdf'asdf"
 ---> Running in 48d6824c02ad
 ---> 17df958a420a
Step 11/20 : COPY $NOBREAK .
 ---> 1fcafb39acb1
Step 12/20 : COPY a .
 ---> 428b63829342
Step 13/20 : COPY src/ .
 ---> 4e55fcb5d5c5
Step 14/20 : COPY ./src/$DIR2 /tmp/
 ---> 59df6382498d
Step 15/20 : COPY ./src/$DIRNAME  /tmp/
 ---> 4d182523b4f3
Step 16/20 : COPY ./src/$MY_NAME /tmp/
 ---> a4ef10e6fe6b
Step 17/20 : COPY ./src/$MY_DOG /tmp/
 ---> 043c8a3062a3
Step 18/20 : COPY ./src/$MY_CAT /tmp/
 ---> 8c1d5aa9b2c7
Step 19/20 : CMD ["./app"]
 ---> Running in 7e5a5b6a9c9d
 ---> 45c93161726d
Step 20/20 : COPY --from=builder /app .
 ---> 29276d711899
Successfully built 29276d711899
Successfully tagged bert:151b8d3-dirty
```

### CODE REVIEW

**Review by aaron-prindle — APPROVED** [review]
LGTM

**Comment by kadern0** [comment]
Hi @aaron-prindle thank you very much. I noticed an estrange behavior when testing this change and wanted to ask someone before opening an issue. When building docker containers, `skaffold build` fails if you try to copy and empty dir. Is there any reason for `skaffold build` to work different than  `docker build` ?

**Comment by aaron-prindle** [comment]
> Hi @aaron-prindle thank you very much. I noticed an estrange behavior when testing this change and wanted to ask someone before opening an issue. When building docker containers, `skaffold build` fails if you try to copy and empty dir. Is there any reason for `skaffold build` to work different than `docker build` ?

@kadern0 can you give a small sample app/setup to reproduce the issue you mentioned?  `skaffold build` should not be different than docker build ideally but because of how env vars, etc. are passed there might be some discrepancies.  I will hold off on merging this until I can look into the issue you mentioned

File: pkg/skaffold/docker/parse.go [hunk 1]
```diff
@@ -262,7 +262,7 @@ func extractCopyCommands(ctx context.Context, nodes []*parser.Node, onlyLastImag
 		case command.Env:
 			// one env command may define multiple variables
 			for node := node.Next; node != nil && node.Next != nil; node = node.Next.Next {
-				envs = append(envs, fmt.Sprintf("%s=%s", node.Value, node.Next.Value))
+				envs = append(envs, fmt.Sprintf("%s=%s", node.Value, unquote(node.Next.Value)))
```
Comment (aaron-prindle) [inline pkg/skaffold/docker/parse.go:265]: nit: can you add a test case in parse_test.go that fails with the original issue (eg: env vars are quoted incorrectly)

Comment (kadern0) [reply pkg/skaffold/docker/parse.go:265]: The original issue is that skaffold fails when env vars are quoted correctly though. (It works as expected with wrongly quoted vars -> `unable to stream build output: failed to process "\"asdfsafd": unexpected end of statement while looking for matching double-quote`)

Comment (kadern0) [reply pkg/skaffold/docker/parse.go:265]: The problem occurs when trying to verify whether that directory exists, here:
https://github.com/GoogleContainerTools/skaffold/blob/fc060164fcb42d7d648df5ed5125571fde572e3f/pkg/skaffold/docker/parse.go#L170-L173

But AFAIK, this will happen at run time so in this case I think it would make more sense adding a directory and then a COPY statement to one of the tests like this one instead: https://github.com/GoogleContainerTools/skaffold/blob/fc060164fcb42d7d648df5ed5125571fde572e3f/pkg/skaffold/initializer/testdata/init/hello/Dockerfile 

What do you think?

**Comment by kadern0** [comment]
> > I noticed an estrange behavior when testing this change and wanted to ask someone before opening an issue. When building docker containers, `skaffold build` fails if you try to copy and empty dir. Is there any reason for `skaffold build` to work different than `docker build` ?
> 
> @kadern0 can you give a small sample-app/set-of-steps to reproduce the issue you mentioned above? I can investigate more thoroughly if you have an app setup I can use to repro. `skaffold build` should not be different than `docker build` ideally but because of how env vars, config, etc. are passed around there might be some discrepancies. I will hold off on merging this until I can look into the issue you mentioned

Steps to reproduce:
cd into `skaffold/examples/docker-deploy/bert/`
```
mkdir test
# add following copy to Dockerfile
COPY test .
cd ..
skaffold build
Generating tags...
 - bert -> bert:151b8d3-dirty
 - ernie -> ernie:151b8d3
Checking cache...
 - bert: Not found. Building
 - ernie: Found Locally
Starting build...
Found [ed-ks2] context, using local docker daemon.
Building [bert]...
Sending build context to Docker daemon  3.072kB
Step 1/9 : FROM golang:1.15 as builder
 ---> 40349a2425ef
Step 2/9 : COPY main.go .
 ---> Using cache
 ---> 5bcddb464805
Step 3/9 : ARG SKAFFOLD_GO_GCFLAGS
 ---> Using cache
 ---> 0fe720d5c3d6
Step 4/9 : RUN go build -gcflags="${SKAFFOLD_GO_GCFLAGS}" -o /app main.go
 ---> Using cache
 ---> b0fa60be1cbd
Step 5/9 : FROM alpine:3.10
 ---> e7b300aee9f9
Step 6/9 : ENV GOTRACEBACK=single
 ---> Using cache
 ---> e850d4805844
Step 7/9 : COPY test .
unable to stream build output: COPY failed: file not found in build context or excluded by .dockerignore: stat test: file does not exist
```
Verify directory exists:
```
ls bert/
Dockerfile   main.go   src   test
```

Now, add a single file to the directory and try again:
```
touch bert/test/testfile
 skaffold build
Generating tags...
 - bert -> bert:151b8d3-dirty
 - ernie -> ernie:151b8d3
Checking cache...
 - bert: Not found. Building
 - ernie: Found Locally
Starting build...
Found [ed-ks2] context, using local docker daemon.
Building [bert]...
Sending build context to Docker daemon  3.584kB
Step 1/9 : FROM golang:1.15 as builder
 ---> 40349a2425ef
Step 2/9 : COPY main.go .
 ---> Using cache
 ---> 5bcddb464805
Step 3/9 : ARG SKAFFOLD_GO_GCFLAGS
 ---> Using cache
 ---> 0fe720d5c3d6
Step 4/9 : RUN go build -gcflags="${SKAFFOLD_GO_GCFLAGS}" -o /app main.go
 ---> Using cache
 ---> b0fa60be1cbd
Step 5/9 : FROM alpine:3.10
 ---> e7b300aee9f9
Step 6/9 : ENV GOTRACEBACK=single
 ---> Using cache
 ---> e850d4805844
Step 7/9 : COPY test .
 ---> 4c26c1bf872e
Step 8/9 : CMD ["./app"]
 ---> Running in 6c98a27efeca
 ---> 41b29bf39f5b
Step 9/9 : COPY --from=builder /app .
 ---> 69557d373998
Successfully built 69557d373998
Successfully tagged bert:151b8d3-dirty
```
It fails when the directory is empty.

**Comment by aaron-prindle** [comment]
@kadern0 the docker COPY empty directory appears to be a current bug in skaffold that is not related to this change.  I attempted reproducing this error w/ various version of skaffold and this has been a skaffold bug from at least v1.32.0 onward:
```
aprindle@aprindle ~/skaffold/examples/docker-deploy  [main]$ skaffold-v1.32.0 version
v1.32.0
aprindle@aprindle ~/skaffold/examples/docker-deploy  [main]$ skaffold-v1.32.0 build
Generating tags...
 - bert -> bert:v1.34.0-17-gfc060164f-dirty
 - ernie -> ernie:v1.34.0-17-gfc060164f
Checking cache...
 - bert: Not found. Building
 - ernie: Not found. Building
Starting build...
Found [gke_aprindle-test-clusters_us-central1-c_aprindle-test-cluster] context, using local docker daemon.
Building [ernie]...
Sending build context to Docker daemon  3.072kB
Step 1/8 : FROM golang:1.15 as builder
 ---> e5b4455acc93
Step 2/8 : COPY main.go .
 ---> Using cache
 ---> 65d183d24c2f
Step 3/8 : ARG SKAFFOLD_GO_GCFLAGS
 ---> Using cache
 ---> 003f0f9d95c9
Step 4/8 : RUN go build -gcflags="${SKAFFOLD_GO_GCFLAGS}" -o /app main.go
 ---> Using cache
 ---> a8061498c281
Step 5/8 : FROM alpine:3.10
 ---> e7b300aee9f9
Step 6/8 : ENV GOTRACEBACK=single
 ---> Using cache
 ---> 109d7e69f5af
Step 7/8 : CMD ["./app"]
 ---> Using cache
 ---> 42e6a70e8c09
Step 8/8 : COPY --from=builder /app .
 ---> Using cache
 ---> d3b3cb4efc2c
Successfully built d3b3cb4efc2c
Successfully tagged ernie:v1.34.0-17-gfc060164f
Building [bert]...
Sending build context to Docker daemon  3.072kB
Step 1/9 : FROM golang:1.15 as builder
 ---> e5b4455acc93
Step 2/9 : COPY main.go .
 ---> Using cache
 ---> 20335ca8b486
Step 3/9 : ARG SKAFFOLD_GO_GCFLAGS
 ---> Using cache
 ---> 4ef0d41d4e3e
Step 4/9 : RUN go build -gcflags="${SKAFFOLD_GO_GCFLAGS}" -o /app main.go
 ---> Using cache
 ---> fbe49a368a25
Step 5/9 : FROM alpine:3.10
 ---> e7b300aee9f9
Step 6/9 : ENV GOTRACEBACK=single
 ---> Using cache
 ---> 109d7e69f5af
Step 7/9 : CMD ["./app"]
 ---> Using cache
 ---> 42e6a70e8c09
Step 8/9 : COPY --from=builder /app .
 ---> Using cache
 ---> 3d90026f7448
Step 9/9 : COPY test .
unable to stream build output: COPY failed: file not found in build context or excluded by .dockerignore: stat test: file does not exist
```

```
aprindle@aprindle ~/skaffold/examples/docker-deploy  [main]$ skaffold-v1.33.0 version
v1.33.0
aprindle@aprindle ~/skaffold/examples/docker-deploy  [main]$ skaffold-v1.33.0 build
...  # ommitting middle of logs
unable to stream build output: COPY failed: file not found in build context or excluded by .dockerignore: stat test: file does not exist

```

File: pkg/skaffold/docker/parse.go (hunk 1 above)
Comment (aaron-prindle) [reply pkg/skaffold/docker/parse.go:265]: Yes you are correct, sorry about my suggestion before.  If possible if you could add a test like the one you suggested that would be great to make sure that this fix works as expected and we don't break this functionality with future changes.

Comment (kadern0) [reply pkg/skaffold/docker/parse.go:265]: Just added a test. Let me know if it's not how it should be.

**Comment by aaron-prindle** [comment]
Merging, thanks for all of your work here @kadern0!
