### PR TITLE
Fix kind 0.6.0 support

### LINKED ISSUE #3296: skaffold not using local docker images with latest kind cluster v0.6.0
### Expected behavior
skaffold config set -k $(kubectl config current-context) local-cluster true set config to use local kind cluster
Skaffold Dev --port-forward should deploy and run containers from local docker images. Skaffold is not using local environment as latest version of kind now does not add the @kind to the context. 

### Actual behavior
Skaffold looks public "docker.io/library/ location. 
### Information

- Skaffold version: v1.0.0-103-g2c03a11b
- Operating system: ubuntu 18.04
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2alpha1
kind: Config
build:
 artifacts:
  - image: cloudsolutions-nginx
    context: ../../../source
    docker: 
      dockerfile: docker/frontend/build/Dockerfile
  - image: cloudsolutions-mysql
    context: ../../../.devcontainer/database
    docker:
      dockerfile: Dockerfile
  - image: cloudsolutions-backend
    context: ../../../source
    docker: 
      dockerfile: docker/backend/Dockerfile

#Address defined in skaffold.yaml not available in v1
portForward:
- resourceType: deployment
  resourceName: craft
  namespace: default
  port: 80
  address: 0.0.0.0
  localPort: 80

deploy:
  kustomize: {}

profiles:
- name: local
  build: 
    local: 
      push: false
  activation:
    - kubeContext: kubernetes-admin@kind
      command: dev, run
```

### Steps to reproduce the behavior

1. use latest kind v0.6.0 start cluster
2. set skaffold to use local-cluster true
3. Run skaffold dev --port-forward

### PR DESCRIPTION
**Pull request by dgageot**
+ Support new kind naming scheme
 + Properly load docker images into the current kind cluster. This used to fail if the cluster had a non-default name

Fixes #3296

### CODE REVIEW

File: pkg/skaffold/config/util_test.go [hunk 1]
```diff
@@ -259,3 +259,48 @@ func TestIsUpdateCheckEnabled(t *testing.T) {
...
 	}
 }
+
+func TestIsDefaultLocal(t *testing.T) {
+	tests := []struct {
+		context       string
+		expectedLocal bool
+	}{
+		{context: "kind-other", expectedLocal: true},
+		{context: "kind@kind", expectedLocal: true},
```
Comment (briandealwis) [inline pkg/skaffold/config/util_test.go]: Worth having a check for `kind@blah` &rarr; `false`?

File: pkg/skaffold/config/util_test.go [hunk 2]
```diff
@@ -259,3 +259,48 @@ func TestIsUpdateCheckEnabled(t *testing.T) {
...
+
+			t.CheckDeepEqual(test.expectedLocal, local)
+		})
+	}
+}
+
+func TestIsKindCluster(t *testing.T) {
+	tests := []struct {
+		context        string
+		expecteName    string
```
Comment (briandealwis) [inline pkg/skaffold/config/util_test.go]: Missing `d`: `expectedName`

File: pkg/skaffold/config/util.go [hunk 3]
```diff
@@ -183,14 +183,27 @@ func GetInsecureRegistries(configFile string) ([]string, error) {
...
+	isKind, _ := IsKindCluster(kubeContext)
+	return isKind
 }
 
-func IsKindCluster(kubeContext string) bool {
-	return strings.HasSuffix(kubeContext, "@kind")
+// IsKindCluster checks that the given `kubeContext` is talking to `kind`.
+// It also returns the name of the `kind` cluster.
+func IsKindCluster(kubeContext string) (bool, string) {
+	switch {
```
Comment (briandealwis) [inline pkg/skaffold/config/util.go]: Could you add some doc here about kind naming prefixes with their version?  When nobody is using < 0.6 then can we remove the `kind-` prefixing?

**Comment by dgageot** [comment]
Thanks @briandealwis, I've addressed your feedback!

File: pkg/skaffold/runner/kind_test.go [hunk 4]
```diff
@@ -41,19 +42,21 @@ func TestLoadImagesInKindNodes(t *testing.T) {
 	}{
 		{
 			description: "load image",
+			kindCluster: "kind",
 			built:       []build.Artifact{{Tag: "tag1"}},
 			deployed:    []build.Artifact{{Tag: "tag1"}},
 			commands: testutil.
 				CmdRunOut("kubectl --context kubecontext --namespace namespace get nodes -ojsonpath='{@.items[*].status.images[*].names[*]}'", "").
-				AndRun("kind load docker-image tag1"),
+				AndRun("kind load docker-image --name kind tag1"),
```
Comment (tejal29) [inline pkg/skaffold/runner/kind_test.go]: is `kind` the cluster name here?

**Comment by dgageot** [comment]
@balopat I've updated the docs

File: docs/content/en/docs/environment/local-cluster.md [hunk 5]
```diff
@@ -5,15 +5,38 @@ weight: 60
...
+For any other name, Skaffold assumes that the cluster is remote and that images
+have to be pushed.
+
+ [`minikube`]: https://github.com/kubernetes/minikube/
+ [`Docker Desktop`]: https://www.docker.com/products/docker-desktop
+ [`kind`]: https://github.com/kubernetes-sigs/kind
+
+### Manual override
+
+For non-standard local setups, such as a custom `minikube` profile,
```
Comment (balopat) [inline docs/content/en/docs/environment/local-cluster.md]: I would just add one more thing here: 

```suggestion

As `kind` clusters currently manual override is not possible, the context name has to comply with the above patterns for Skaffold to work locally with `kind`.

For some non-standard local setups, such as a custom `minikube` profile, 
```
