### PR TITLE
Don’t replace existing labels

### LINKED ISSUE #3718: labels break some deployments: `selector` does not match template `labels`
Skaffold labels are breaking certain deploys.

``` 
 - Error from server (Invalid): error when applying patch:
 - {"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"apps/v1\",\"kind\":\"Deployment\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"webhook\",\"app.kubernetes.io/instance\":\"cert-manager\",\"app.kubernetes.io/managed-by\":\"skaffold-v1.4.0\",\"app.kubernetes.io/name\":\"webhook\",\"helm.sh/chart\":\"cert-manager-v0.13.0\",\"skaffold.dev/builder\":\"local\",\"skaffold.dev/cleanup\":\"true\",\"skaffold.dev/deployer\":\"kustomize\",\"skaffold.dev/docker-api-version\":\"1.40\",\"skaffold.dev/profile.0\":\"testCluster\",\"skaffold.dev/run-id\":\"ea787d57-32f1-4d78-90d6-df128aea74fd\",\"skaffold.dev/tag-policy\":\"git-commit\",\"skaffold.dev/tail\":\"true\"},\"name\":\"cert-manager-webhook\",\"namespace\":\"cert-manager\"},\"spec\":{\"replicas\":1,\"selector\":{\"matchLabels\":{\"app\":\"webhook\",\"app.kubernetes.io/instance\":\"cert-manager\",\"app.kubernetes.io/managed-by\":\"Tiller\",\"app.kubernetes.io/name\":\"webhook\"}},\"template\":{\"metadata\":{\"annotations\":null,\"labels\":{\"app\":\"webhook\",\"app.kubernetes.io/instance\":\"cert-manager\",\"app.kubernetes.io/managed-by\":\"skaffold-v1.4.0\",\"app.kubernetes.io/name\":\"webhook\",\"helm.sh/chart\":\"cert-manager-v0.13.0\",\"skaffold.dev/builder\":\"local\",\"skaffold.dev/cleanup\":\"true\",\"skaffold.dev/deployer\":\"kustomize\",\"skaffold.dev/docker-api-version\":\"1.40\",\"skaffold.dev/profile.0\":\"testCluster\",\"skaffold.dev/run-id\":\"ea787d57-32f1-4d78-90d6-df128aea74fd\",\"skaffold.dev/tag-policy\":\"git-commit\",\"skaffold.dev/tail\":\"true\"}},\"spec\":{\"containers\":[{\"args\":[\"--v=2\",\"--secure-port=10250\",\"--tls-cert-file=/certs/tls.crt\",\"--tls-private-key-file=/certs/tls.key\"],\"env\":[{\"name\":\"POD_NAMESPACE\",\"valueFrom\":{\"fieldRef\":{\"fieldPath\":\"metadata.namespace\"}}}],\"image\":\"quay.io/jetstack/cert-manager-webhook:v0.13.0\",\"imagePullPolicy\":\"IfNotPresent\",\"livenessProbe\":{\"httpGet\":{\"path\":\"/livez\",\"port\":6080,\"scheme\":\"HTTP\"}},\"name\":\"cert-manager\",\"readinessProbe\":{\"httpGet\":{\"path\":\"/healthz\",\"port\":6080,\"scheme\":\"HTTP\"}},\"resources\":{},\"volumeMounts\":[{\"mountPath\":\"/certs\",\"name\":\"certs\"}]}],\"serviceAccountName\":\"cert-manager-webhook\",\"volumes\":[{\"name\":\"certs\",\"secret\":{\"secretName\":\"cert-manager-webhook-tls\"}}]}}}}\n"},"labels":{"app.kubernetes.io/managed-by":"skaffold-v1.4.0","skaffold.dev/builder":"local","skaffold.dev/cleanup":"true","skaffold.dev/deployer":"kustomize","skaffold.dev/docker-api-version":"1.40","skaffold.dev/profile.0":"testCluster","skaffold.dev/run-id":"ea787d57-32f1-4d78-90d6-df128aea74fd","skaffold.dev/tag-policy":"git-commit","skaffold.dev/tail":"true"}},"spec":{"template":{"metadata":{"annotations":null,"labels":{"app.kubernetes.io/managed-by":"skaffold-v1.4.0","skaffold.dev/builder":"local","skaffold.dev/cleanup":"true","skaffold.dev/deployer":"kustomize","skaffold.dev/docker-api-version":"1.40","skaffold.dev/profile.0":"testCluster","skaffold.dev/run-id":"ea787d57-32f1-4d78-90d6-df128aea74fd","skaffold.dev/tag-policy":"git-commit","skaffold.dev/tail":"true"}}}}}
 - to:
- Resource: "apps/v1, Resource=deployments", GroupVersionKind: "apps/v1, Kind=Deployment"
 - Name: "cert-manager-webhook", Namespace: "cert-manager"
 - Object: &{map["apiVersion":"apps/v1" "kind":"Deployment" "metadata":map["annotations":map["deployment.kubernetes.io/revision":"1" "kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"apps/v1\",\"kind\":\"Deployment\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"webhook\",\"app.kubernetes.io/instance\":\"cert-manager\",\"app.kubernetes.io/managed-by\":\"Tiller\",\"app.kubernetes.io/name\":\"webhook\",\"helm.sh/chart\":\"cert-manager-v0.13.0\"},\"name\":\"cert-manager-webhook\",\"namespace\":\"cert-manager\"},\"spec\":{\"replicas\":1,\"selector\":{\"matchLabels\":{\"app\":\"webhook\",\"app.kubernetes.io/instance\":\"cert-manager\",\"app.kubernetes.io/managed-by\":\"Tiller\",\"app.kubernetes.io/name\":\"webhook\"}},\"template\":{\"metadata\":{\"annotations\":null,\"labels\":{\"app\":\"webhook\",\"app.kubernetes.io/instance\":\"cert-manager\",\"app.kubernetes.io/managed-by\":\"Tiller\",\"app.kubernetes.io/name\":\"webhook\",\"helm.sh/chart\":\"cert-manager-v0.13.0\"}},\"spec\":{\"containers\":[{\"args\":[\"--v=2\",\"--secure-port=10250\",\"--tls-cert-file=/certs/tls.crt\",\"--tls-private-key-file=/certs/tls.key\"],\"env\":[{\"name\":\"POD_NAMESPACE\",\"valueFrom\":{\"fieldRef\":{\"fieldPath\":\"metadata.namespace\"}}}],\"image\":\"quay.io/jetstack/cert-manager-webhook:v0.13.0\",\"imagePullPolicy\":\"IfNotPresent\",\"livenessProbe\":{\"httpGet\":{\"path\":\"/livez\",\"port\":6080,\"scheme\":\"HTTP\"}},\"name\":\"cert-manager\",\"readinessProbe\":{\"httpGet\":{\"path\":\"/healthz\",\"port\":6080,\"scheme\":\"HTTP\"}},\"resources\":{},\"volumeMounts\":[{\"mountPath\":\"/certs\",\"name\":\"certs\"}]}],\"serviceAccountName\":\"cert-manager-webhook\",\"volumes\":[{\"name\":\"certs\",\"secret\":{\"secretName\":\"cert-manager-webhook-tls\"}}]}}}}\n"] "creationTimestamp":"2020-02-14T00:26:08Z" "generation":'\x01' "labels":map["app":"webhook" "app.kubernetes.io/instance":"cert-manager" "app.kubernetes.io/managed-by":"Tiller" "app.kubernetes.io/name":"webhook" "helm.sh/chart":"cert-manager-v0.13.0"] "name":"cert-manager-webhook" "namespace":"cert-manager" "resourceVersion":"49459" "selfLink":"/apis/apps/v1/namespaces/cert-manager/deployments/cert-manager-webhook" "uid":"9845c1ca-4ec0-11ea-8f8a-02f635fc858a"] "spec":map["progressDeadlineSeconds":'\u0258' "replicas":'\x01' "revisionHistoryLimit":'\n' "selector":map["matchLabels":map["app":"webhook" "app.kubernetes.io/instance":"cert-manager" "app.kubernetes.io/managed-by":"Tiller" "app.kubernetes.io/name":"webhook"]] "strategy":map["rollingUpdate":map["maxSurge":"25%" "maxUnavailable":"25%"] "type":"RollingUpdate"] "template":map["metadata":map["creationTimestamp":<nil> "labels":map["app":"webhook" "app.kubernetes.io/instance":"cert-manager" "app.kubernetes.io/managed-by":"Tiller" "app.kubernetes.io/name":"webhook" "helm.sh/chart":"cert-manager-v0.13.0"]] "spec":map["containers":[map["args":["--v=2" "--secure-port=10250" "--tls-cert-file=/certs/tls.crt" "--tls-private-key-file=/certs/tls.key"] "env":[map["name":"POD_NAMESPACE" "valueFrom":map["fieldRef":map["apiVersion":"v1" "fieldPath":"metadata.namespace"]]]] "image":"quay.io/jetstack/cert-manager-webhook:v0.13.0" "imagePullPolicy":"IfNotPresent" "livenessProbe":map["failureThreshold":'\x03' "httpGet":map["path":"/livez" "port":'\u17c0' "scheme":"HTTP"] "periodSeconds":'\n' "successThreshold":'\x01' "timeoutSeconds":'\x01'] "name":"cert-manager" "readinessProbe":map["failureThreshold":'\x03' "httpGet":map["path":"/healthz" "port":'\u17c0' "scheme":"HTTP"] "periodSeconds":'\n' "successThreshold":'\x01' "timeoutSeconds":'\x01'] "resources":map[] "terminationMessagePath":"/dev/termination-log" "terminationMessagePolicy":"File" "volumeMounts":[map["mountPath":"/certs" "name":"certs"]]]] "dnsPolicy":"ClusterFirst" "restartPolicy":"Always" "schedulerName":"default-scheduler" "securityContext":map[] "serviceAccount":"cert-manager-webhook" "serviceAccountName":"cert-manager-webhook" "terminationGracePeriodSeconds":'\x1e' "volumes":[map["name":"certs" "secret":map["defaultMode":'\u01a4' "secretName":"cert-manager-webhook-tls"]]]]]] "status":map["availableReplicas":'\x01' "conditions":[map["lastTransitionTime":"2020-02-14T00:28:33Z" "lastUpdateTime":"2020-02-14T00:28:33Z" "message":"Deployment has minimum availability." "reason":"MinimumReplicasAvailable" "status":"True" "type":"Available"] map["lastTransitionTime":"2020-02-14T00:26:08Z" "lastUpdateTime":"2020-02-14T00:28:33Z" "message":"ReplicaSet \"cert-manager-webhook-5c8cf6d9d4\" has successfully progressed." "reason":"NewReplicaSetAvailable" "status":"True" "type":"Progressing"]] "observedGeneration":'\x01' "readyReplicas":'\x01' "replicas":'\x01' "updatedReplicas":'\x01']]}
 - for: "STDIN": Deployment.apps "cert-manager-webhook" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app":"webhook", "app.kubernetes.io/instance":"cert-manager", "app.kubernetes.io/managed-by":"skaffold-v1.4.0", "app.kubernetes.io/name":"webhook", "helm.sh/chart":"cert-manager-v0.13.0", "skaffold.dev/builder":"local", "skaffold.dev/cleanup":"true", "skaffold.dev/deployer":"kustomize", "skaffold.dev/docker-api-version":"1.40", "skaffold.dev/profile.0":"testCluster", "skaffold.dev/run-id":"ea787d57-32f1-4d78-90d6-df128aea74fd", "skaffold.dev/tag-policy":"git-commit", "skaffold.dev/tail":"true"}: `selector` does not match template `labels`
```

`kustomize build . | kubectl apply -f -` applies properly
`skaffold run -p testCluster` fails with the error above,  it throws several errors but they are all very similar 

### Expected behavior
deploy works properly

### Information

- Skaffold version: 1.3.1, 1.4.0
- Operating system: OSX
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: cert-manager
profiles:
- name: testCluster
  deploy:
    kustomize:
      paths:
      - deploy/testCluster
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold <command>`
3. ...

### PR DESCRIPTION
**Pull request by dgageot**
When a Kubernetes resource has pre-existing labels, we must not change their values. Otherwise, we can break a label selector such as the one used in Deployments.

Fixes #3718

Signed-off-by: David Gageot <david@gageot.net>

### CODE REVIEW

File: pkg/skaffold/deploy/labels_test.go [hunk 1]
```diff
@@ -0,0 +1,117 @@
...
+				"key2": "value2",
+			},
+		},
+		{
+			description: "add labels",
+			existingLabels: map[string]string{
+				"key0": "value0",
+			},
+			appliedLabels: map[string]string{
+				"key0": "ignored",
```
Comment (briandealwis) [inline pkg/skaffold/deploy/labels_test.go:72]: consider `should-be-ignored` to be more explicit?

File: pkg/skaffold/deploy/kubectl/labels_test.go [hunk 2]
```diff
@@ -87,6 +86,7 @@ spec:
 `)}
 
 	resultManifest, err := manifests.SetLabels(map[string]string{
+		"key0": "ignored",
```
Comment (briandealwis) [inline pkg/skaffold/deploy/kubectl/labels_test.go:89]: consider `should-be-ignored` to be more explicit?

File: pkg/skaffold/deploy/labels_test.go [hunk 3]
```diff
@@ -0,0 +1,117 @@
...
+					APIVersion: "apps/v1",
+					Kind:       "Deployment",
+				},
+				ObjectMeta: metav1.ObjectMeta{
+					Name:   "foo",
+					Labels: test.existingLabels,
+				},
+			}
+
+			// Mock Kubernetes
```
Comment (briandealwis) [inline pkg/skaffold/deploy/labels_test.go:95]: Do not taunt Kubernetes :-)

File: pkg/skaffold/deploy/labels_test.go [hunk 4]
```diff
@@ -0,0 +1,117 @@
+/*
+Copyright 2019 The Skaffold Authors
```
Comment (nkubala) [inline pkg/skaffold/deploy/labels_test.go:2]: nit: 2020
