### PR TITLE
Fix portforward flake

### LINKED ISSUE #2787: TestDevPortForward is flaky
https://travis-ci.com/GoogleContainerTools/skaffold/jobs/230109409

```
--- FAIL: TestDevPortForward (146.37s)
    dev_test.go:201: waiting for connection...
    dev_test.go:296: event received timestamp:<seconds:1567436510 nanos:667158576 > event:<metaEvent:<entry:"Starting Skaffold: &{Version:v0.37.0-86-g4e37814 ConfigVersion:skaffold/v1beta15 GitVersion: GitCommit:4e37814bd0a4c5cf555b1f234a0a47d8476cc12d GitTreeState:clean BuildDate:2019-09-02T14:53:18Z GoVersion:go1.12.9 Compiler:gc Platform:linux/amd64}" > > 
    dev_test.go:296: event received timestamp:<seconds:1567436510 nanos:725595941 > event:<buildEvent:<artifact:"gcr.io/k8s-skaffold/leeroy-app" status:"In Progress" > > entry:"Build started for artifact gcr.io/k8s-skaffold/leeroy-app" 
    dev_test.go:296: event received timestamp:<seconds:1567436510 nanos:725924951 > event:<buildEvent:<artifact:"gcr.io/k8s-skaffold/leeroy-web" status:"In Progress" > > entry:"Build started for artifact gcr.io/k8s-skaffold/leeroy-web" 
    dev_test.go:296: event received timestamp:<seconds:1567436510 nanos:728803392 > event:<buildEvent:<artifact:"gcr.io/k8s-skaffold/leeroy-web" status:"Complete" > > entry:"Build completed for artifact gcr.io/k8s-skaffold/leeroy-web" 
    dev_test.go:296: event received timestamp:<seconds:1567436510 nanos:738410480 > event:<buildEvent:<artifact:"gcr.io/k8s-skaffold/leeroy-app" status:"Complete" > > entry:"Build completed for artifact gcr.io/k8s-skaffold/leeroy-app" 
    dev_test.go:296: event received timestamp:<seconds:1567436514 nanos:777816445 > event:<deployEvent:<status:"In Progress" > > entry:"Deploy started" 
    dev_test.go:296: event received timestamp:<seconds:1567436515 nanos:159111034 > event:<deployEvent:<status:"Complete" > > entry:"Deploy complete" 
    dev_test.go:287: event received timestamp:<seconds:1567436515 nanos:243112934 > event:<portEvent:<localPort:9000 remotePort:8080 namespace:"default" resourceType:"deployment" resourceName:"leeroy-web" > > entry:"Forwarding container  to local port 9000" 
    dev_test.go:287: event received timestamp:<seconds:1567436515 nanos:246233817 > event:<portEvent:<localPort:50051 remotePort:50051 namespace:"skaffoldspths" resourceType:"service" resourceName:"leeroy-app" > > entry:"Forwarding container  to local port 50051" 
    dev_test.go:292: Detected service/leeroy-app is forwarded to port 50051
    dev_test.go:296: event received timestamp:<seconds:1567436519 nanos:317692442 > event:<buildEvent:<artifact:"gcr.io/k8s-skaffold/leeroy-app" status:"In Progress" > > entry:"Build started for artifact gcr.io/k8s-skaffold/leeroy-app" 
    dev_test.go:296: event received timestamp:<seconds:1567436519 nanos:319870088 > event:<buildEvent:<artifact:"gcr.io/k8s-skaffold/leeroy-app" status:"In Progress" > > entry:"Build started for artifact gcr.io/k8s-skaffold/leeroy-app" 
    dev_test.go:296: event received timestamp:<seconds:1567436522 nanos:372002592 > event:<buildEvent:<artifact:"gcr.io/k8s-skaffold/leeroy-app" status:"Complete" > > entry:"Build completed for artifact gcr.io/k8s-skaffold/leeroy-app" 
    dev_test.go:296: event received timestamp:<seconds:1567436524 nanos:377053678 > event:<deployEvent:<status:"In Progress" > > entry:"Deploy started" 
    dev_test.go:296: event received timestamp:<seconds:1567436524 nanos:647508646 > event:<deployEvent:<status:"Complete" > > entry:"Deploy complete" 
    dev_test.go:287: event received timestamp:<seconds:1567436524 nanos:655748164 > event:<portEvent:<localPort:50051 remotePort:50051 namespace:"skaffoldspths" resourceType:"service" resourceName:"leeroy-app" > > entry:"Forwarding container  to local port 50051" 
    dev_test.go:292: Detected service/leeroy-app is forwarded to port 50051
    dev_test.go:316: Timed out waiting for response from port 50051
```

### PR DESCRIPTION
**Pull request by balopat**
Fixes #2787.

### CODE REVIEW

File: integration/dev_test.go [hunk 1]
```diff
@@ -315,21 +315,22 @@ func assertResponseFromPort(t *testing.T, port int, expected string) {
 		case <-ctx.Done():
 			t.Fatalf("Timed out waiting for response from port %d", port)
 		case <-time.After(1 * time.Second):
-			resp, err := http.Get(fmt.Sprintf("http://%s:%d", util.Loopback, port))
+			client := http.Client{Timeout: 1 * time.Second}
```
Comment (balopat) [inline integration/dev_test.go]: this is the fix - I expect that sometimes the client would just hang in broken connections. This helps get over that issue and forces a retry.
