### PR TITLE
Error instead of opening interactive prompt with --force init

### LINKED ISSUE #3221: Skaffold init in force mode still opens interactive mode when choice is ambiguous
Setup:
* Use https://github.com/GoogleCloudPlatform/cloud-code-samples/tree/master/java/java-hello-world project
* Remove `skaffold.yaml`
* Run 
```
skaffold init --analyze --XXenableJibInit
{"builders":[{"name":"Docker","payload":{"path":"Dockerfile"}},{"name":"Jib Maven Plugin","payload":{"path":"pom.xml"}}],"images":[{"name":"java-hello-world","foundMatch":false}]}
```
* Add `--force`, remove `--analyze` to try to force configuration:
```
skaffold init --force --XXenableJibInit
? Choose the builder to build image java-hello-world  [Use arrows to move, space to select, type to filter]
> Docker (Dockerfile)
  Jib Maven Plugin (pom.xml)
  None (image not built from these sources)
```

*Expected*: skaffold to fail with non-zero code indicating it cannot force the ambiguous configurations.

### PR DESCRIPTION
**Pull request by TadCordle**
Fixes #3221.

`skaffold init --force` now shows an error if all builder/image pairs can't be automatically resolved.

### CODE REVIEW

File: pkg/skaffold/initializer/init_test.go [hunk 1]
```diff
@@ -395,9 +418,12 @@ func TestResolveBuilderImages(t *testing.T) {
 				return choices[0], nil
 			})
 
-			pairs, err := resolveBuilderImages(test.buildConfigs, test.images)
+			pairs, err := resolveBuilderImages(test.buildConfigs, test.images, test.force)
 
-			t.CheckNoError(err)
+			t.CheckError(test.shouldErr, err)
```
Comment (dgageot) [inline pkg/skaffold/initializer/init_test.go]: `t.CheckErrorAndDeepEqual(test.shouldErr, err, test.expectedPairs, pairs)`
