### PR TITLE
Version can be in the process of being released

### LINKED ISSUE #3617: Release process broken.
### Expected behavior
On a release PR, like #3616 Travis test should pass.

### Actual behavior
On release PR, `./hack/check-samples.sh` script failed

e.g:  https://travis-ci.com/GoogleContainerTools/skaffold/jobs/282115609

This is due to recent PR https://github.com/GoogleContainerTools/skaffold/pull/3539

### Workaround
Change release process to 
1. Create release branch say release-1.3
2. Create a PR and get it approved. Ignore the travis failure. 
3. Create release TAG and push to upstream on the release branch
    - wait for the triggered built to complete.
4. Rerun the Travis job.  
5. Finally merge the PR

### PR DESCRIPTION
**Pull request by dgageot**
Fixes #3617

Signed-off-by: David Gageot <david@gageot.net>

### CODE REVIEW

File: hack/versions/pkg/version/version.go [hunk 1]
```diff
@@ -32,9 +32,20 @@ import (
...
 	current := strings.TrimPrefix(latest.Version, "skaffold/")
 	logrus.Infof("Current Skaffold version: %s", current)
-	logrus.Infof("checking for released status of %s...", current)
+
+	config, err := ioutil.ReadFile("pkg/skaffold/schema/latest/config.go")
+	if err != nil {
+		logrus.Fatalf("failed to read latest config: %s", err)
+	}
+
+	if strings.Contains(string(config), "This config version is already released") {
```
Comment (tejal29) [inline hack/versions/pkg/version/version.go]: Can you look for `hack/versions/pkg/schema/comment.go#releasesComment` instead of this string. 
`./hack/release.sh` actually add the comment with this constant.

Comment (dgageot) [reply hack/versions/pkg/version/version.go]: Done. Thanks for the feedback!

**Comment by dgageot** [comment]
Don't know what's going on on Kokoro. Docker doesn't respond

**Comment by tejal29** [comment]
> Don't know what's going on on Kokoro. Docker doesn't respond

This was due to Kaniko Outage https://github.com/GoogleContainerTools/kaniko/issues/1002
Its now fixed. i will give it another try!
