### PR TITLE
Fix absolute path substitution in configs imported as dependencies.

### LINKED ISSUE #5388: Artifact workspace and other `filepath` type fields not being set correctly in configs imported as dependencies
Consider the directory:
```
.
├── foo
│   └── skaffold.yaml
└── skaffold.yaml
```
where `./skaffold.yaml` is:
```yaml
apiVersion: skaffold/v2beta12
kind: Config
requires:
  - path: foo
```
and `./foo/skaffold.yaml` is:
```yaml
apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: cfg1
requires:
  - configs: [cfg2]

---

apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: cfg2
build:
  artifacts:
  - image: foo
```
### Expected behavior
If I run `skaffold diagnose --yaml-only`, I expect:

```yaml
apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: cfg2
build:
  artifacts:
  - image: foo
    context: /Users/gaghosh/Code/Hack/foobar/foo
...
```

### Actual behavior
I actually get:

```yaml
apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: cfg2
build:
  artifacts:
  - image: foo
    context: .
...
```

The `build.context` isn't resolved to the absolute path for the config `cfg2` that's imported as a dependency in `./skaffold.yaml`

### PR DESCRIPTION
**Pull request by gsquared94**
Fixes #5388

### CODE REVIEW

File: cmd/skaffold/app/cmd/parse_config.go [hunk 1]
```diff
@@ -184,19 +191,22 @@ func processEachDependency(d latest.ConfigDependency, fPath string, required boo
...
+			return nil, fmt.Errorf("could not find skaffold config %s that is referenced as a dependency in config %s", path, cfgOpts.file)
 		}
-		return nil, fmt.Errorf("parsing dependencies for skaffold config %s: %w", fPath, err)
+		return nil, fmt.Errorf("parsing dependencies for skaffold config %s: %w", cfgOpts.file, err)
 	}
 	if fi.IsDir() {
 		path = filepath.Join(path, "skaffold.yaml")
 	}
-	depConfigs, err := getConfigs(configOpts{file: path, selection: d.Names, profiles: depProfiles, isRequired: required, isDependency: path != fPath}, opts, r)
+	cfgOpts.isDependency = cfgOpts.isDependency || path != cfgOpts.file
```
Comment (gsquared94) [inline cmd/skaffold/app/cmd/parse_config.go:206]: The main change in this PR is:
```diff
- cfgOpts.isDependency = path != cfgOpts.file
+ cfgOpts.isDependency = cfgOpts.isDependency || path != cfgOpts.file
```
Other changes are just reordering functions.

Comment (gsquared94) [reply cmd/skaffold/app/cmd/parse_config.go:206]: `isDependency` defines if the current config is an imported config vs the main config. We want to resolve absolute file paths for properties in imported configs and not on the main config. For multiple configs defined in the same file just checking `path != cfgOpts.file` was causing some imported configs to have `isDependency` as false.

Comment (nkubala) [reply cmd/skaffold/app/cmd/parse_config.go:206]: thanks for this explanation, makes reviewing a lot easier 👍

**Review by nkubala — APPROVED** [review]
