### PR TITLE
[kaniko] Better error message when upload fails

### LINKED ISSUE #3944: copying sources: uploading build context: exit status 1
This is my `skaffold.yaml`. It's very straightforward:
```
apiVersion: skaffold/v2beta1
kind: Config
metadata:
  name: spring-boot-slab
build:
  artifacts:
  - image: skaffold-covid-backend
    kaniko: {}
  cluster: {}
deploy:
  kubectl:
    manifests:
    - k8s/*
```
When I'm trying to build it:
```
$ skaffold build --default-repo=registry.local:5000 --verbosity=debug
INFO[0000] Skaffold &{Version:v1.7.0 ConfigVersion:skaffold/v2beta1 GitVersion: GitCommit:145f59579470eb1f0a7f40d8e0924f8716c6f05b GitTreeState:clean BuildDate:2020-04-02T21:49:58Z GoVersion:go1.14 Compiler:gc Platform:linux/amd64} 
DEBU[0000] validating yamltags of struct SkaffoldConfig 
DEBU[0000] validating yamltags of struct Metadata       
DEBU[0000] validating yamltags of struct Pipeline       
DEBU[0000] validating yamltags of struct BuildConfig    
DEBU[0000] validating yamltags of struct Artifact       
DEBU[0000] validating yamltags of struct ArtifactType   
DEBU[0000] validating yamltags of struct KanikoArtifact 
DEBU[0000] validating yamltags of struct TagPolicy      
DEBU[0000] validating yamltags of struct GitTagger      
DEBU[0000] validating yamltags of struct BuildType      
DEBU[0000] validating yamltags of struct ClusterDetails 
DEBU[0000] validating yamltags of struct DeployConfig   
DEBU[0000] validating yamltags of struct DeployType     
DEBU[0000] validating yamltags of struct KubectlDeploy  
DEBU[0000] validating yamltags of struct KubectlFlags   
INFO[0000] Using kubectl context: k3s-traefik-v2        
DEBU[0000] Using builder: cluster                       
DEBU[0000] setting Docker user agent to skaffold-v1.7.0 
Generating tags...
 - skaffold-covid-backend -> DEBU[0000] Running command: [git describe --tags --always] 
DEBU[0000] Command output: [c5dfd81
]                   
DEBU[0000] Running command: [git status . --porcelain]  
DEBU[0000] Command output: [ M skaffold.yaml
?? k8s/configmap.yaml
] 
registry.local:5000/skaffold-covid-backend:c5dfd81-dirty
INFO[0000] Tags generated in 3.135415ms                 
Checking cache...
 - skaffold-covid-backend: WARN[0016] error checking cache, caching may not work as expected: getting hash for artifact skaffold-covid-backend: getting dependencies for "skaffold-covid-backend": file pattern [target/*.jar] must match at least one file 
Error checking cache. Rebuilding.
INFO[0016] Cache check complete in 16.225444103s        
Building [skaffold-covid-backend]...
DEBU[0016] getting client config for kubeContext: ``    
INFO[0016] Waiting for kaniko-lmf99 to be initialized   
DEBU[0017] Running command: [kubectl --context k3s-traefik-v2 exec -i kaniko-lmf99 -c kaniko-init-container -n skaffold -- tar -xf - -C /kaniko/buildcontext] 
FATA[0017] build failed: building [skaffold-covid-backend]: copying sources: uploading build context: exit status 1
```

As you can see:

> WARN[0016] error checking cache, caching may not work as expected: getting hash for artifact skaffold-covid-backend: getting dependencies for "skaffold-covid-backend": file pattern [target/*.jar] must match at least one file 
Error checking cache. Rebuilding.

And

> DEBU[0017] Running command: [kubectl --context k3s-traefik-v2 exec -i kaniko-lmf99 -c kaniko-init-container -n skaffold -- tar -xf - -C /kaniko/buildcontext] 
FATA[0017] build failed: building [skaffold-covid-backend]: copying sources: uploading build context: exit status 1

My project is a maven project. And my `Dockerfile` is:
```
FROM openjdk:8-jdk-alpine
RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
```
Any ideas?

### PR DESCRIPTION
**Pull request by dgageot**
Fix #3944

Signed-off-by: David Gageot <david@gageot.net>

### CODE REVIEW

File: pkg/skaffold/build/cluster/kaniko.go [hunk 1]
```diff
@@ -95,10 +96,15 @@ func (b *Builder) copyKanikoBuildContext(ctx context.Context, workspace string,
 		buildCtxWriter.Close()
 	}()
 
-	if err := b.kubectlcli.Run(ctx, buildCtx, nil, "exec", "-i", podName, "-c", initContainer, "-n", b.Namespace, "--", "tar", "-xf", "-", "-C", constants.DefaultKanikoEmptyDirMountPath); err != nil {
-		return fmt.Errorf("uploading build context: %w", err)
+	var out bytes.Buffer
+	if err := b.kubectlcli.Run(ctx, buildCtx, &out, "exec", "-i", podName, "-c", initContainer, "-n", b.Namespace, "--", "tar", "-xf", "-", "-C", constants.DefaultKanikoEmptyDirMountPath); err != nil {
```
Comment (briandealwis) [inline pkg/skaffold/build/cluster/kaniko.go:100]: It would be worth a comment that the `err` is useless (`exit status 1`)
