### PR TITLE
Watch files for changes in the correct directory

### LINKED ISSUE #4018: Getting started guide not reloading
### Expected behavior
`skaffold dev` to reload pods when changes are made to source code in the getting-started guide.

### Actual behavior

No reloading, similar to [this old issue](https://github.com/GoogleContainerTools/skaffold/issues/202)

Same problem with the hot-reload example.

### Information

- Skaffold version: 1.8.0 installed via brew
- Operating system: MacOS Mojave 10.14.6 (18G3020)
- Contents of skaffold.yaml:
```yaml
apiVersion: skaffold/v2beta2
kind: Config
build:
  artifacts:
  - image: skaffold-example
deploy:
  kubectl:
    manifests:
      - k8s-*

```

### Steps to reproduce the behavior

- Followed the [quickstart](https://skaffold.dev/docs/quickstart/) on mac osx, to run the getting-started example. App runs fine.

- Changed the print statement in `main.go` from: `fmt.Println("Hello World!")` to `fmt.Println("Hell is setting up kubernetes")`

### Output in verbose mode

I used `scaffold dev -v debug` and the output is as follows:
```
$ skaffold dev -v debug
INFO[0000] starting gRPC server on port 50051           
INFO[0000] starting gRPC HTTP server on port 50052      
INFO[0000] Skaffold &{Version:v1.8.0 ConfigVersion:skaffold/v2beta2 GitVersion: GitCommit:bd280192092e28067f0f52584c8bcb4f4dc480e4 GitTreeState:clean BuildDate:2020-04-18T18:47:13Z GoVersion:go1.14.2 Compiler:gc Platform:darwin/amd64} 
DEBU[0000] Defaulting build type to local build         
DEBU[0000] validating yamltags of struct SkaffoldConfig 
DEBU[0000] validating yamltags of struct Metadata       
DEBU[0000] validating yamltags of struct Pipeline       
DEBU[0000] validating yamltags of struct BuildConfig    
DEBU[0000] validating yamltags of struct Artifact       
DEBU[0000] validating yamltags of struct ArtifactType   
DEBU[0000] validating yamltags of struct DockerArtifact 
DEBU[0000] validating yamltags of struct TagPolicy      
DEBU[0000] validating yamltags of struct GitTagger      
DEBU[0000] validating yamltags of struct BuildType      
DEBU[0000] validating yamltags of struct LocalBuild     
DEBU[0000] validating yamltags of struct DeployConfig   
DEBU[0000] validating yamltags of struct DeployType     
DEBU[0000] validating yamltags of struct KubectlDeploy  
DEBU[0000] validating yamltags of struct KubectlFlags   
INFO[0000] Using kubectl context: minikube              
DEBU[0000] Using builder: local                         
DEBU[0000] Running command: [minikube docker-env --shell none] 
DEBU[0000] Command output: [DOCKER_TLS_VERIFY=1
DOCKER_HOST=tcp://192.168.64.2:2376
DOCKER_CERT_PATH=/Users/thc29/.minikube/certs
MINIKUBE_ACTIVE_DOCKERD=minikube
] 
DEBU[0000] setting Docker user agent to skaffold-v1.8.0 
DEBU[0000] push value not present, defaulting to false because localCluster is true 
Listing files to watch...
 - skaffold-example
DEBU[0000] Found dependencies for dockerfile: [{main.go /go true}] 
INFO[0000] List generated in 8.654ms                    
Generating tags...
 - skaffold-example -> DEBU[0000] Running command: [git describe --tags --always] 
DEBU[0000] Command output: [v1.8.0-32-ged51e35b9
]      
DEBU[0000] Running command: [git status . --porcelain]  
DEBU[0001] Command output: [ M examples/getting-started/main.go
] 
skaffold-example:v1.8.0-32-ged51e35b9-dirty
INFO[0001] Tags generated in 110.568577ms               
Checking cache...
DEBU[0001] Found dependencies for dockerfile: [{main.go /go true}] 
 - skaffold-example: Found Locally
INFO[0001] Cache check complete in 10.245903ms          
Tags used in deployment:
 - skaffold-example -> skaffold-example:7a1ebacc0b27fba6f73e1f67c1fb9f600b0bf99f33c8be33d91a2f615e169dd4
   local images can't be referenced by digest. They are tagged and referenced by a unique ID instead
Starting deploy...
DEBU[0001] Running command: [kubectl version --client -ojson] 
DEBU[0001] Command output: [{
  "clientVersion": {
    "major": "1",
    "minor": "18",
    "gitVersion": "v1.18.2",
    "gitCommit": "52c56ce7a8272c798dbc29846288d7cd9fbae032",
    "gitTreeState": "clean",
    "buildDate": "2020-04-16T23:34:25Z",
    "goVersion": "go1.14.2",
    "compiler": "gc",
    "platform": "darwin/amd64"
  }
}
] 
DEBU[0001] Running command: [kubectl --context minikube create --dry-run -oyaml -f /Users/thc29/source/thclark/skaffold-test/skaffold/examples/getting-started/k8s-pod.yaml] 
DEBU[0002] Command output: [apiVersion: v1
kind: Pod
metadata:
  name: getting-started
  namespace: default
spec:
  containers:
  - image: skaffold-example
    name: getting-started
], stderr: W0423 18:40:17.749816   72208 helpers.go:535] --dry-run is deprecated and can be replaced with --dry-run=client. 
DEBU[0002] manifests with tagged images: apiVersion: v1
kind: Pod
metadata:
  name: getting-started
  namespace: default
spec:
  containers:
  - image: skaffold-example:7a1ebacc0b27fba6f73e1f67c1fb9f600b0bf99f33c8be33d91a2f615e169dd4
    name: getting-started 
DEBU[0002] manifests with labels apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/managed-by: skaffold-v1.8.0
    skaffold.dev/builder: local
    skaffold.dev/cleanup: "true"
    skaffold.dev/deployer: kubectl
    skaffold.dev/docker-api-version: "1.40"
    skaffold.dev/run-id: 62f82011-e8cc-4124-a566-b69c2c7ef732
    skaffold.dev/tag-policy: git-commit
    skaffold.dev/tail: "true"
  name: getting-started
  namespace: default
spec:
  containers:
  - image: skaffold-example:7a1ebacc0b27fba6f73e1f67c1fb9f600b0bf99f33c8be33d91a2f615e169dd4
    name: getting-started 
DEBU[0002] 1 manifests to deploy. 1 are updated or new  
DEBU[0002] Running command: [kubectl --context minikube apply -f - --force --grace-period=0] 
 - pod/getting-started created
INFO[0002] Deploy complete in 1.280263852s              
Waiting for deployments to stabilize...
DEBU[0002] getting client config for kubeContext: ``    
Deployments stabilized in 69.194001ms
DEBU[0002] getting client config for kubeContext: ``    
DEBU[0002] Change detected <nil>                        
DEBU[0002] Found dependencies for dockerfile: [{main.go /go true}] 
Watching for changes...
DEBU[0003] Found dependencies for dockerfile: [{main.go /go true}] 
INFO[0003] Streaming logs from pod: getting-started container: getting-started 
DEBU[0003] Running command: [kubectl --context minikube logs --since=3s -f getting-started -c getting-started --namespace default] 
[getting-started] Hello World!
[getting-started] Hello World!
[getting-started] Hello World!
[getting-started] Hello World!
[getting-started] Hello World!
[getting-started] Hello World!
[getting-started] Hello World!
[getting-started] Hello World!
...ad infinitum...
```
```

### PR DESCRIPTION
**Pull request by dgageot**
On macOS, $PWD can have a different case that the actual current working directory. That happens for example if one does:
`cd /home/me/MY-PROJECT` before running Skaffold, instead of `cd /home/me/my-project`.

In such situation, the file watcher will fail to detect changes.

To solve that, we force `os.Getwd()` not to use $PWD.

Fixes #4018

Signed-off-by: David Gageot <david@gageot.net>

### CODE REVIEW

File: pkg/skaffold/trigger/workdir.go [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+import (
+	"os"
+	"runtime"
+)
+
+// On macOS, $PWD can have a different case that the actual current
+// working directory. That happens for example if one does:
+// `cd /home/me/MY-PROJECT` before running Skaffold,
+// instead of `cd /home/me/my-project`.
+// In such situation, the file watcher will fail to detect changes.
```
Comment (briandealwis) [inline pkg/skaffold/trigger/workdir.go:28]:
```suggestion
// In such a situation, the file watcher will fail to detect changes.
```

Did you figure out why the watcher misses these changes? (Is there a fix we can submit upstream?)

**Comment by briandealwis** [comment]
Upstream as https://github.com/rjeczalik/notify/issues/96 —  this issue came up in #3109.

File: pkg/skaffold/trigger/triggers.go [hunk 2]
```diff
@@ -163,14 +163,23 @@ func (t *fsNotifyTrigger) LogWatchToUser(out io.Writer) {
 func (t *fsNotifyTrigger) Start(ctx context.Context) (<-chan bool, error) {
 	c := make(chan notify.EventInfo, 100)
 
+	wd, err := RealWorkDir()
```
Comment (briandealwis) [inline pkg/skaffold/trigger/triggers.go:166]: Add a note: `Workaround https://github.com/rjeczalik/notify/issues/96`
