### PR TITLE
Explicitly specify commands that should show surveys and update messages post execution

### LINKED ISSUE #4620: "skaffold completion" includes survey result command in output 🔥
Since the latest update of Homebrew I always get an error / message when I start a new shell (`bash`):

```
bash: Help: command not found
Thank you for offering your feedback on Skaffold! Understanding your experiences and opinions helps us make Skaffold better for you and other users.
   Our survey can be found here: https://forms.gle/BMTbGQXLWSdn7vEs6

To permanently disable the survey prompt, run:
   skaffold config set --survey --global disable-prompt true
```

This is due to the fact that at the end of `/usr/local/etc/bash_completion.d/skaffold` I find the following snippet:

```
...

# ex: ts=4 sw=4 et filetype=sh
Help improve Skaffold! Take a 10-second anonymous survey by running
   skaffold survey
```

I could already drill it down to this line of code: https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/survey/survey.go#L32 but do not have any idea now how this leads to the wrong bash completion rc?

### Expected behavior

Start `bash` without any problems

### Actual behavior

See above (run `bash --login`)

### Information

- Skaffold version: 1.13.0
- Operating system: OS X

### PR DESCRIPTION
**Pull request by gsquared94**
Fixes #4620 

Removes erroneous text generated in command `skaffold completion zsh`
Before:
```
...
compdef _skaffold skaffold
Help improve Skaffold! Take a 10-second anonymous survey by running
   skaffold survey
```
After:
```
...
compdef _skaffold skaffold
```

### CODE REVIEW

File: cmd/skaffold/app/cmd/debug.go [hunk 1]
```diff
@@ -36,6 +36,7 @@ func NewCmdDebug() *cobra.Command {
 		WithDescription("[beta] Run a pipeline in debug mode").
 		WithLongDescription("Similar to `dev`, but configures the pipeline for debugging.").
 		WithCommonFlags().
+		AllowHouseKeepingMessages().
```
Comment (tejal29) [inline cmd/skaffold/app/cmd/debug.go:39]: Can we rename this to `withHouseKeepingMessages()` ?

**Comment by gsquared94** [comment]
> Instead of blacklisting certain commands, I would feel better if this was implemented as a whitelist so as to avoid breaking a future command which we forgot to mark as evaluated.
> 
> For instance, only prompt for the survey for a limited number of commands where it makes sense, like `dev`.

Switched to an allowlist

File: cmd/skaffold/app/cmd/cmd.go [hunk 2]
```diff
@@ -103,6 +108,15 @@ func NewSkaffoldCommand(out, err io.Writer) *cobra.Command {
 			return nil
 		},
 		PersistentPostRun: func(cmd *cobra.Command, args []string) {
+			if !isHouseKeepingMessagesAllowed(cmd) {
```
Comment (tejal29) [inline cmd/skaffold/app/cmd/cmd.go:111]: so, we should also make this check in L95 and not call the `go func` which makes these calls.

Comment (gsquared94) [reply cmd/skaffold/app/cmd/cmd.go]: makes sense

File: cmd/skaffold/app/cmd/debug.go (hunk 1 above)
Comment (gsquared94) [reply cmd/skaffold/app/cmd/debug.go]: done

**Comment by tejal29** [comment]
Can you please add a test `TestCompletion` which only checks if the generated output string does not contain the survey test.

also, add describe the after for `skaffold completion [bash | zsh] in the PR description to indicate the output change.

File: cmd/skaffold/app/cmd/commands_test.go [hunk 3]
```diff
@@ -105,6 +105,11 @@ func TestNewCmdWithFlags(t *testing.T) {
 	testutil.CheckDeepEqual(t, "usage", flags["test"].Usage)
 }
 
+func TestNewCmdWithHouseKeepingMessages(t *testing.T) {
```
Comment (tejal29) [inline cmd/skaffold/app/cmd/commands_test.go:108]: this will ensure if the annotations are added. But this test won't protect us against a regression introduced if someone removed this condition
https://github.com/GoogleContainerTools/skaffold/blob/90530d501a96264c6790d21f50b2972d5d4e36d0/cmd/skaffold/app/cmd/cmd.go#L92


Can you please add a test, where we make sure if output does not contain the messages
```
// Return showDisplayprompt to be always be true.
t.Override(&config.ShouldDisplayPrompt, true)
var buf bytes.Buffer

cmd := NewCmd("").ExactArgs(1, func(ctx context.Context, out io.Writer, args []string) error {
		fmt.Fprintf(out, "test output: %v\n", args)
		return nil
	})
cmd.SetOutput(&buf)
// Make sure the display prompt is not shown
```

Comment (gsquared94) [reply cmd/skaffold/app/cmd/commands_test.go:108]: I think this will be easier to test in an integration test 🤷🏾‍♂️

Comment (nkubala) [reply cmd/skaffold/app/cmd/commands_test.go:108]: @gsquared94 agreed, I think it would be more effective as well

Comment (gsquared94) [reply cmd/skaffold/app/cmd/commands_test.go:108]: added integration tests
