### PR TITLE
Fix analyze update check

### LINKED ISSUE #3686: Skaffold init --analyze output not ideal for parsing by clients
Tested with Skaffold version 1.2. I assume this behavior is still carried forward.

`skaffold init --analyze --XenableJibInit` returns the following output:

```
{"builders":[{"name":"Jib Maven Plugin","payload":{"path":"pom.xml"}}],"images":[{"name":"java-hello-world","foundMatch":false}]}There is a new version (1.3.1) of Skaffold available. Download it at https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
```

Notice the new version / upgrade message after the JSON. This makes it inconvenient for clients trying to parse the json output of this command. Is there a way to suppress this that I may have missed?

### PR DESCRIPTION
**Pull request by balopat**
Fixes #3686.

Unfortunately this piece is hard to test currently.

### CODE REVIEW

File: pkg/skaffold/kubernetes/util.go [hunk 1]
```diff
@@ -100,7 +100,7 @@ func parseKubernetesObjects(filepath string) ([]yamlObject, error) {
 			return nil, errors.Wrap(err, "reading Kubernetes YAML")
 		}
 
-		if !hasRequiredK8sManifestFields(obj) {
+		if !hasRequiredK8sManifestFields(obj, filepath) {
```
Comment (dgageot) [inline pkg/skaffold/kubernetes/util.go]: Is that related?

Comment (balopat) [reply pkg/skaffold/kubernetes/util.go]: no, that was accidental

File: cmd/skaffold/app/cmd/cmd.go [hunk 2]
```diff
@@ -100,6 +100,8 @@ func NewSkaffoldCommand(out, err io.Writer) *cobra.Command {
 
 			if quietFlag {
 				logrus.Debugf("Update check is disabled because of quiet mode")
+			} else if analyze {
```
Comment (dgageot) [inline cmd/skaffold/app/cmd/cmd.go]: The linter wants a switch here
