### PR TITLE
gracefull shutdown RPC even when build is in error

### LINKED ISSUE #3991: Skaffold event API failed to send a failure reason when project not found.
@quoctruong reported

```

C:\Users\quoct\cloudcode-projects\nodejs-hello-world-24>skaffold debug --enable-rpc -v info --port-forward --rpc-http-port 60538 --filename skaffold.yaml --default-repo gcr.io/gcloud-powershell-te
time="2020-04-20T14:32:22-07:00" level=info msg="starting gRPC server on port 50051"
time="2020-04-20T14:32:22-07:00" level=info msg="starting gRPC HTTP server on port 60538"
time="2020-04-20T14:32:22-07:00" level=info msg="Skaffold &{Version:v1.8.0 ConfigVersion:skaffold/v2beta2 GitVersion: GitCommit:bd280192092e28067f0f52584c8bcb4f4dc480e4 GitTreeState:clean BuildDate:2020-04-17T23:01:25Z GoVersion:go1.14 Compiler:gc Platform:windows/amd64}"
time="2020-04-20T14:32:22-07:00" level=info msg="Using kubectl context: gke_gcloud-powershell-testing_us-central1_cluster-3"
Listing files to watch...
time="2020-04-20T14:32:22-07:00" level=info msg="List generated in 1.0017ms"
Generating tags...
 - nodejs-hello-world -> gcr.io/gcloud-powershell-te/nodejs-hello-world:latest
time="2020-04-20T14:32:22-07:00" level=info msg="Tags generated in 995.9µs"
Checking cache...
 - nodejs-hello-world: Found. Pushing
The push refers to repository [gcr.io/gcloud-powershell-te/nodejs-hello-world]
535aa4bfd632: Retrying in 1 second
01fe2b5ec402: Retrying in 2 seconds
ea6156b3ea98: Retrying in 1 second
6c14b4215be4: Retrying in 1 second
e9022e94bf2b: Retrying in 3 seconds
0493dc030ae3: Waiting
0095ff73bb21: Waiting
0fe19df8b8f8: Waiting
b17cc31e431b: Waiting
12cb127eee44: Waiting
604829a174eb: Waiting
fbb641a8b943: Waiting
time="2020-04-20T14:33:19-07:00" level=fatal msg="exiting dev mode because first build failed: pushing image: unknown: Project 'project:gcloud-powershell-te' not found or deleted."
```

Could be related to #3970

### PR DESCRIPTION
**Pull request by tejal29**
Fixes: #3970 
Maybe fixes #3991
**Related**: _Relevant tracking issues, for context_
**Merge before/after**: _Dependent or prerequisite PRs_

**Description**
Another attempt to gracefully shutdown RPC.

1. This is mostly bringing back what #4010 did however, 
`GracefulStop` and `server.Shutdown` wait for all idle connections to close. 
IDES RPC client connections never terminate and go into idle state hence the above functions never return.
In this PR, the `GracefulStop` and `server.Shutdown` are wrapped in a timeout context. 
They wait for max 1 second which is enough to read the last events on the channel.

2. `shutdownAPIServer` was called in `PersistedPostRun`. 
However, `PersistentPostRun` is only called if a command's `RunE` does not result into any error.
https://github.com/spf13/cobra/blob/master/command.go#L843

To make sure, the servers shut down gracefully when an error occurs, we need to call the `shutdownAPIServer` in `RunE` command to execute.

**User facing changes (remove if N/A)**
No.

** events API changes ** 
On any example, please run a command where build would fail. 
e.g. `skaffold  dev --cache-artifacts=false` (remove global default repo setting)

On master 

*** Before ***

```
curl localhost:50052/v1/event_log
....
{"result":{"timestamp":"2020-06-24T05:18:10.565560Z","
        event":{"devLoopEvent":{"status":"In Progress"}},"entry":"DevInit Iteration 0 in progress"}}
{"result":{"timestamp":"2020-06-24T05:18:10.612157Z",
    "event":{"buildEvent":{"artifact":"leeroy-web","status":"In Progress"}},"entry":"Build started for artifact leeroy-web"}}
curl: (18) transfer closed with outstanding read data remaining

```
You never see the build failed and devloop iteration failed events for a failed build.

**On the branch**
```
curl localhost:50052/v1/event_log
....
{"result":{"timestamp":"2020-06-24T05:21:35.823218Z",
   "event":{"devLoopEvent":{"status":"In Progress"}},"entry":"DevInit Iteration 0 in progress"}}
{"result":{"timestamp":"2020-06-24T05:21:35.864723Z",
    "event":{"buildEvent":{"artifact":"leeroy-web","status":"In Progress"}},"entry":"Build started for artifact leeroy-web"}}
{"result":{"timestamp":"2020-06-24T05:21:42.684603Z",
    "event":{"buildEvent":{
                 "artifact":"leeroy-web",
                 "status":"Failed",
                 "err":"could not push image \"leeroy-web:v1.11.0-99-g473026664\": denied: requested access to the resource is denied",
                "errCode":"BUILD_UNKNOWN",
                 "actionableErr":{"errCode":"BUILD_UNKNOWN","message":"could not push image \"leeroy-web:v1.11.0-99-g473026664\": denied: requested access to the resource is denied"}}},"entry":"Build failed for artifact leeroy-web"}}

{"result":{"timestamp":"2020-06-24T05:21:42.684624Z",
      "event":{
             "devLoopEvent":{
             "status":"Failed",
             "err":{
              "errCode":"BUILD_UNKNOWN",
              "message":"couldn't build \"leeroy-web\": could not push image \"leeroy-web:v1.11.0-99-g473026664\": denied: requested access to the resource is denied"}}},
              "entry":"DevInit Iteration 0 failed with error code BUILD_UNKNOWN"}
}
```
On the branch you will see failure events.

**Follow-up Work (remove if N/A)**

### CODE REVIEW

**Comment by tejal29** [comment]
@dgageot Can you please take a look at this?

Thx!

File: pkg/skaffold/server/server.go [hunk 1]
```diff
@@ -34,7 +35,12 @@ import (
 	"github.com/GoogleContainerTools/skaffold/proto"
 )
 
-var srv *server
+var (
+	srv *server
+
+	// waits for 1 second before shutting down the server
+	secondTimeout = 1 * time.Second
```
Comment (balopat) [inline pkg/skaffold/server/server.go:42]: I'd rename this to `forceShutdownTimeout` - the idea is that if `s.GracefulStop()` doesn't halt in this time, we'll forcefully shutdown the server, right?

File: pkg/skaffold/server/server.go [hunk 2]
```diff
@@ -174,9 +193,18 @@ func newHTTPServer(port, proxyPort int) (func() error, error) {
 	}
 	logrus.Infof("starting gRPC HTTP server on port %d", port)
 
+	server := &http.Server{
+		Handler:     mux,
+		ReadTimeout: 10 * time.Second,
```
Comment (balopat) [inline pkg/skaffold/server/server.go:198]: why is this required?

File: cmd/skaffold/app/cmd/cmd.go [hunk 3]
```diff
@@ -115,10 +115,6 @@ func NewSkaffoldCommand(out, err io.Writer) *cobra.Command {
 				}
 			default:
 			}
-
-			if shutdownAPIServer != nil {
```
Comment (balopat) [inline cmd/skaffold/app/cmd/cmd.go:119]: why did we have to move this to the RunE sections? Doesn't the `PersistentPostRun` good enough? I don't understand this change

Comment (tejal29) [reply cmd/skaffold/app/cmd/cmd.go:119]: I explained this in the PR description. Maybe you missed it. Let me know if you are still confused.

File: pkg/skaffold/server/server.go (hunk 1 above)
Comment (balopat) [reply pkg/skaffold/server/server.go]: also, is 1 Second seems tight. I'd raise it to 5 seconds potentially. Also why do we need this? Is this the improvement over David's PR - as s.GracefulStop sometimes hangs? Do we know why it hangs? Can we tackle that root cause instead of forced shutdown with an arbitrary timeout that might or might not work?

File: pkg/skaffold/server/server.go (hunk 2 above)
Comment (tejal29) [reply pkg/skaffold/server/server.go]: removed the `ReadTimeout` since its not required. 
Fixed the `go http.serve(l, mux) to `go server.Serve()`

File: cmd/skaffold/app/cmd/cmd.go (hunk 3 above)
Comment (balopat) [reply cmd/skaffold/app/cmd/cmd.go:119]: ooops, busted! I didn't read your description, I got it now, thank you :D

Comment (balopat) [reply cmd/skaffold/app/cmd/cmd.go:119]: One thing: a comment might be useful - so that people don't factor it out accidentally 6 months down the line this seeming duplication!

File: pkg/skaffold/server/server.go (hunk 1 above)
Comment (balopat) [reply pkg/skaffold/server/server.go]: I read your description - can we add a comment here as well why we are forcing? Just explain the same thing you wrote in the PR that if connections are alive the server never shuts down.

**Comment by tejal29** [comment]
> LGTM but please put the two explanatory comments to the two places for clarity - it is not obvious at all why these design choices were made just from reading the code - and while someone might look at this PRs description, it's best to have this kind of context in the code. Thank you for fixing this!!!

Done!

**Comment by briandealwis** [comment]
I've been digging into this worrying message from `curl`:
```
curl: (18) transfer closed with outstanding read data remaining
```

The grpc-gateway uses `Transfer-Encoding: chunked` with HTTP/1.1 connections.  With `chunked`, each message is sent prefixed with the byte size of the message and a CR-LF:
```console
$ curl -i --raw localhost:50052/v1/events
HTTP/1.1 200 OK
Content-Type: application/json
Grpc-Metadata-Content-Type: application/grpc
Date: Mon, 13 Jul 2020 15:04:10 GMT
Transfer-Encoding: chunked

1b5
{"result":{"timestamp":"2020-07-13T15:04:10.200435Z","event":{"metaEvent":{"entry":"Starting Skaffold: \u0026{Version: ConfigVersion:skaffold/v2beta6 GitVersion: GitCommit: GitTreeState: BuildDate: GoVersion:go1.14.3 Compiler:gc Platform:darwin/amd64}","metadata":{"build":{"numberOfArtifacts":1,"builders":[{"type":"BUILDPACKS","count":1}],"type":"LOCAL"},"deploy":{"deployers":[{"type":"KUBECTL","count":1}],"cluster":"MINIKUBE"}}}}}}

93
{"result":{"timestamp":"2020-07-13T15:04:10.201334Z","event":{"devLoopEvent":{"status":"In Progress"}},"entry":"DevInit Iteration 0 in progress"}}

c1
{"result":{"timestamp":"2020-07-13T15:04:10.299620Z","event":{"buildEvent":{"artifact":"skaffold-buildpacks","status":"In Progress"}},"entry":"Build started for artifact skaffold-buildpacks"}}

201
{"result":{"timestamp":"2020-07-13T15:04:11.777416Z","event":{"buildEvent":{"artifact":"skaffold-buildpacks","status":"Failed","err":"failed to fetch builder image 'gcr.io/buildpacks/builder:v1': error getting credentials - err: exit status 1, out: ``","errCode":"BUILD_UNKNOWN","actionableErr":{"errCode":"BUILD_UNKNOWN","message":"failed to fetch builder image 'gcr.io/buildpacks/builder:v1': error getting credentials - err: exit status 1, out: ``"}}},"entry":"Build failed for artifact skaffold-buildpacks"}}

173
{"result":{"timestamp":"2020-07-13T15:04:11.777773Z","event":{"devLoopEvent":{"status":"Failed","err":{"errCode":"BUILD_UNKNOWN","message":"couldn't build \"skaffold-buildpacks\": failed to fetch builder image 'gcr.io/buildpacks/builder:v1': error getting credentials - err: exit status 1, out: ``"}}},"entry":"DevInit Iteration 0 failed with error code BUILD_UNKNOWN"}}

curl: (18) transfer closed with outstanding read data remaining
```

A chunked connection is normally closed by sending a 0-byte message. But calling `net.http.Server.Shutdown()` to gracefully shutdown the server closes the underlying connection and does not use the [chunked writer's close](https://golang.org/src/net/http/server.go#L400).  Since curl doesn't receive the 0-byte message, it complains that there was outstanding data pending.  I think a case could be made that this is not a graceful shutdown.
