### PR TITLE
Fix spurious logs when dev loop is restarted

### LINKED ISSUE #2791: [skaffold dev] changing skaffold.yaml reprints all the logs
While in a `skaffold dev` loop, I run `touch skaffold.yaml`. This resets the dev loop with no change and it should carry on with the logs where it left them.

Instead:
 + It reprints all the logs for every container involved in the deployment.
 + It print `WARN[0019] signal: killed` for every running pod (I assume it's the kubectl logs being killed)
 + It often prints `<Container was Terminated>` for each container. Even when they are not terminated.

### PR DESCRIPTION
**Pull request by dgageot**
Fix #2791

Signed-off-by: David Gageot <david@gageot.net>

### CODE REVIEW

File: pkg/skaffold/kubernetes/log.go [hunk 1]
```diff
@@ -193,7 +197,10 @@ func (a *LogAggregator) streamRequest(ctx context.Context, headerColor color.Col
 			// Read up to newline
 			line, err := r.ReadString('\n')
 			if err == io.EOF {
-				a.printLogLine(headerColor, prefix, "<Container was Terminated>\n")
+				// Unless the context was interrupted, this means that the container was stopped.
+				if ctx.Err() != context.Canceled {
```
Comment (balopat) [inline pkg/skaffold/kubernetes/log.go]: another time I see this happen is when I run `skaffold dev` after `skaffold run` - the "tail end" of the container logs gets picked up.
