### PR TITLE
Revisited artifact caching

### LINKED ISSUE #2460: Caching fails with horrific error
This issue is a bit hard to reproduce but it very likely to happen to someone getting started with skaffold.

I'm working with a multi-artifact project. I've started building my artifacts locally, with caching enabled. Everything is fine. Now I switch to a remote cluster and I run `skaffold build` again to make sure the images are pushed to the registry. Here's what happens:

```
$ skaffold build --cache-artifacts=true
Generating tags...
 - gcr.io/dga-demo/proxy -> gcr.io/dga-demo/proxy:v1-1-gebf1885a2
 - gcr.io/dga-demo/ref -> gcr.io/dga-demo/ref:v1-1-gebf1885a2
 - gcr.io/dga-demo/game -> gcr.io/dga-demo/game:v1-1-gebf1885a2
 - gcr.io/dga-demo/db -> gcr.io/dga-demo/db:v1-1-gebf1885a2
 - gcr.io/dga-demo/title -> gcr.io/dga-demo/title:v1-1-gebf1885a2
 - gcr.io/dga-demo/ui -> gcr.io/dga-demo/ui:v1-1-gebf1885a2
Tags generated in 174.999283ms
Checking cache...
 - gcr.io/dga-demo/db: Found Locally. Pushing.
 - gcr.io/dga-demo/proxy: Found Locally. Pushing.
 - gcr.io/dga-demo/ref:  - gcr.io/dga-demo/game: Found Locally. Pushing.
Found Locally. Pushing.
 - gcr.io/dga-demo/ui: Found Locally. Pushing.
 - gcr.io/dga-demo/title: Found Locally. Pushing.
ERROR: gcloud crashed (OperationalError): database is locked
ERROR: gcloud crashed (OperationalError): database is locked

If you would like to report this issue, please run the following command:

If you would like to report this issue, please run the following command:
ERROR: gcloud crashed (OperationalError): database is locked
  gcloud feedback
  gcloud feedback

To check gcloud for common problems, please run the following command:
ERROR: gcloud crashed (OperationalError): database is locked

To check gcloud for common problems, please run the following command:

If you would like to report this issue, please run the following command:
  gcloud info --run-diagnostics
  gcloud info --run-diagnostics
  gcloud feedback

If you would like to report this issue, please run the following command:

To check gcloud for common problems, please run the following command:
  gcloud feedback
  gcloud info --run-diagnostics

To check gcloud for common problems, please run the following command:
  gcloud info --run-diagnostics
 - gcr.io/dga-demo/proxy: Not Found. Rebuilding.
 - gcr.io/dga-demo/game: Not Found. Rebuilding.
 - gcr.io/dga-demo/ref: Not Found. Rebuilding.
 - gcr.io/dga-demo/db: Not Found. Rebuilding.
The push refers to repository [gcr.io/dga-demo/ui]
The push refers to repository [gcr.io/dga-demo/title]
59dea2b31d4a: Preparing
f9666c9ea065: Preparing
4060351574d1: Preparing
c14e44c7a04a: Preparing
8f8ce1ee4af3: Preparing
4906c61c139f: Preparing
a464c54f93a9: Preparing
4906c61c139f: Waiting
a464c54f93a9: Waiting
1d056714521f: Preparing
c36cd2fdf5ca: Preparing
a4c333801849: Preparing
6189abe095d5: Preparing
dffd9992ca39: Preparing
932da5156413: Preparing
1d056714521f: Waiting
c36cd2fdf5ca: Waiting
a4c333801849: Waiting
dffd9992ca39: Waiting
6189abe095d5: Waiting
932da5156413: Waiting
^C - gcr.io/dga-demo/title: Not Found. Rebuilding.
 - gcr.io/dga-demo/ui: Not Found. Rebuilding.
Cache check complete in 2.536761104s
Starting build...
Found [docker-desktop] context, using local docker daemon.
Building [gcr.io/dga-demo/proxy]...
Complete in 2.736345156s
```

This happens because all the actions happen in separate go routines.

### PR DESCRIPTION
**Pull request by dgageot**
This is a reimplementation from scratch of the artifact caching.
I tried to remove some of the existing complexity to hopefully make it more robust.

Fixes #2460 #2459 #2458 #2457 #2197 #1740

### CODE REVIEW

File: integration/build_test.go [hunk 1]
```diff
@@ -85,10 +85,14 @@ func TestBuild(t *testing.T) {
...
 			}
 
-			// remove image in case it is already present
 			removeImage(t, test.expectImage)
 			skaffold.Build(test.args...).InDir(test.dir).RunOrFail(t)
 			checkImageExists(t, test.expectImage)
+
+			removeImage(t, test.expectImage)
+			skaffold.Build(append(test.args, "--cache-artifacts=true")...).InDir(test.dir).RunOrFail(t)
+			skaffold.Build(append(test.args, "--cache-artifacts=true")...).InDir(test.dir).RunOrFail(t)
```
Comment (tejal29) [inline integration/build_test.go]: wait, what is the second build doing? We are not testing anything here. we can check for some log statements like 
"re-using cache artifacts.. or something"

File: pkg/skaffold/build/cache/types.go [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+	"io"
+
+	"github.com/GoogleContainerTools/skaffold/pkg/skaffold/build"
+	"github.com/GoogleContainerTools/skaffold/pkg/skaffold/build/tag"
+	"github.com/GoogleContainerTools/skaffold/pkg/skaffold/schema/latest"
+)
+
+type BuildAndTestFn func(context.Context, io.Writer, tag.ImageTags, []*latest.Artifact) ([]build.Artifact, error)
+
+type Cache interface {
```
Comment (tejal29) [inline pkg/skaffold/build/cache/types.go]: The formatting if off in this diff is it?

File: integration/build_test.go (hunk 1 above)
Comment (dgageot) [reply integration/build_test.go]: Yes, I'll try to improve that. I was at least checking that it wasn't failing

File: pkg/skaffold/build/cache/types.go (hunk 2 above)
Comment (dgageot) [reply pkg/skaffold/build/cache/types.go]: Looks like a problem with GitHub.

File: pkg/skaffold/runner/build_deploy.go [hunk 3]
```diff
@@ -33,27 +33,29 @@ func (r *SkaffoldRunner) BuildAndTest(ctx context.Context, out io.Writer, artifa
...
-	bRes, err := r.Builder.Build(ctx, out, tags, artifactsToBuild)
-	if err != nil {
-		return nil, errors.Wrap(err, "build failed")
-	}
-	r.cache.RetagLocalImages(ctx, out, artifactsToBuild, bRes)
-	bRes = append(bRes, res...)
-	if err := r.cache.CacheArtifacts(ctx, artifacts, bRes); err != nil {
-		logrus.Warnf("error caching artifacts: %v", err)
-	}
+		r.hasBuilt = true
```
[the remark this answers is not in the document]
Comment (dgageot) [reply pkg/skaffold/runner/build_deploy.go]: It's used to run the pruning only if something was built. Maybe it could be simplified.

File: pkg/skaffold/build/cache/hash_test.go [hunk 4]
```diff
@@ -18,37 +18,20 @@ package cache
...
 	"testing"
 
-	"github.com/GoogleContainerTools/skaffold/pkg/skaffold/build"
-	"github.com/GoogleContainerTools/skaffold/pkg/skaffold/build/tag"
 	"github.com/GoogleContainerTools/skaffold/pkg/skaffold/schema/latest"
 	"github.com/GoogleContainerTools/skaffold/testutil"
 )
 
-type mockBuilder struct {
+type mockDependencyLister struct {
```
[the remark this answers is not in the document]
Comment (dgageot) [reply pkg/skaffold/build/cache/hash_test.go]: lol, reminds me of https://fr.slideshare.net/dgageot/mockito-chti-jug (slide 5)
Will fix that.

**Comment by dgageot** [comment]
@tejal29 Thank you for reviewing this large PR! I've taken your feedback into account.
Regarding the `CacheBuilder/build.WithCache` idea. Do you have a clear view of what it would look like. I've tried multiple times to improve that part of the code and failed each time. I'm happy to try again! Maybe in a separate PR though.

File: integration/build_test.go (hunk 1 above)
Comment (dgageot) [reply integration/build_test.go]: I've added assertions on the output

**Comment by tejal29** [comment]
no, i dont have a view right now. Was wondering how are you going to re-design this? Maybe this could be a good candidate for design proposal?

File: pkg/skaffold/build/cache/retrieve.go [hunk 5]
```diff
@@ -18,222 +18,131 @@ package cache
...
-			if ok {
-				builtImages[i] = true
-				return
-			}
-			if err != nil {
-				logrus.Debugf("error finding cached artifact for %s: %v", artifacts[i].ImageName, err)
+		result := results[i]
+		switch result := result.(type) {
+		case failed:
+			return nil, errors.Wrap(result.err, "checking cache")
```
Comment (priyawadhwa) [inline pkg/skaffold/build/cache/retrieve.go]: In the past, when caching failed, we would log an error and then rebuild the artifact. I'd still expect that as a user, WDYT?

File: pkg/skaffold/build/cache/retrieve.go [hunk 6]
```diff
@@ -18,222 +18,131 @@ package cache
...
-			})
+		// Image is already built
+		entry := c.artifactCache[result.Hash()]
+		var uniqueTag string
+		if c.imagesAreLocal {
+			// k8s doesn't recognize the imageID or any combination of the image name
+			// suffixed with the imageID, as a valid image name.
+			// So, the solution we chose is to create a tag, just for Skaffold, from
+			// the imageID, and use that in the manifests.
+			uniqueTag = artifact.ImageName + ":" + strings.TrimPrefix(entry.ID, "sha256:")
```
Comment (priyawadhwa) [inline pkg/skaffold/build/cache/retrieve.go]: Since this is used elsewhere, we could move it into a separate function

**Comment by dgageot** [comment]
@tejal29 @priyawadhwa Thanks a lot for the review! I've updated the code to take your feedback into account. I also sneaked in some dead code removal that I had forgotten.

File: pkg/skaffold/build/cache/cache.go [hunk 7]
```diff
@@ -21,90 +21,81 @@ import (
...
-		if err != nil {
-			logrus.Warn("Unable to get list of images from local docker daemon, won't be checked for cache.")
-		}
+		return &noCache{}, nil
 	}
 
-	lc, err := localCluster()
-	if err != nil {
-		logrus.Warn("Unable to determine if using a local cluster, cache may not work.")
+	client, err := newDockerClient(runCtx)
```
Comment (nkubala) [inline pkg/skaffold/build/cache/cache.go]: should we even be trying to create this client if `imagesAreLocal == false`?

File: pkg/skaffold/build/cache/lookup.go [hunk 8]
```diff
@@ -0,0 +1,116 @@
...
+)
+
+func (c *cache) lookupArtifacts(ctx context.Context, tags tag.ImageTags, artifacts []*latest.Artifact) []cacheDetails {
+	details := make([]cacheDetails, len(artifacts))
+
+	var wg sync.WaitGroup
+	for i := range artifacts {
+		wg.Add(1)
+
+		i := i
```
Comment (nkubala) [inline pkg/skaffold/build/cache/lookup.go]: really just asking for my own curiosity: is there any advantage to reassigning the variable here as opposed to just passing it to the goroutine as a parameter?

File: pkg/skaffold/build/cache/lookup.go [hunk 9]
```diff
@@ -0,0 +1,116 @@
...
+func (c *cache) lookupRemote(ctx context.Context, hash, tag string, entry ImageDetails) cacheDetails {
+	if remoteDigest, err := docker.RemoteDigest(tag, c.insecureRegistries); err == nil {
+		// Image exists remotely with the same tag and digest
+		if remoteDigest == entry.Digest {
+			return found{hash: hash}
+		}
+	}
+
+	// Image exists remotely with a different tag
+	fqn := tag + "@" + entry.Digest // Actual tag will be ignored but we need the registry and the digest part of it.
```
Comment (nkubala) [inline pkg/skaffold/build/cache/lookup.go]: are you doing this because go-containerregistry won't let you pass an image name without a tag?

File: pkg/skaffold/build/local/local_test.go [hunk 10]
```diff
@@ -99,9 +99,9 @@ func TestLocalRun(t *testing.T) {
 			pushImages: true,
 			expected: []build.Artifact{{
 				ImageName: "gcr.io/test/image",
-				Tag:       "gcr.io/test/image:tag@sha256:7368613235363a31e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
+				Tag:       "gcr.io/test/image:tag@sha256:51ae7fa00c92525c319404a3a6d400e52ff9372c5a39cb415e0486fe425f3165",
```
Comment (nkubala) [inline pkg/skaffold/build/local/local_test.go]: was there something wrong with the original digest? :)

File: pkg/skaffold/schema/latest/config.go [hunk 11]
```diff
@@ -524,8 +524,6 @@ type Artifact struct {
 
 	// ArtifactType describes how to build an artifact.
 	ArtifactType `yaml:",inline"`
-
-	WorkspaceHash string `yaml:"-,omitempty"`
```
Comment (nkubala) [inline pkg/skaffold/schema/latest/config.go]: just making sure, this won't break any existing configs right?

File: pkg/skaffold/build/cache/cache.go (hunk 7 above)
Comment (dgageot) [reply pkg/skaffold/build/cache/cache.go]: yes for eg when images where built locally and now we switch to a remote cluster and just need to push them.

File: pkg/skaffold/build/cache/lookup.go (hunk 8 above)
Comment (dgageot) [reply pkg/skaffold/build/cache/lookup.go]: same same

File: pkg/skaffold/build/cache/lookup.go (hunk 9 above)
Comment (dgageot) [reply pkg/skaffold/build/cache/lookup.go]: It's because the image name says which registry host to connect to.

File: pkg/skaffold/build/local/local_test.go (hunk 10 above)
Comment (dgageot) [reply pkg/skaffold/build/local/local_test.go]: yes :-) The fake was always computing the same hash which was something like the hash of an empty array

File: pkg/skaffold/schema/latest/config.go (hunk 11 above)
Comment (dgageot) [reply pkg/skaffold/schema/latest/config.go]: No, this is not serialized.

**Comment by dgageot** [comment]
@priyawadhwa I haven't seen that. Let me try
