### PR TITLE
Convert git tag into proper docker tag

### LINKED ISSUE #3344: git tag contains "/" causes docker build failure
### Expected behavior
- Any valid Dockerfile
- git tag name contains "/"
- run skaffold build 
--> expect the image is built and tagged properly

### Actual behavior
skaffold build fails with error message

```
Generating tags...
 - my-docker-repositories.com/helloworld/hw -> cxm-my-docker-repositories.com/helloworld/hw:ms/1.0.0-94-g93057a3
Checking cache...
 - my-docker-repositories.com/helloworld/hw: Not found. Building
Building [my-docker-repositories.com/helloworld/hw]...
FATA[0001] failed to build: build failed: build failed: building [my-docker-repositories.com/helloworld/hw]: build artifact: docker build: Error response from daemon: invalid reference format
```
### Information

- Skaffold version: version... 0.6.0 and 1.0.0
- Operating system: ... MacOS
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: my-docker-repositories.com/helloworld/hw
    context:
      .
deploy:
  kubectl:
    manifests:
    - k8s/hw-dev.yaml

```

### Steps to reproduce the behavior

1. clone any repo
2. git tag tag/slash
3. skaffold build

### PR DESCRIPTION
**Pull request by dgageot**
Fixes #3344

### CODE REVIEW

File: pkg/skaffold/build/tag/git_commit.go [hunk 1]
```diff
@@ -89,9 +90,31 @@ func (c *GitCommit) GenerateFullyQualifiedImageName(workingDir string, imageName
 		return fmt.Sprintf("%s:%s-dirty", imageName, ref), nil
 	}
 
+	ref = gitTagToDockerTag(ref)
+
 	return fmt.Sprintf("%s:%s", imageName, ref), nil
 }
 
+func gitTagToDockerTag(text string) string {
```
Comment (balopat) [inline pkg/skaffold/build/tag/git_commit.go]: Not: I don't think there is anything got specific about this - and it doesn't say what it does: `escapeAndTruncateAsTag`?

File: pkg/skaffold/build/tag/git_commit.go [hunk 2]
```diff
@@ -89,9 +90,31 @@ func (c *GitCommit) GenerateFullyQualifiedImageName(workingDir string, imageName
...
+		} else {
+			break
+		}
+	}
+	withAuthorizedPrefix := authorizedPrefix + withAuthorizedChars[len(authorizedPrefix):]
+
+	if len(withAuthorizedPrefix) > 128 {
+		return withAuthorizedPrefix[0:128]
+	}
+
```
Comment (balopat) [inline pkg/skaffold/build/tag/git_commit.go]: I would also add a warning or maybe debug message for visibility - when tags start to overlap accidentally,this can be a useful hint

File: pkg/skaffold/build/tag/git_commit.go (hunk 1 above)
Comment (balopat) [reply pkg/skaffold/build/tag/git_commit.go]: Or `sanitizeTag` could be another option

**Comment by dgageot** [comment]
Fixed all the nits
