### PR TITLE
Fix flake: Don't rely on variable `allProblems` in test

### LINKED ISSUE #5733: Test flake: TestBuildProblems
Seen on Travis, can't reproduce locally.
```
--- FAIL: TestBuildProblems (0.02s)
/pkg/skaffold/build/TestBuildProblems/build_error_when_docker_is_not_running_with_minikube_local_cluster
    build_problems_test.go:186: string differ (-got, +want):   strings.Join({
        - 	"creating runner: creating builder: getting docker client: gettin",
        - 	"g minikube env: running [/Users/tejaldesai/Downloads/google-clou",
        - 	"d-sdk2/bin/minikube docker-env --shell none -p minikube]\n - stdo",
        - 	"ut: \"\\n\\n\"\n - stderr: \"! Executing \\\"docker container inspect mi",
        - 	`nikube --format={{.State.Status}}\" took an unusually long time:`,
        - 	` 7.36540945s\n* Restarting the docker service may improve perfor`,
        - 	`mance.\nX Exiting due to GUEST_STATUS: state: unknown state \"mi`,
        - 	`nikube\": docker container inspect minikube --format=: exit stat`,
        - 	`us 1\nstdout:\n\n\nstderr:\nCannot connect to the Docker daemon `,
        - 	`at unix:///var/run/docker.sock. Is the docker daemon running?\n\`,
        - 	`n* \n* If the above advice does not help, please let us know: \n`,
        - 	"  - https://github.com/kubernetes/minikube/issues/new/choose\\n\"\n",
        - 	" - cause: exit status 80. If above error is unexpected, please o",
        - 	"pen an issue to report this error at https://github.com/GoogleCo",
        - 	"ntainerTools/skaffold/issues/new",
        + 	"Build Failed. Cannot connect to the Docker daemon at unix:///var",
        + 	"/run/docker.sock. Check if docker is running",
          	".",
          }, "")
```

### PR DESCRIPTION
**Pull request by tejal29**
Fixes #5733 

Add a new class `ProblemCatalog` which will now be used in test instead of global `allErrors` which gets initialized in package inits. 

This change, will make sure we are testing the relevant registered problems and not all. 
This should avoid any regular expressions being missed due to race/ tests running in parallel

### CODE REVIEW

File: pkg/skaffold/errors/problem_catalog.go [hunk 1]
```diff
@@ -0,0 +1,50 @@
+/*
+Copyright 2020 The Skaffold Authors
```
Comment (nkubala) [inline pkg/skaffold/errors/problem_catalog.go:2]: nit:

```suggestion
Copyright 2021 The Skaffold Authors
```

**Review by nkubala — COMMENTED** [review]
one nit otherwise LGTM

File: pkg/skaffold/errors/problem_catalog.go (hunk 1 above)
Comment (tejal29) [reply pkg/skaffold/errors/problem_catalog.go]: oops. will change in follow up. 
Another way to increase my commit count ;)
