### PR TITLE
Use the PreRelease field semver.Version.Pre for update check and telemetry

### LINKED ISSUE #5515: Skaffold update check is broken since v1.19.0
Skaffold update check is broken since release v1.19.0

From @briandealwis testing
```
$ skaffold build -vtrace
INFO[0000] Skaffold &{Version:v1.20.0 ConfigVersion:skaffold/v2beta12 GitVersion: GitCommit:c48e97690d8daffd68141c2a68fcbe3df6f6936a GitTreeState:dirty BuildDate:2021-02-11T22:55:17Z GoVersion:go1.14.14 Compiler:gc Platform:darwin/amd64} 
DEBU[0000] Update check not enabled, skipping.       
```

findings:
#5280, skaffold release pipeline added secret files resulting into dirty git workspace. 
if git tree is dirty for a skaffold version, we assume its coming from a skaffold under development and skip update checks
https://github.com/GoogleContainerTools/skaffold/blob/31b6212b7847d569427bce7a42d9ec414e8a4a13/pkg/skaffold/update/update.go#L74

How to fixes
1) change the release process to not download secrets in github workspace
2) Change the logic to determine if version is released to just match with version string and follows a pattern `vX.Y.Z`
3) add more...

### PR DESCRIPTION
**Pull request by tejal29**
fixes #5515

In this Pr, 
We were relying on `version.GitTree` state being dirty to detect if skaffold binary is dev binary or released.
However, in https://github.com/GoogleContainerTools/skaffold/pull/5280/files#diff-6547f8c009c546989c6d4d936f8eecddf7815e8a40e1924e9a67fec8b24d7132R4, we added a step in the release process which leaves up the git workspace into a dirty state. 

The `semver.Version` has this field of `PreRelease` version which indicates a version is not released. 
1) For binaries built from skaffold dev branches, the git commit will be part of `semver.Version.Pre`
**Note**: in future if we plan to do a pre-release, we wont get any usage metrics for that. It should be fine.
 
Relying on `semver.Version.Pre` instead of `GitTree` being dirty to disable update checks for skaffold binaries under dev.

Also, disable sending telemetry for non released skaffold version by consolidating this logic at one place. 

Future work
- [ ] Add a test in our release pipeline to make sure, update check  is **never** skipped for released version.
- [ ] Determine if `telemetry` should be disabled in non interactive mode.

Testing notes
1) checkout this branchs
2) Make a skaffold binary with `version.version` as release version but `version.gitTreeState=dirty`
```
GOOS=darwin GOARCH=amd64 CGO_ENABLED=1 \
	    go build -gcflags="all=-N -l" -tags "release " -ldflags "-X github.com/GoogleContainerTools/skaffold/pkg/skaffold/version.version=v1.20.0 -X github.com/GoogleContainerTools/skaffold/pkg/skaffold/version.buildDate=2021-03-09T15:08:33Z -X github.com/GoogleContainerTools/skaffold/pkg/skaffold/version.gitCommit=71bd9e69c61025944f34dee763a5b145e7c6afc9 -X github.com/GoogleContainerTools/skaffold/pkg/skaffold/version.gitTreeState=dirty -s -w " -o out/skaffold github.com/GoogleContainerTools/skaffold/cmd/skaffold
```
3) make sure update check is not skipped. does not show ` DEBU[0000] Update check, survey prompt and telemetry disabled for pre release version `
```
cd examples/getting-started && ../../out/skaffold build -v=debug && cd examples/getting-started

```

Testing for a pre-release version or dev version
1) make
2)  you see update check disabled prompt
```
➜  skaffold git:(update_check_released_version) make
GOOS=darwin GOARCH=amd64 CGO_ENABLED=1 \
	    go build -gcflags="all=-N -l" -tags "release " -ldflags "-X github.com/GoogleContainerTools/skaffold/pkg/skaffold/version.version=v1.20.0-43-g07a806d3c -X github.com/GoogleContainerTools/skaffold/pkg/skaffold/version.buildDate=2021-03-09T16:05:26Z -X github.com/GoogleContainerTools/skaffold/pkg/skaffold/version.gitCommit=07a806d3cb76399adbd20fac9b8c0542eb4a91ff -s -w " -o out/skaffold github.com/GoogleContainerTools/skaffold/cmd/skaffold
➜  skaffold git:(update_check_released_version) cd examples/getting-started && ../../out/skaffold build -v=debug
INFO[0000] Skaffold &{Version:v1.20.0-43-g07a806d3c ConfigVersion:skaffold/v2beta13 GitVersion: GitCommit:07a806d3cb76399adbd20fac9b8c0542eb4a91ff BuildDate:2021-03-09T16:05:26Z GoVersion:go1.15.3 Compiler:gc Platform:darwin/amd64} 
DEBU[0000] Update check, survey prompt and telemetry disabled for pre release version 
```

### CODE REVIEW

File: cmd/skaffold/app/cmd/cmd.go [hunk 1]
```diff
@@ -98,19 +98,21 @@ func NewSkaffoldCommand(out, err io.Writer) *cobra.Command {
...
-			logrus.Infof("Skaffold %+v", version)
+			versionInfo := version.Get()
+			logrus.Infof("Skaffold %+v", versionInfo)
 			if !isHouseKeepingMessagesAllowed(cmd) {
 				logrus.Debugf("Disable housekeeping messages for command explicitly")
 				return nil
 			}
 			switch {
+			case preReleaseVersion(versionInfo.Version):
+				logrus.Debugf("Update check, survey prompt and telemetry disabled for pre release version")
```
Comment (briandealwis) [inline cmd/skaffold/app/cmd/cmd.go:109]:
```suggestion
				logrus.Debugf("Update check, survey prompt and telemetry disabled for pre-release version")
```

File: cmd/skaffold/app/cmd/cmd_test.go [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+)
+
+func TestPreReleaseVersion(t *testing.T) {
+	tests := []struct {
+		description string
+		versionStr  string
+		expected    bool
+	}{
+		{
+			description: "pre release version",
```
Comment (briandealwis) [inline cmd/skaffold/app/cmd/cmd_test.go:32]:
```suggestion
			description: "pre-release version",
```

File: cmd/skaffold/app/cmd/cmd_test.go [hunk 3]
```diff
@@ -0,0 +1,52 @@
...
+			versionStr:  "v1.20.0-42-g92900f245-dirty",
+			expected:    true,
+		},
+		{
+			description: "release version",
+			versionStr:  "v1.20.0",
+		},
+		{
+			description: "incorrect version indicates pre release or dev version",
```
Comment (briandealwis) [inline cmd/skaffold/app/cmd/cmd_test.go:41]:
```suggestion
			description: "incorrect version indicates pre-release or dev version",
```

**Review by briandealwis — APPROVED** [review]
